### ISSUE TITLE
Request for 16bit sampling RTL TCP feature

### ISSUE THREAD

**Issue by haveyouwantto** [AlexandreRouma/SDRPlusPlus#1002]
Hello,

I am a user of SDR++ and I appreciate your great work on this program. I would like to request a feature that allows selecting 16bit sampling for `RTL TCP` sources. Although the original RTL TCP does not support 16bit sampling, some other SDR TCP devices, such as `RSP TCP`, provide this feature. This can improve the signal quality and dynamic range of the received data.

Adding this feature would make SDR++ compatible with more SDR TCP devices and software, and enhance the reception performance. I hope you can consider this request and implement it in future versions.

Thank you for your time and effort.

**Comment by AlexandreRouma** [comment]
Any other device than the RTL-SDR is not, and will not be supported over the RTL-TCP protocol.

Use SDR++ server if you want to use a device remotely at high bit depths.
