### ISSUE TITLE
Feature request:  add more Custom Frequency Offsets

### ISSUE THREAD

**Issue by drdatapi** [AlexandreRouma/SDRPlusPlus#1006]
There exists only one Custom Frequency Offset I can set my own.
I wish to have more Custom-Frequency-Offsets, at least 3.
Instead of CUSTOM please add CUSTOM 1, CUSTUM 2, CUSTUM 3....

I use a RSPduo with two Tuners. And every Tuner has its own Offset.
I often switch between the two Tuners. I use one for HF and one for VHF.
A few days ago I installed a Bullseye LNB for QO-100 Satellite reception
and I noticed that this LNB also have its own Offset Frequency. So I need
a third.

Sure....in SDR++ there is a pre-definition for KU-Band LNB (9750 MHz).
But changing the pre definied Frequency with +/- Keys ist not possible.
And I think nearly none LNB hit this Frequency exactly.
So please add CUSTUM 1, CUSTUM 2, CUSTUM 3.......

It could also be usefull for Users who have 2 or 3 different RTL-SDR Sticks connected.

PS:
Thanks for your hard work on SDR++. I am on MacOS and really enjoy the use 
of SDR++, because good SDR Software on MacOS is rare.
Many Thanks!

**Comment by AlexandreRouma** [comment]
This is planned but not at all in this way.
Having mutiple "custom" options is just a bad UI/UX implementation.
The way it'll work is you can add named offsets to the list

**Comment by AlexandreRouma** [comment]
Implemented
![image](https://github.com/user-attachments/assets/44d5bca6-db5e-443c-8073-b1b3a49e707c)
![image](https://github.com/user-attachments/assets/35c21847-81e4-4628-8613-de354db4e843)
