### ISSUE TITLE
[Feature request] Add audio/baseband clip feature

### ISSUE THREAD

**Issue by KaktusXY** [AlexandreRouma/SDRPlusPlus#1015]
**Feature description**
A feature which records audio/baseband constantly (when enabled), but last couple seconds/minutes are only saved when a button is pressed.

similar to #979 but much simpler or like NVIDIA Shadowplay or Twitch clips

**Comment by AlexandreRouma** [comment]
Same issues as #979. Very few use cases and it eats up an insane amount of ram, especially for anything faster than the RTL.
