### ISSUE TITLE
TCP Audio 

### ISSUE THREAD

**Issue by romanremus** [AlexandreRouma/SDRPlusPlus#1018]
**Feature description**
hello everyone, please if it is possible to add to tcp audio the connection of several clients, thank you very much  
to the same tcp 7355 port, more clients can be added. Thank you very much

**Comment by AlexandreRouma** [comment]
I'm not sure what usecase this would cover. Could you elaborate?

**Comment by romanremus** [comment]
of course, I open DSD-FME which has a TCP input with port 7355 but I can open it through sdrsharp because it has a tcp audio plugin, and I like SDR++ more but unfortunately I can only connect one console to TCP.... I open two DSD - FME terminals and I want the input to be able to work with the same port ..... Thank you very much
![2 terminals](https://user-images.githubusercontent.com/54954927/228757486-10ef1da8-6402-4365-b5e6-b517cdae8f53.jpg)

**Comment by romanremus** [comment]
I open several instances because in one terminal I can only see calls and in the other terminal only information, but both connect to the same port as input, namely tcp 7355

**Comment by lwvmobile** [comment]
> I open several instances because in one terminal I can only see calls and in the other terminal only information, but both connect to the same port as input, namely tcp 7355

Remus. Make a second 'Radio'. Give it a different port number, set the radio on the frequency you want, or the same one, and connect to its port number (i.e. `-i tcp:localhost:7356`) under sinks. See image:

![Screenshot from 2023-04-06 17-53-27](https://user-images.githubusercontent.com/59371473/230501032-83e55999-403b-475a-9677-bdb314841bcb.png)

If you need more help, reply to me on DSD-FME issues, no need to make multiple issues here for this.

**Comment by AlexandreRouma** [comment]
The new sink system will instead support multiple simultaneous sinks which I think is a better option.
Allowing for multiple connections at once would complicate the server code quite a bit.

I will close this issue once this new sink system rolls out.

**Comment by AlexandreRouma** [comment]
Reading back the entire convo I don't think this is really relevant to the new sink system, closing.
