### ISSUE TITLE
save and then restore settings or profile

### ISSUE THREAD

**Issue by canislupus11** [AlexandreRouma/SDRPlusPlus#1030]
Possibility to save and then restore settings or profile. The settings should contain at least:
- SDR receiver settings: driver, gain, checkboxes like IQ swap or IQ correction.
- receiver settings: frequency, modulation, filter width.
- waterfall settings: min, max, zoom, colors, resolution and speed.

**Comment by Daniel-from-Germany** [comment]
start sdr++, close sdr++, look for all file in the root directory, sort files by date, backup, done ;)
