### ISSUE TITLE
CAT communication and "IF listening" mode in ham radio

### ISSUE THREAD

**Issue by canislupus11** [AlexandreRouma/SDRPlusPlus#1031]
Ability to communicate with an amateur radio via CAT (rigctl?), especially in "IF listening" mode when the SDR is tuned to a fixed frequency, but clicking on the waterfall will tune the radio according to the distance on the waterfall and taking into account the currently tuned frequency reads from the radio after the CAT .

**Comment by AlexandreRouma** [comment]
the rigctl server is already fully implemented and the rigctl client is partially implemented (duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/174)

**Comment by canislupus11** [comment]
> the rigctl server is already fully implemented and the rigctl client is partially implemented (duplicate of #174)

What about "IF listening" mode?

**Comment by AlexandreRouma** [comment]
that's what the rigctl client does
