### ISSUE TITLE
Mouse wheel bleed-through

### ISSUE THREAD

**Issue by JohBod** [AlexandreRouma/SDRPlusPlus#1034]
_Very_ low priority cosmetic bug :)

**Hardware**
Win10 laptop and Airspy HF+.

**Software**
SDR++ v1.1.0 (Built at 23:49:11, Mar 30 2023)

**Bug Description**
Rolling the mouse wheel to scroll the credits screen works, but it "bleeds through" and changes the frequency. The scrollbar doesn't help as the cred' screen disappears immediately when the bar is clicked.

73 SM6LKM

**Comment by AlexandreRouma** [comment]
It's a known issue but quite unimportant so no priority on a fix.

**Comment by JohBod** [comment]
Of course. That's why I wrote "Very low priority cosmetic bug" ;) It was just an observation.
