### ISSUE TITLE
sdrpp 64 bit bullyeyes debina os pi4

### ISSUE THREAD

**Issue by joewb6** [AlexandreRouma/SDRPlusPlus#1038]
hi

pi4b 64bit raspberry bullyeye os

installed sdrpp from github   64bit package

installed with no notical errors.. i cant find a log file???

but the icon is on my menu list.

when i click it  the sand dial goes around about 3 times
but nothing happens.

no gui.. no beeps, no error windows pop up

why wont it boot?

**Comment by AlexandreRouma** [comment]
There is no 64bit arm version of SDR++ available, you must build it from source yourself using the instructions in the readme.
You probably tried to install an **amd**64 deb file which is for PC only.
