### ISSUE TITLE
Incorrect display on Samsung S20

### ISSUE THREAD

**Issue by ForceNL4** [AlexandreRouma/SDRPlusPlus#1040]
Just one screenshot defines everything, Samsung S20 smarthone specs are out, Android 13 One Ui 5.1
![Screenshot_20230410_001151](https://user-images.githubusercontent.com/109143790/230798930-1aff5820-2703-40ef-8771-60e630779283.jpg)

Google translate

**Comment by AlexandreRouma** [comment]
Hi,

For the top bar, it's an a known issue, please follow this issue instead to know when a fix rolls out: https://github.com/AlexandreRouma/SDRPlusPlus/issues/774

For the menu, grab the line between the waterfall and menu and drag it to make the menu wider (it's not super easy on mobile but try it on desktop and you'll understand how it works)
