### ISSUE TITLE
SDRPlay as source in Mac Bundle 

### ISSUE THREAD

**Issue by chuckurbis** [AlexandreRouma/SDRPlusPlus#1053]
**Feature description**
Not sure if this should be a feature or a bug, but is it possible to get SDRPlay as a source in the bundled version of SDR++ for mac?

I see that the dlyib is in the bundle, but I do not see it in the source options when I run the program on my M1 macbook. 

I saw mentioned somewhere that I may need to update a config.json to include it. Is that just in build mode?

**Comment by AlexandreRouma** [comment]
The module is available on MacOS. You are expected to install the SDRplay API yourself as it is proprietary can not be redistributed with the software.

You cannot however use the rebuilt bundle on M1 with the SDRplay as it's built for intel and will not accept the M1 version of the API.

Your only option is to build the bundle from source.
