### ISSUE TITLE
Show and set squelch on the signal level meter

### ISSUE THREAD

**Issue by sergeibit** [AlexandreRouma/SDRPlusPlus#1059]
**Feature description**

I would like to suggest a new control to be added on the signal level meter.

![squelchmeter](https://user-images.githubusercontent.com/1696875/236948331-3a6d5744-be88-4115-b8b7-edac7a79cee7.png)

It would consist in a small marker over the signal level meter showing the current squelch cut level.

Additionally, it would be great to control the squelch level on the marker itself, either by dragging the marker or by using the scroll wheel over it.

**Comment by AlexandreRouma** [comment]
It is NOT a level meter. It's a SNR meter.
