### ISSUE TITLE
Phantom carrier that travels with tuned frequency

### ISSUE THREAD

**Issue by IdontKnowWhatToNameThisAccount** [AlexandreRouma/SDRPlusPlus#1064]
Device: RTL-SDR Blog V3 Donge (yes, its genuine)
Operating System: Windows 10 and Linux Mint 20.3

Perhaps this is a noob question but I couldnt find anything online.

I've noticed that there is a thin carrier at exactly the frequency I've tuned my sdr to, no matter what frequency I tune it to, even with no antenna attached. The carrier is barely visible when zoomed out since it almost completely disapears behind the frequency marker, but when zoomed in it becomes visible:
![grafik](https://github.com/AlexandreRouma/SDRPlusPlus/assets/55452827/b6fbd1ac-d562-403f-ad75-e52e2d4fa1cf)

This carrier doesnt appear when using SDR# so I think this is a problem with SDRpp?

**Comment by AlexandreRouma** [comment]
It's the DC spike visible on most SDR, google it for more info.
Enable IQ correction to get rid of it (SDR# has this option enabled by default)
