### ISSUE TITLE
Rasp Pi 4 SDR++ locked at 1FPS, unusable

### ISSUE THREAD

**Issue by twfth9** [AlexandreRouma/SDRPlusPlus#1081]
**Hardware**
- CPU: Rasp Pi 4
- RAM: 4GB
- SDR: RTLSDR in USB

**Software**
- Operating System: Raspbian Bullseye 11 64-bit
- SDR++: v1.1.0 built 01:31:35, May 27 2023

**Bug Description**
Hi all,

I've installed SDR++ v1.1.0 on my Rasp Pi 4, but immediately upon startup the program is borderline unresponsive with the UI elements take 4-5 seconds to react to input, even before connecting an sdr. Other programs on the Pi run as normal when opened alongside SDR++. 

Looking at the Debug window I notice the framerate is locked at 1FPS, with a wavering frametime of approx. 1000ms/frame.

With SDR++ running, my Pi 4 is at 2GHz, CPU @ 4-10%, MEM @ 14%, Temps @ 48C, RTLSDR in USB (no change if disconnected). I'm controlling the Pi through VNC. I have other programs installed on the Pi, perhaps some of them are fighting SDR++ over something causing a 1 second timeout? I also have the KrakenSDR software installed on the Pi, but not running nor is the Kraken itself connected.

Anyone else experience something akin to this? Any help/guidance would be greatly appreciated!

**Comment by AlexandreRouma** [comment]
Bug in the graphics driver of the pi. Connect an external monitor and reboot even if you're using it through VNC and you'll notice it starts working
