### ISSUE TITLE
DSP dependencies broken for modules: Weather Sat, Falcon9, KG SSTV

### ISSUE THREAD

**Issue by Szewcson** [AlexandreRouma/SDRPlusPlus#1093]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Bug Description**
DSP sources dir structure and API was changed but this changes are not implemented in decoder modules. They can't be build at the moment, and changes are to big to quickfix it without any knowladge about the code base.

**Steps To Reproduce**
1. execute `cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DOPT_BUILD_METEOR_DEMODULATOR=ON -DOPT_BUILD_KG_SSTV_DECODER=ON -DOPT_BUILD_WEATHER_SAT_DECODER=ON -DOPT_BUILD_FALCON9_DECODER=ON -DOPT_BUILD_ATV_DECODER=ON -DOPT_BUILD_M17_DECODER=ON`
2. execute `make`
3. see the errors about missing dsp headers

**Comment by AlexandreRouma** [comment]
A lot of the modules you tried to build are unfinished and therefor build should not be attempted. A lot of these (falcon9_decoder, weather_sat_decoder and kg_sstv_decoder) will also be removed and archived soon.

See https://github.com/AlexandreRouma/SDRPlusPlus#module-list for details on the state of development of various modules.

**Comment by Szewcson** [comment]
THX for the replay. In fact I was only hoping to use weather_sat_decoder (the others I tried to build out of curiosity). Sad to hear that this module will be removed.
