### ISSUE TITLE
Missing Options in Windows version?

### ISSUE THREAD

**Issue by ShockTherapist** [AlexandreRouma/SDRPlusPlus#1096]
Greetings and thanks for making SDR++ available.

New user so not sure whether these are issues or expected behavior. When selecting WFM, the RDS, Low Pass and Noise Reduction options are not available. Similarly. on USB, LSB and DSB, the Noise Blanker is not available. This was observed with both an RTL-SDR and an RSP2.

Is these issues or am I missing something?

Thanks.

**Comment by AlexandreRouma** [comment]
You're probably running an old version instead of the nightly: https://www.sdrpp.org/nightly
Don't use the noise blanker, it's a work in progress.

**Comment by ShockTherapist** [comment]
Thanks for the quick response.
