### ISSUE TITLE
SDR++ Android not starting when pressing the "play" button

### ISSUE THREAD

**Issue by RFFreebander433** [AlexandreRouma/SDRPlusPlus#1097]
Hello, I installed the SDR++ apk and it downloaded fine, I've selected the source (RTL-SDR), set my bandwidth to 2.048 and selected direct sampling, aswell set the frequency to a time signal (9.996 MHz RWM Time signal), I've set all that and pressed the play button, the spectrum does not start and there is no audio even.

OS: Android 13

The SDR is plugged in fine, even the app detects it but it doesn't start up when pressing the play button. Am I missing something here or is this a bug?

**Comment by AlexandreRouma** [comment]
Show a screenshot that includes the waterfall and source menu.

**Comment by RFFreebander433** [comment]
![TWCN-Relay-Image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/129181357/b467ea7f-ee8b-4879-8934-f3be9c5afbf9)

**Comment by AlexandreRouma** [comment]
It's not detected otherwise it would show up in the dropdown. "RTL-SDR" is the source type, not the device.
Probably forgot to press refresh which is required on android after giving device permissions.
See the manual for details https://www.sdrpp.org/manual.pdf

**Comment by RFFreebander433** [comment]
I tried refresh and it worked! Thanks for the help!

**Comment by RFFreebander433** [comment]
Also, this SDR++ android is a really a great way to bring my SDR outdoors for better reception, thank you for making this!
