### ISSUE TITLE
SDR++ Server not starting on Mac OS Ventura

### ISSUE THREAD

**Issue by Screaminbean** [AlexandreRouma/SDRPlusPlus#1100]
I'm somewhat new to this so I could just be missing something but after installing from the nightly builds, I can't seem to get the SDR server to even start from the UI. I have Volk 3.0.0 installed, maybe that's the issue? 

Any help would be greatly appreciated

**Comment by Screaminbean** [comment]
Okay after getting home from work it would appear that it just straight up isn't built in to the Mac build of SDR++, whoops. Hope it gets added sometime soon.

**Comment by AlexandreRouma** [comment]
no steps to reproduce, no error logs, no info on which sdr++ version is being used.
Not sure how I'm supposed to help here...
