### ISSUE TITLE
GUI interface faulty, flickering and overlapping controls

### ISSUE THREAD

**Issue by colinrk** [AlexandreRouma/SDRPlusPlus#1106]
Built/installed from git on Ubuntu 22.04.2 as per the instructions in README. 
Underlying radio function appears to work but the GUI controls are buggy. The top row controls (menu button, play button etc) show up as blank squares. The side panel controls look and behave ok initially but when menu sections are expanded/collapsed, everything starts overlapping and flickering and immediately becomes unusable.
I will re-test in an X11 session (vs Wayland) after posting to see if that is the issue.
The debian package can be made to install but wont function (libglew not linked correctly IIRC)
Any other ideas?

**Comment by colinrk** [comment]
The issue is reproducible on both wayland and xorg sessions. 
![Screenshot from 2023-06-27 11-51-05](https://github.com/AlexandreRouma/SDRPlusPlus/assets/4383744/7256cc95-9cf3-497b-8725-f0078addf809)

Hope there's a way to resolve this as SDRPP looks like the best app around when working.

**Comment by AlexandreRouma** [comment]
Broken graphics driver or hardware too old.
