### ISSUE TITLE
option(OPT_BUILD_WEATHER_SAT_DECODER "Build the HRPT decoder module (no dependencies required)" ON)

### ISSUE THREAD

**Issue by kmp56** [AlexandreRouma/SDRPlusPlus#1108]
![obraz](https://github.com/AlexandreRouma/SDRPlusPlus/assets/55712082/5259d6d7-0586-4450-a9ba-057acf48cc0b)

**Hardware**
- CPU: i9-12900K
- RAM: 32GB
- GPU: nVidia GeForce GTX 1650
- SDR: local, last github 1c081ca

**Software**
- Operating System: Ubuntu 22.04 LTS
- SDR++: Version 1.1.0  Build date: 29.06.2023

**Bug Description**
Compilation without problem till switching ON in:
option(OPT_BUILD_WEATHER_SAT_DECODER "Build the HRPT decoder module (no dependencies required)" ON)

**Effect:**
/home/kmp/SDRPlusPlus/decoder_modules/weather_sat_decoder/src/main.cpp:9:10: fatal error: dsp/pll.h: No such file or directory
    9 | #include <dsp/pll.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by AlexandreRouma** [comment]
Readme clearly states
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/fe35b575-b2d5-4297-a170-17132a989b66)

Additionally as stated in https://github.com/AlexandreRouma/SDRPlusPlus/issues/1093, the module is deprecated and will be removed soon.
