### ISSUE TITLE
Too large font on Android 

### ISSUE THREAD

**Issue by andimik** [AlexandreRouma/SDRPlusPlus#1119]
**Hardware**

Sony G8441 Android mobile phone 

```
Pixeldichte 	319 ppi
Auflösung 	720 x 1.280 Pixel
Diagonale Zoll 	4,6 Zoll
Diagonale mm 	116,8 mm 
```

- CPU: 
- RAM: 4 GB
- GPU: 
- SDR: (Remote or local? If remote, what protocol?)

**Software**
- Operating System Android 9

- SDR++: Version + Build date https://github.com/AlexandreRouma/SDRPlusPlus/releases/download/nightly/sdrpp.apk and https://github.com/AlexandreRouma/SDRPlusPlus/commit/9ae6a7440844a4c6f0f27c11dd4ffd0bde4f6be1

**Bug Description**
On my Android phone I can't use the app as the font is too large, see screenshot. 

**Steps To Reproduce**
1. Installation of app
2. Run it

**Screenshots**
![Screenshot_20230704-122859](https://github.com/AlexandreRouma/SDRPlusPlus/assets/24510556/749b2e57-20ae-4045-af46-b5b29afe16ae)

**Comment by AlexandreRouma** [comment]
the high-dpi scaling setting is literally visible in your screenshot, expand the width thof the menu change it to something smaller. The default scaling is meant for modern smartphone with much higher resolutions than this one.

**Comment by andimik** [comment]
Ok, I could successfully increase the column width and set it to another, lower value.

**Comment by andimik** [comment]
I did not know this was adjustable... 😁
