### ISSUE TITLE
Recording 

### ISSUE THREAD

**Issue by STU8897** [AlexandreRouma/SDRPlusPlus#1120]
**Feature description**
I have android sdr++, but can't save records, sdr++ data file is empty?

**Comment by AlexandreRouma** [comment]
You must select a path in which the application is allowed to write. likely the SD card.
I don't recommend recording on android anyway since the data rates involved will fill up most smartphones quite fast.

**Comment by STU8897** [comment]
thanks for the answer, I'd better save my record on the PC only
