### ISSUE TITLE
Missing file_source under Android 

### ISSUE THREAD

**Issue by andimik** [AlexandreRouma/SDRPlusPlus#1122]
**Hardware**
Sony G8841 Android 
- CPU: 
- RAM: 4GB
- GPU: 
- SDR

**Software**
Android 9

- SDR++: nightly built  9ae6a74

**Bug Description**
According to the https://github.com/AlexandreRouma/SDRPlusPlus/#sources file_source should be default but I can't see it in the drop down as well as the module manager 

**Screenshots**
![Screenshot_20230705-173448](https://github.com/AlexandreRouma/SDRPlusPlus/assets/24510556/9491a539-167b-4d9e-8aa4-0cb031482a27)

**Comment by AlexandreRouma** [comment]
It's disabled on purpose.
