### ISSUE TITLE
MacOS - Audio sinks missing with newest nightly build

### ISSUE THREAD

**Issue by michaelgeorge001** [AlexandreRouma/SDRPlusPlus#1133]
**Hardware**
Mac mini M1
16GB RAM
Nooelec NESDR SMArTee v2 SDR

**Software**
MacOS 12.6.7

**Bug Description**
Audio sinks missing with newest nightly build

Audio sinks display and operate properly with the Jul 9, 2023 nightly build and earlier.
Audio sinks are missing on the Jul 10, 2023 nightly build.

**Steps To Reproduce**
Using the same config file, and toggling back and forth between both nightly builds produces the following results.

Jul 9 version - Audio sinks display and audio is heard.
July 10 version - Audio sinks do not display, and obviously no audio is heard.

**Screenshots**

Here are the relevant screen shots:
![Screen Shot 2023-07-11 at 6 02 09 PM](https://github.com/AlexandreRouma/SDRPlusPlus/assets/2292023/ff373bf6-66b5-4304-b0df-d551dca89b15)

![Screen Shot 2023-07-11 at 6 01 54 PM](https://github.com/AlexandreRouma/SDRPlusPlus/assets/2292023/e6b3e58a-7153-4d2b-b8e4-db53471c6aa0)

Unless I'm missing a new config setting, this doesn't seem to be correct behaviour.

-Mike-

**Comment by michaelgeorge001** [comment]
In addition the new Streams module is also inoperable in the newest version as well.
![Screen Shot 2023-07-11 at 6 16 23 PM](https://github.com/AlexandreRouma/SDRPlusPlus/assets/2292023/97e4aa69-dbb7-4326-9620-277ca337a052)

-Mike-

**Comment by AlexandreRouma** [comment]
you downloaded some random CI build from the `new_sinks` branch, **NOT** a nightly.

Nightly builds are available at https://www.sdrpp.org/nightly

**Comment by michaelgeorge001** [comment]
Thank you, my mistake.

However, it wasn't just some random CI build, it was the newest.

Regardless, it was my error in not confirming that a nightly build was created from it or that it was from the master branch.

I will pull from the nightly build link from this point forward, or compile it myself.

Thanks again.

-Mike-
