### ISSUE TITLE
SDR++ hangs and then crashes upon start and trying to initialize SoapySDR Source-Linux Mint 21.1

### ISSUE THREAD

**Issue by Tchawk71** [AlexandreRouma/SDRPlusPlus#1137]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: Athlon II 645
- RAM: 16
- GPU: Radeon
- SDR: RTL-SDR Blog V3

**Software**
- Linux Mint 21.1
- SDR++ V1.1.0 (Built at 23:17:07, Jul 10 2023) This is the Jammy_deb from Nightly

**Bug Description**
Upon start of SDR++, it begins loading fine and fast, but once it gets to the part where it is "Initializing SoupySDR Source (soapy_source), I get a popup window saying that "SDR++ V1.1.0 (Built at 23:17:07, Jul 10 2023) is not responding" and then the program completely closes out no matter if I select Force Quit or Wait. 

**Steps To Reproduce**
1. ...select SDR++ program icon 
2. ...
3. ...

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
![SDRPP Soapy Error](https://github.com/AlexandreRouma/SDRPlusPlus/assets/139568892/dfaa733b-90a7-40c5-ab84-1827b8fc76a0)

I have had this running previously on Linux Mint 20.3 with no issues. I am also a new Linux user, so am comfortable installing with a .deb file, but not so much yet via any other method.ie..tar.gz or terminal. The NIghtly area is the only deb file I could locate for Jammy.

**Comment by AlexandreRouma** [comment]
You didn't give logs as asked for by the template but almost certainly: https://github.com/AlexandreRouma/SDRPlusPlus#hash-collision-error-when-starting
