### ISSUE TITLE
APRS Decoding

### ISSUE THREAD

**Issue by EricFROL** [AlexandreRouma/SDRPlusPlus#1138]
**Feature description**
Would be nice to have an integrated APRS decoder

**Comment by gprime31** [comment]
the only plugin i am aware of is:
https://github.com/dbdexter-dev/sdrpp_radiosonde
not sure if there are any plans for more.

**Comment by AlexandreRouma** [comment]
Still planner, would have closed it if not

**Comment by EricFROL** [comment]
Oh ok sorry, i was just closing my old opened issues.
Keep it up!
