### ISSUE TITLE
SDR error message

### ISSUE THREAD

**Issue by Nirbles** [AlexandreRouma/SDRPlusPlus#1140]
Hello, I have noticed the following error message showing up periodically:
"Cannot process TDMA channel grant - unrecognized timeslot count: 4"
I am using 2 dongles on the Manatee County FL trunk system. sdr-trunk is running on Windows 11.
Thank you for any ideas on this.

**Comment by AlexandreRouma** [comment]
This is not a support services for SDtrunk, talk to them instead.
