### ISSUE TITLE
Doesn't work on macos

### ISSUE THREAD

**Issue by utdrmac** [AlexandreRouma/SDRPlusPlus#1150]
**Hardware**
- CPU: 2.3 GHz 8-Core Intel Core i9
- RAM: 16GB
- GPU: N/A
- SDR: Local/USB NESDR Nano 2 Plus (RTL2832U & R820T2)

**Software**
- Operating System: MacOS 13.4.1 Ventura
- SDR++: SDR++ v1.0.4

**Steps To Reproduce**
1. Download latest macos package and install.
2. Attempt to run on CLI

```
$ sdrpp --help
dyld[56647]: Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.2.dylib
  Referenced from: <72CC01C6-4A69-39E0-BC4F-EB717CFA38CB> /usr/local/bin/sdrpp
  Reason: tried: '/usr/local/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/usr/local/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/usr/local/lib/libGLEW.2.2.dylib' (no such file), '/usr/lib/libGLEW.2.2.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Comment by AlexandreRouma** [comment]
Version 1.0.4 is deprecated for MacOS. Use the nightly instead: https://www.sdrpp.org/nightly
