### ISSUE TITLE
SDRPlusPlus silently exits when run on a Windows host without 3D acceleration / OpenGL support available

### ISSUE THREAD

**Issue by AsciiWolf** [AlexandreRouma/SDRPlusPlus#1151]
When running on a system without 3D acceleration and/or OpenGL support, SDRPlusPlus silently exits without any error message. Consider adding an exception for this that returns an error code that can be displayed to the user before the application exits.

I am not including any hardware details, because this issue is not hardware specific - it happens on every machine without 3D acceleration / OpenGL available (for example most virtual machines).

**Comment by AlexandreRouma** [comment]
On windows GUI apps do not have a terminal. As stated in the manual, if you want one, start with `-c`.

**Comment by AsciiWolf** [comment]
What? I did mean a GUI error message shown to the user if no OpenGL support is available, not printing the error on stdout (which is useless for most Windows users).
