### ISSUE TITLE
Build breaks with rtaudio-6.0.0

### ISSUE THREAD

**Issue by yurivict** [AlexandreRouma/SDRPlusPlus#1153]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: 
- RAM:
- GPU: 
- SDR: (Remote or local? If remote, what protocol?)

**Software**
- Operating System: FreeBSD 13.2
- SDR++: 1.0.4

**Bug Description**
Build breaks:
```
/wrkdirs/usr/ports/comms/sdr++/work/SDRPlusPlus-1.0.4/sink_modules/audio_sink/src/main.cpp:49:23: error: no member named 'probed' in 'RtAudio::DeviceInfo'
            if (!info.probed) { continue; }
                 ~~~~ ^
/wrkdirs/usr/ports/comms/sdr++/work/SDRPlusPlus-1.0.4/sink_modules/audio_sink/src/main.cpp:176:17: error: unknown type name 'RtAudioError'; did you mean 'RtAudioErrorType'?
        catch ( RtAudioError& e ) {
                ^~~~~~~~~~~~
                RtAudioErrorType
/usr/local/include/rtaudio/RtAudio.h:228:6: note: 'RtAudioErrorType' declared here
enum RtAudioErrorType {
     ^
2 warnings and 2 errors generated.
```

rtaudio-6.0.0
clang-14
FreeBSD 13.2

**Comment by starvald** [comment]
https://github.com/AlexandreRouma/SDRPlusPlus/issues/1149
 rtaudio 6.0.0 not supported.
