### ISSUE TITLE
Baseband (IQ) input from USB device

### ISSUE THREAD

**Issue by laurenweinstein1** [AlexandreRouma/SDRPlusPlus#1158]
Any plans for this as on the Win version? Thanks!

**Comment by AlexandreRouma** [comment]
**what** device?

**Comment by laurenweinstein1** [comment]
Malahit, for example. Thanks.

**Comment by AlexandreRouma** [comment]
afaik it's just a soundcard. Use the audio source.

**Comment by laurenweinstein1** [comment]
Just for the record, it will output baseband via its USB-C jack. I've made it work under a Win app.
