### ISSUE TITLE
IQ recording of complete or selected frequency band

### ISSUE THREAD

**Issue by alphapats** [AlexandreRouma/SDRPlusPlus#1159]
**Feature description**
Presently their is option is record baseband or audio of selected signal after demodulation. There is no option to record raw IQ signal of complete Instantaneous bandwidth of SDR (like 2MHz band IQ recording in RTL SDR) or selected frequency band. This feature will help users to carry out raw IQ signal analysis in other third party softwares or in MATLAB/Gnuradio.

**Comment by AlexandreRouma** [comment]
I'll let you guess what "baseband" recording is. In the mean time I recommend reading through the manual: https://www.sdrpp.org/manual.pdf
