### ISSUE TITLE
Please add indication of input IQ stream peak level in dBFS units

### ISSUE THREAD

**Issue by qrp73** [AlexandreRouma/SDRPlusPlus#1175]
There is missing very important indication for SDR receiver - peak level of input IQ stream in dBFS units. Without this indication the user is blind and cannot tune RF frontend and hardware DSP settings to use max possible dynamic range with max receiver sensitivity.

We're talked about it in issue about unity gain and you said
>> There is no point displaying this. Almost all SDRs do some kind of processing to the IQ that will change the raw level compared to the real ADC values meaning the value you'll measure will be basically useless.

But this is incorrect. This is the most important indication for SDR receiver. 

dBFS units are relative units it shows value relative to sample dynamic range (sample bits). **It doesn't depends on absolute analog signal level, or raw level changes on analog or digital frontend.** It actually shows how much dynamic range of input IQ stream resolution is utilized by IF signal. In other words it shows how much dynamic range of your receiver is actually in use.

It is very important indication, especially when you're hunting for a weak signals. It allows to quickly perform sanity test that there is no signal distortions due to clipping. It allows to quickly detect issues with RF frontend tuning or settings or mistakes in DSP processing.

Please don't confuse this measurement with signal SNR in dB or dBFS units. SNR level shows measurement for signal within user-selected bandwidth. RF level shows measurement for entire IQ stream. dBFS unit for RF level allows to easily see how much bits of your IQ sample resolution is actually in use and how much bits is available for increase analog signal gain. 

When RF reach 0 dBFS you're know that input IQ stream dynamic range limit is reached, so you're needs to reduce analog RF gain. 

When RF is much below 0 dBFS it means that you're don't use all available dynamic range, so you're needs to increase analog RF gain or FPGA DSP gain to use all bits of IQ sample resolution. 

In such way this indication allows to tune analog RF frontend precisely and quickly in such way to achieve the max receiver performance and listen very weak signals on your SDR receiver with no distortions. 

Without this indication you're completely blind and cannot precisely tune RF gain in order to achieve the best receiver sensitivity and utilize full dynamic range of your ADC. Without this indication you cannot estimate if all analog and DSP chain is well tuned to get max sensitivity and utilize full dynamic range of your ADC.

See example of RF dBFS measurement on HDSDR screenshot, it shows hardcoded sine with max possible amplitude. Actually this sine has 0 dBFS for ADC output, but my DSP chain on FPGA has 7 dB margin to avoid clipping for specific cases, this is why IQ stream with this sine has RF level = -7 dBFS:

![RF-dBFS](https://github.com/AlexandreRouma/SDRPlusPlus/assets/46676744/eca52421-3b1f-4258-b504-3633eb93ef70)

You can find the same measurement in any serious SDR software, because this is very important indication. Please add it.

**Comment by AlexandreRouma** [comment]
I've already said no.
