### ISSUE TITLE
Compiling on Raspberry Pi

### ISSUE THREAD

**Issue by sakittelsen** [AlexandreRouma/SDRPlusPlus#1181]
I just compiled the program on a Raspberry Pi 400 running the current Raspberry Pi OS 64 bit (based on Debian 11) under the Gnome desktop, and noticed two issues:

1- The library libvolk1-dev is not available, so using libvolk2-dev instead, which worked.

2- I extracted the git files in a new folder in my download folder and tried to run the rpi_install.sh from there. That failed, it expected the files to be in the root of my home folder. Can this be updated in the script so it can run from any location I choose?

**Comment by H6LS1S** [comment]
> I just compiled the program on a Raspberry Pi 400 running the current Raspberry Pi OS 64 bit (based on Debian 11) under the Gnome desktop, and noticed two issues:
> 
> 1- The library libvolk1-dev is not available, so using libvolk2-dev instead, which worked.
> 
> 2- I extracted the git files in a new folder in my download folder and tried to run the rpi_install.sh from there. That failed, it expected the files to be in the root of my home folder. Can this be updated in the script so it can run from any location I choose?

https://github.com/AlexandreRouma/SDRPlusPlus/issues/942#issuecomment-1685595050

**Comment by AlexandreRouma** [comment]
That script was specifically for old raspberry pi OS.

Just follow the normal linux instructions. There is no difference in instructions.

I'll delete that script since it confuses people.
