### ISSUE TITLE
Adroid fails to record audio fil

### ISSUE THREAD

**Issue by longtreeroad** [AlexandreRouma/SDRPlusPlus#1186]
Firstly I absolutely love this software,

My issue is with recording or saving audio files, the app has all permissions enabled yet I fail to get any audio file saved.

The app counts the audio recording time but when I stop recording and close the app I see no files in the recordings folder?

I have tried to change the file path but this fails to help.

I'm trying to save NOAA audio files for processing in a separate piece of software I'm working on.

Any advice or help would be great.

Android 13
Galaxy tab s7 fe 5g

**Comment by AlexandreRouma** [comment]
It's not that it's not recording it's just that modern android systems don't allow you to access app folders.
As the previous commenter said, change the path to somewhere else.

In any case I don't recommend recording on android. The files get huge quickly and recording that much data on an SD card or embedded flash can damage it in the long term.
