### ISSUE TITLE
sdrplay_api: ERROR: Requested maxDevs (128) too large for shared memory, requesting 16

### ISSUE THREAD

**Issue by marrem** [AlexandreRouma/SDRPlusPlus#1195]
When starting sdr++ as server I get this error message:

```
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69042]: sdrplay_api: sdrplay_api_GetDevices: ERROR: Requested maxDevs (128) too large for shared memory, requesting 16
```

I am running: SDR++ v1.1.0
On Ubuntu 22.04.3 LTS
Linux sdrserver 5.15.0-1036-raspi #39-Ubuntu SMP PREEMPT Mon Aug 21 11:46:10 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
On a Raspberry Pi 4 with 8MB RAM

In context:

```
Sep 23 20:12:55 sdrserver systemd[1]: Started SDR++ Server.
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69042]: sdrplay_api_Open
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69042]: sdrplay_api: sdrplay_api_GetDevices: ERROR: Requested maxDevs (128) too large for shared memory, requesting 16
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69055]: sdrplay_api_device: strmHandlerThread: Entry
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69056]: sdrplay_api_device: eventHandlerThread: Entry
Sep 23 20:12:55 sdrserver sdrpp[69042]: [69057]: sdrplay_api_device: heartBeatThread: Entry
Sep 23 20:12:56 sdrserver sdrpp[69042]: [69056]: sdrplay_api_device: eventHandlerThread: Exit
Sep 23 20:12:56 sdrserver sdrpp[69042]: [69055]: sdrplay_api_device: strmHandlerThread: Exit
Sep 23 20:12:56 sdrserver sdrpp[69042]: [69057]: sdrplay_api_device: heartBeatThread: Exit
```

It does function, however. I can connect from another sdr++ running on my laptop.
But I wonder, is it a problem it requests so many devices? Even the 16 devices consume more memory than would be needed. I have only one SDRplay device connected. And at the moment I only connect to the SDR++ server from one client at a time. Would it be an idea to make the number of requested devices configurable. Maybe decrease the default.

**Comment by AlexandreRouma** [comment]
You can safely ignore it.
