### ISSUE TITLE
Open font error

### ISSUE THREAD

**Issue by BG7JAF** [AlexandreRouma/SDRPlusPlus#12]
Hi, I have build this program success. but when I try to run it, it just crash and throw some error message:

lynx@darkstar ~/G/S/build (master)> ./sdrpp
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
Detached kernel driver
Found Rafael Micro R820T tuner
Reattached kernel driver
[2020-08-15 22:36:49.127] [info] SDR++ v0.2.5_alpha
sdrpp: /home/lynx/Git/SDRPlusPlus/src/imgui/imgui_draw.cpp:1823: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
fish: “./sdrpp” terminated by signal SIGABRT (Abort)

I want to know which font should I install. I am running Ubuntu 20.04. thx

**Comment by AlexandreRouma** [comment]
Hi,
You need to copy `res`, `bandplans` and `band_colors.json` to the build/run directory.
this will be fixed in the new alpha, there was a lot of cleanup done in the file paths.
