### ISSUE TITLE
Sound is stuttering when  SDR++ is used with soapy server / soapy client 

### ISSUE THREAD

**Issue by oldchap7** [AlexandreRouma/SDRPlusPlus#1207]
Sound is stuttering when used in in a server-client (sdr++) configuration. It seems to be obvious that the suttering effect is caused by sdr++ since even noise, when no signal is tuned in, is stuttering. The graph in the SA presentation is continuous.
The rig:
Server:  Raspi zero 2 / bullseye 32 bit / cariboulite hat with its dedicated SW
Client: Raspi 4 /2GB /bullseye 32 bit / SDR++
LAN connected (not WLAN!)
When setting up the rig I tested SDR++ using a RTLSDR at the client, which worked ok.
Using cariboulite via soapy server it receives (local broadcast stn), but as said above, AF is stuttering.
Saw the hints re sound in the SDR++ User Guide, but not sure wether it is still actual as the fix is dated 05.2021.

Any ideas around how to cure? (thanks in advance)

**Comment by AlexandreRouma** [comment]
> It seems to be obvious that the suttering effect is caused by sdr++ since even noise

And the fact you're running a UDP based protocol over wifi on an under-powered device would have nothing to do with it?

I'm not sure why you're using soapyremote when SDR++ has its own more efficient and better in every way remote protocol called "SDR++ server", see the manual for details: https://www.sdrpp.org/manual.pdf. And even then, I'm not sure the pi zero has the horsepower to run a cariboulite.

**Comment by oldchap7** [comment]
﻿﻿To get things clear:I am not using WiFi ! ( That had been declared in the thread)Cariboulabs published a video on youtube where they demonstrate cariboulite working on Raspberry zero. From that point of view, raspi zero 2 should be able to run cariboulite or the value of the demonstration must be doubted.However, if there will be no sollution to the problem reported, will try using sdr++ server.Vom mobilen Endgerät gesendetAm 12.10.2023 um 22:41 schrieb AlexandreRouma ***@***.***>:﻿

It seems to be obvious that the suttering effect is caused by sdr++ since even noise

And the fact you're running a UDP based protocol over wifi on an under-powered device would have nothing to do with it?
I'm not sure why you're using soapyremote when SDR++ has its own more efficient and better in every way remote protocol called "SDR++ server", see the manual for details: https://www.sdrpp.org/manual.pdf. And even then, I'm not sure the pi zero has the horsepower to run a cariboulite.

**Comment by AlexandreRouma** [comment]
> Server: Raspi zero 2

> I am not using WiFi !

?

**Comment by oldchap7** [comment]
Changed the strategy, now using a rpi4/2GB+bullseye 32 bit to test a Soapy SDR. 
Downloaded the actual nightly build, installation went smoothly. When starting sdr++ than it does not list RTL SDR in the source list (nor other SDRs.) Same in the Module Manager.
Checked usr/lib/sdrpp/plugins -> all modules are listed there.
How are the modules to be added to the Module Manager or activated otherwise.
Thanks for support.

**Comment by oldchap7** [comment]
Lost interest.
