### ISSUE TITLE
[Debian 12 / MX Linux 23] [Xfce] File selection dialog does not appear

### ISSUE THREAD

**Issue by LZ2DMV** [AlexandreRouma/SDRPlusPlus#1208]
Hello,

The file selection dialog when using "File" as a source is not showing at all on a fully updated MX Linux 23 (Xfce), based on Debian 12 Bookworm - clicking on the three dots does nothing. Nothing unusual goes to stdin or stderr either.

I'm using the latest deb package from the nightly releases page. It is installed with all dependencies satisfied beforehand.

SDR++ version: The current one on the nightly release channel at the moment of opening the bug report (sorry, didn't noted the build number in the title bar when i was testing)
Kernel version: 6.1.55-1
Xfce version: 4.18

Steps to reproduce:
1. Load the program, either from the GUI shell or via a terminal if you want to monitor stdin and stderr.
2. Change the input source to "File".
3. Click the three dots at the end of the input field where the file path goes.
4. By design, a file selection dialog should appear, but nothing happens.

**Comment by AlexandreRouma** [comment]
KDialog must be installed.
