### ISSUE TITLE
Wrong chunks size in RIFF header

### ISSUE THREAD

**Issue by volo-zyko** [AlexandreRouma/SDRPlusPlus#1212]
Currently, only the size of the chunks' data is added to the size written in RIFF header (size following `RIFF` id). However, chunk also includes its `id` and `size` which are represented by `ChunkHeader` in code. Since, normally, SDR++ writes 2 chunks (`fmt` and `data`) then the size in RIFF header is less than it should have been by 16 bytes. The line below should also include `+ sizeof(ChunkHeader)`.
 
https://github.com/AlexandreRouma/SDRPlusPlus/blob/78daed7879d3ff785bc5c4f70dbc7fc6b961bd94/core/src/utils/riff.cpp#L96

As a side note. Comment in the line below (despite `fileSize` is never used) has the right size.

https://github.com/AlexandreRouma/SDRPlusPlus/blob/78daed7879d3ff785bc5c4f70dbc7fc6b961bd94/source_modules/file_source/src/wavreader.h#L64

**Comment by AlexandreRouma** [comment]
haven't had time to check yet just putting the label in case
