### ISSUE TITLE
Set Frequency at startup

### ISSUE THREAD

**Issue by GreeyChip** [AlexandreRouma/SDRPlusPlus#1218]
**Feature description**
Set Frequency at startup
Example: `/usr/bin/sdrpp --autostart --Frequency 485339660`
it would be nice for the program to be able to startup on a specific Frequency

**Comment by AlexandreRouma** [comment]
There is no need, the last set frequency is retained between runs.
Moreover, there can be any number of VFO, so specifying a single frequency makes no sense.
