### ISSUE TITLE
Raspberry Pi OS 64-bit bookworm support

### ISSUE THREAD

**Issue by skyper-cz** [AlexandreRouma/SDRPlusPlus#1222]
Hi
Im using the Raspberry Pi OS 64-bit bookworm and wanted to install sdr++ as per instructions at this page:
https://www.sdrpp.org/manual.pdf

However even though it showed in the "others" folder it did not run, it might be caused by this.
<img width="644" alt="Screenshot 2023-11-03 at 13 48 38" src="https://github.com/AlexandreRouma/SDRPlusPlus/assets/62872636/30d7dc12-932c-417b-b751-36943c8b34e2">

Any idea of a solution?

**Comment by AlexandreRouma** [comment]
1) The error has nothing to do with the package itself, it's a permission error from APT, can't help with that
2) the package is for the 32bit bullseye image, it will not work with your OS. Build the app from source instead.
