### ISSUE TITLE
DDE Module?

### ISSUE THREAD

**Issue by ArthurZhou** [AlexandreRouma/SDRPlusPlus#1223]
**Feature description**
Need a module to connect with applications like Orbitron, Look4Sat. thks :)

**Comment by AlexandreRouma** [comment]
Orbitron is horribly outdated and I do not want to support it.

Look4Sat is an android app that doesn't support controlling a radio, only a rotor through rotctl...

Use GPredict with the rigctl_server module.

**Comment by ArthurZhou** [comment]
thanks, bro :)
