### ISSUE TITLE
no way to add airspy server ui is not working

### ISSUE THREAD

**Issue by ta3pks** [AlexandreRouma/SDRPlusPlus#1224]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: apple m1
- RAM: 8gb
- GPU: N/A
- SDR: airspy remote

**Software**
- Operating System: macos 14.1
- SDR++: 1.1.0 02:25:47 oct 29 2023
**Bug Description**
From the manual what i understand is that source section should contain 2 inputs to enter host and port after selecting Airspy.
However in my case theres just two empty dropdowns in which i cannot input anything effectively rendering the entire app unusable.

**Steps To Reproduce**
1. go to applications folder and click on sdr++.app
2. select Airspy in the source menu
3. no way to enter the server details

**Screenshots**
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/9097437/11308694-5348-42f2-9205-a4de7a5fb8b0)
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/9097437/e56019e5-515f-4b5a-8f6f-e880d0a44ded)
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/9097437/fb4ae9e5-c532-4caa-9c06-a5d35c60074a)

**Comment by AlexandreRouma** [comment]
"SpyServer" and "Airspy" are two different things, shocking I know...
What you want is "SpyServer", Airspy is the device.

**Comment by ta3pks** [comment]
oh i see thanks
