### ISSUE TITLE
compile fix & missing package

### ISSUE THREAD

**Issue by folkertvanheusden** [AlexandreRouma/SDRPlusPlus#1225]
core/src/utils/networking.cpp requires #include <stdexcept>
and the readme fails to mention that for ubuntu one needs to install librtlsdr-dev

**Comment by AlexandreRouma** [comment]
1) You're wrong, the CI checks every commit and it builds correctly on all supported operating systems, including ubuntu.
2) No shit sherlock, you need to install the driver for your SDR???? Who could have thought?????? And yes, it is absolutely mentioned in the readme:
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/4dd8853b-c4dd-4b74-9120-454df4e77dc7)

**Comment by folkertvanheusden** [comment]
I'm talking about Ubuntu 23.10 here (may not be officially supported yet, but then it is a fix for the future). And it was not mentioned in the part where it tells you how to prepare your debian/ubuntu system (the apt-get part).

**Comment by AlexandreRouma** [comment]
> I'm talking about Ubuntu 23.10 here (may not be officially supported yet, but then it is a fix for the future).

No, it's known to work, there's just not a CI build for it yet. What you said here "core/src/utils/networking.cpp requires #include <stdexcept>" is just plain wrong, literally line 4 of the file:
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/0e709fd4-5aed-41c8-9866-e8c518145ef1)

I don't know how old of a commit you're using but it must be at least a year old...

**Comment by folkertvanheusden** [comment]
> > I'm talking about Ubuntu 23.10 here (may not be officially supported yet, but then it is a fix for the future).
> 
> No, it's known to work, there's just not a CI build for it yet. What you said here "core/src/utils/networking.cpp requires #include <stdexcept>" is just plain wrong, literally line 4 of the file:
> ![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/0e709fd4-5aed-41c8-9866-e8c518145ef1)
> 
> I don't know how old of a commit you're using but it must be at least a year old...

Ah I was using the 1.0.4 release.

Indeed the latest version on github compiles & runs fine.
