### ISSUE TITLE
SDR++Server Multi Client Connection&Client Name (or IP)

### ISSUE THREAD

**Issue by vgegok** [AlexandreRouma/SDRPlusPlus#1228]
I plan to remotely place Raspberry Pi and multiple SDR devices for remote control indoors, possibly with multiple client controls, so I need multi client support from SDR++Server. And in the server log, it can be seen which client connected which device.

**Comment by AlexandreRouma** [comment]
Multi-client support is not possible at all with how SDR++ server is designed. If you need to use multiple receivers at the same time, start multiple server instances with their own config directories on their own port.
