### ISSUE TITLE
Constant audio buffer underruns with JACK

### ISSUE THREAD

**Issue by illegalcoding** [AlexandreRouma/SDRPlusPlus#1229]
**Hardware**
- CPU: Intel Core i5-4590
- RAM: 10GB DDR3 1333MHz
- GPU: AMD Radeon RX 6600
- SDR: RTLSDR

**Software**
- Operating System: Arch Linux, Kernel 6.5.2.8.realtime1-1-rt
- SDR++: Built from source, latest version

**Bug Description**
Starting up SDR++ results in JACK getting spammed with Xruns, once the SDR is started, the Xruns stop, but once the SDR is stopped again, they continue, and a nasty repeating sound plays

**Steps To Reproduce**
1. Build RtAudio with JACK support
2. Launch SDR++
3. Play and Stop the SDR

**Screenshots**
![2023-11-13T19:44:37,200529832+01:00](https://github.com/AlexandreRouma/SDRPlusPlus/assets/89472272/caafed26-22ba-4a6e-9aa5-7d0a5764fd6e)
![2023-11-13T19:44:58,474401185+01:00](https://github.com/AlexandreRouma/SDRPlusPlus/assets/89472272/0382627d-6fe0-4393-96db-f03cacbf1f88)
(An Xrun is a term for a buffer over- or underrun.)

**Additional info**
I've spent some time investigating this issue, digging into SDR++ and RtAudio source code and it seems the issue stems from SDR++'s (mis)use of audio sinks. AFAICT the way SDR++ works is that on startup it creates an audio sink, which it doesn't send any data to, which causes buffer underruns, as the callback hangs. Once the SDR is started, data starts flowing as normal, but once it's stopped again, JACK's process callback calls RtAudio's callbackEvent(), which calls the callback in SDR++'s audio sink, as usual. However, when this callback calls stereoPacker.out.read(), it hangs on rdyCV.wait() (core/src/dsp/stream.h:72), as data is not available, since the source is stopped in setPlayState(), which causes buffer underruns.

The way JACK handles buffer underruns is by outputting whatever was last in the buffer. This is the cause of that nasty repeating glitch sound. The reason this doesn't happen on PulseAudio is because RtAudio uses pa_simple_write in it's own callback function, and if that callback doesn't ever get to that point then pulse just receives no data and stays silent. The JACK implementation, however, uses JACK's native set_process_callback() (which is set to jackCallbackHandler, which calls callbackEvent, which calls the SDR++ callback to retrieve data) which needs to receive data on every callback, otherwise it causes an underrun.

This is not a bug in RtAudio, it is how JACK works, and how JACK is used in RtAudio.

This bug is not reproducible with pipewire-jack AFAICT, as pipewire-jack is not native JACK, and just stands in place of JACK, using PipeWire in the background. It is, however, reproducible with pulseaudio-module-jack, and PipeWire's jackdbus module, as these run PulseAudio/PipeWire as a native JACK client.

IMO, the best solution would be to move stream.start() out of decoder_modules/radio/src/radio_module.h, and start and stop the stream as needed in core/src/gui/main_window.cpp's setPlayState() (or wherever else it is needed). The sink should not be running if it's source isn't.

**Comment by AlexandreRouma** [comment]
> SDR++'s (mis)use of audio sinks. [...] doesn't send any data to, which causes buffer underruns, as the callback hangs.

On every audio API of every OS ever except for JACK, this is not an issue. Why? Because adding silence when no data is available (which it's not, the SDR is stopped, there is no data flowing) is the responsibility of the audio server. I'm not going to waste time, CPU power and make the code more complicated just to get around some goofy behavior of by far the worst audio API to ever be released (there's a reason barely anything uses it).

Unfortunately, RtAudio defaults to using it for some inexplicable reason. You can fix this following these instructions: https://github.com/AlexandreRouma/SDRPlusPlus/discussions/112
