### ISSUE TITLE
SDR++ crashes on android tablet when resizing sidebar

### ISSUE THREAD

**Issue by Cpt-Dingus** [AlexandreRouma/SDRPlusPlus#1232]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: Snapdragon 865+
- RAM: 6 GB
- GPU: Adreno 650
- SDR: Local; Nooelec Smart SDR v5

**Software**
- Operating System: Android 13 running OneUI 5.1.1.
- SDR++:  v1.1.0 Built at 01:56:32, Oct 29 2023  
( Latest nightly build from [the following commit](https://github.com/AlexandreRouma/SDRPlusPlus/commit/9ae6a7440844a4c6f0f27c11dd4ffd0bde4f6be1) )

**Bug Description**
Resizing the sidebar when the radio is enabled seems to crash almost every single time on my Samsung Galaxy Tab S7 (SM-T870)
Every fifth or so attempt the app just freezes for about 10 seconds, finally unfreezes and resizes the sidebar.

**Steps To Reproduce**
1. Start radio
2. Rescale sidebar by moving its edge
3. App crashes

**Screenshots**
A video of the issue, recorded using my phone since the inbuilt screen recorder crashes along with the app: 
https://github.com/AlexandreRouma/SDRPlusPlus/assets/100243410/d93cd07b-fc98-4ca1-bf36-b439a0374412

Used my S-pen since I wanted to quickly catch the sidebars edge, it has better precision. The bug is still present when using standard touch input.

**Additional info**
Tried across two different versions, tried reinstalling the app. Nothing's helped. Issue does not happen on my phone (Samsung Galaxy S20 Ultra, SM-G988B/DS)

**Comment by AlexandreRouma** [comment]
same core issue as #1230, follow that one instead.
