### ISSUE TITLE
Support for SDRPlay API v3.12.1 on macOS

### ISSUE THREAD

**Issue by segarza** [AlexandreRouma/SDRPlusPlus#1246]
Nightly macOS build (intel) of sdrpp (v.1.1.0) references v3.07 of the SDRPlay api (expects libsdrplay_api.so.3.07 in /usr/local/lib). The latest macOS SDRPlay API is 3.12.1 (universal). The SDRPlay API Installer now creates a a series of symbolic links, including /usr/local/lib/libsdrplay_api.so.3 which seems would be the preferred link/reference.

**Comment by AlexandreRouma** [comment]
Done a week or so ago, forgot to close
