### ISSUE TITLE
gain and amplification is pushed to max when changing settings

### ISSUE THREAD

**Issue by grigore2024** [AlexandreRouma/SDRPlusPlus#1249]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
portapack h2
- CPU: 
- RAM:
- GPU: 
- SDR: (Remote or local? If remote, what protocol?)

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).

**Bug Description**
A clear description of the bug.

**Steps To Reproduce**
1. go to transmit
2. selet pocsnag tx ,  ! is not the only one with the problem !
3. sleect gain and amp
4. test, then change message or settings  , iti will set gain and amp to max

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.
![SCR_0011](https://github.com/AlexandreRouma/SDRPlusPlus/assets/65670534/1ab8b6ab-88bf-4cfc-847e-60cb69f8032d)
![SCR_0012](https://github.com/AlexandreRouma/SDRPlusPlus/assets/65670534/167634f6-b20f-49e2-bdb0-414b3ac8d958)

**Comment by AlexandreRouma** [comment]
Wtf is this? it doesn't even involve SDR++...
This is not a general SDR help site.
