### ISSUE TITLE
How to enable plugins for meteor demodulation

### ISSUE THREAD

**Issue by JoshuaKimsey** [AlexandreRouma/SDRPlusPlus#125]
I saw someone else had enabled the plug to experiment with Meteor demodulation. I was curious how to go about doing this? I tried rebuilding my fork of it from the new est files but with no success. Is this something I have to enable by hand in the code for now?

**Comment by KentuckyFriedData** [comment]
Enable it by adding the module(s) in config.json under both "moduleInstances" and "modules" as shown here
![Screenshot_2021-04-29_23-18-01](https://user-images.githubusercontent.com/31137660/116656686-f26b0380-a941-11eb-8289-95816e872ce4.png)

**Comment by JoshuaKimsey** [comment]
Thank you!!!

**Comment by AlexandreRouma** [comment]
Note that adding it to the "module" parameter is only required when not installed (aka deving).
