### ISSUE TITLE
How do I change the recording output in SDR++ Android and why is screen recording with internal audio not possible in the Android version?

### ISSUE THREAD

**Issue by tteletubby** [AlexandreRouma/SDRPlusPlus#1258]
I've recorded a NOAA WX Signal using the SDR++ Audio recorder just for it to say its on %ROOT%/Recordings which I can't find on my phone at all.

Then i've thought of just screen recording it and decoding it afterwards from the recording and seeing that audio isn't being recorded at all. What can I do?

**Comment by tteletubby** [comment]
since it took me almost 2 days of searching...
answer is

**/storage/emulated/0/Downloads**

**Comment by zhaosge** [comment]
Differently, I find the "recordings" folder in /data/user/0.org.sdrpp.sdrpp/files/recordings...

**Comment by Jasonzyt** [comment]
> Differently, I find the "recordings" folder in /data/user/0.org.sdrpp.sdrpp/files/recordings...

So I need to root my phone to access this directory...?
