### ISSUE TITLE
Failed to Execute Child Process 

### ISSUE THREAD

**Issue by Tomrm96** [AlexandreRouma/SDRPlusPlus#1264]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**

Raspberry Pi 5
RTLSDR v4

**Software**

RaspberryPi OS 64 bit 
Nightly build on the release page: 
**Bug Description**
Unable to open, downloaded the latest from the releases page and I get the following error:

<img width="580" alt="image" src="https://github.com/AlexandreRouma/SDRPlusPlus/assets/100447956/64c69e5a-3b3b-4cba-b3f6-43394aec4c9a">

**Steps To Reproduce**

Download, extract, install. Try to run.

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.

**Comment by AlexandreRouma** [comment]
1) Filename:
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/bbe0380c-0c64-431f-b5de-121df46be82a)
2) Manual: 
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/80840caf-8aa4-49f8-b3e3-09777afd6dab)
3) Previous issues:
https://github.com/AlexandreRouma/SDRPlusPlus/issues/1187

Please think and do a bit of research before opening an issue.

**Comment by Tomrm96** [comment]
Wow, your rude. Don't 64 bit OS's support 32 bit apps?

**Comment by Conterganer** [comment]
And where can I find the version for the Pi5?
