### ISSUE TITLE
downloaded this and went to open and it wont open what am i doing wrong

### ISSUE THREAD

**Issue by ojibs11** [AlexandreRouma/SDRPlusPlus#1269]
<img width="1076" alt="Screen Shot 2024-01-06 at 9 06 02 PM" src="https://github.com/AlexandreRouma/SDRPlusPlus/assets/121355658/fc7a970a-f541-48a6-abd7-5daf1589d78f">

**Comment by AlexandreRouma** [comment]
[manual](https://www.sdrpp.org/manual.pdf) page 10.

Please do a minimum of research before opening issues.
