### ISSUE TITLE
Android app and MSI.SDR dongle

### ISSUE THREAD

**Issue by DMS03** [AlexandreRouma/SDRPlusPlus#1279]
**Feature description**
Hi!
Msi.sdr dongle good work on windows app  SDR++
But on Android app SDR++ it missing from sources
No support Android MSI or trouble with my device?

**Comment by AlexandreRouma** [comment]
The SDRplay API cannot be supported on android.

**Comment by RusikOk** [comment]
How does the RSP1 work with SDR Touch on android?

**Comment by RusikOk** [comment]
https://www.sdrplay.com/docs/AndroidIntegrationNote.pdf

**Comment by AlexandreRouma** [comment]
I know that. SDR++ uses the V3 api, not V2. I'm not writing a second SDRplay source just to get android support.
