### ISSUE TITLE
sdrpp cannot be installed due to a missing libvolk1 and libvolk2. Only libvolk 3 is available on debian trixie

### ISSUE THREAD

**Issue by sysadminpower2019** [AlexandreRouma/SDRPlusPlus#1296]
Hello,

I am unable to install Sdrpp on debian trixie as only has libvolk3 in it's repositories 

https://packages.debian.org/search?searchon=sourcenames&keywords=volk

**Comment by AlexandreRouma** [comment]
build from source, it doesn't caer about the volk version
