### ISSUE TITLE
GPU usage spikes

### ISSUE THREAD

**Issue by Tanamichi** [AlexandreRouma/SDRPlusPlus#1299]
Hello there!
Strange behavior if sdrpp launched on Windows and waterfall enabled.
before write this issue i double checked my system for miners and other bloatware, it's clean :) 
I look into task tab and see sdrpp GPU usage high. 

Tried with latest nightly:
![title](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/aeff4a9d-d58a-4dc0-86c6-62c047cd5641)
Problem follow from previous versions...

Now i started examine:
1. Waterfall disabled. GPU usage more stable but sometimes spikes GPU usage to 80%
2. Waterfall enabled. GPU usage unstable, spikes come on 80% more periodic.
3. Unpredictable GPU usage. it can more stable without any reasons.
4. Focused or back-grounded sdrpp still invoke GPU usage spikes. 
5. Selected SDR source not affect to spikes. (tried Remote SDR++ server with RTL-SDR and local RSP1 SDR)

it can also affect on other platforms like ARM with weak GPU.

i use these display settings for now and wrote this issue: 
![sdrpp display settings](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/cfa5f647-23f4-451e-94b8-8f5e7b413209)

screenshots below taken in different time.
![screen](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/f2676d1b-9355-4edb-b68d-0905bbb1576d)
![screen](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/1b1d7a55-f4f6-4817-9ce8-33310359475e)
![screen](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/89d4876c-7991-47ef-a665-5fe1eab6f331)

here is small gif with problem:
![sdrpp_issue](https://github.com/AlexandreRouma/SDRPlusPlus/assets/14316605/ba96407d-145e-4994-9876-43d5d44c9e3b)

**Comment by AlexandreRouma** [comment]
1) Issue template not filled out, If the issue wasn't clear cut I'd have closed it and told you to fill it out properly
2) Your graphics driver is the issue. None of my machines do this, not on windows, not on linux, not on macos and not even on android.

**Comment by Tanamichi** [comment]
Thanks. Updating to last nvidia driver solved problem :)
