### ISSUE TITLE
Feature request: Decimation

### ISSUE THREAD

**Issue by Manawyrm** [AlexandreRouma/SDRPlusPlus#13]
Hi,

this is not very important, but it would be nice to be able to set a decimation to get a bit more dynamic range in exchange for sample rate. Some SDRs with really high sample rates (like the HackRF (and even the RTL-SDRs)) can really benefit from that.

**Comment by AlexandreRouma** [comment]
Hi,
This is certainly possible, a simple FIR resampler should do the trick.
Does use a bit of CPU power though, so it'll be an optional feature.
