### ISSUE TITLE
SDRplay not recognized anymore

### ISSUE THREAD

**Issue by loewal** [AlexandreRouma/SDRPlusPlus#1304]
I issued a bug yesterday, but today that issue has disappeared....Strange!

SDRplay is missing as module. Please check!

**Comment by loewal** [comment]
> I issued a bug yesterday, but today that issue has disappeared....Strange!
> 
> SDRplay is missing as module. Please check!

and the number of bytes is 3.5 KB smaller...

**Comment by AlexandreRouma** [comment]
As I already told you, update the version to version 3.12.1.
