### ISSUE TITLE
[Feature Request]Add Malahit-DSP 1/2 support for Android release

### ISSUE THREAD

**Issue by wujinjun-MC** [AlexandreRouma/SDRPlusPlus#1329]
**Feature description**
* Add Malahit-DSP-1 and Malahit-DSP-2 support for Android release
    * Frequency ranges:
        * DSP-1: 50kHz-250MHz and 400MHz-2000MHz (LW,MW,SW,VHF,UHF,...)
        * DSP-2: 10kHz-380MHz and 404MHz-2000MHz (LW,MW,SW,VHF,UHF,...)
     * Waterfall width:
        * DSP-1: 160kHz, 80kHz, 40kHz
        * DSP-2: 192kHz, 96kHz, 48kHz
    * Modes: AW, SSB(LSB,USB), DSB, CW, NFM, WFM
    * Supported connection:
        * DSP-1: USB2.0
        * DSP-2: USB2.0, Bluetooth(optional, by adding bluetooth PCB board)

**Comment by AlexandreRouma** [comment]
it's just a soundcard and I don't have one anyway. Just wait for android to have the audio source.
