### ISSUE TITLE
Trying to run SDR++ with Nooelectric Smart SDR V5...

### ISSUE THREAD

**Issue by pnloud1** [AlexandreRouma/SDRPlusPlus#1332]
Which Device do I select in SDR++ when running the NESDR Smart V5 ?

**Comment by AlexandreRouma** [comment]
Come on... did you do any research before buying it? Do you not know it's a RTL-SDR?
The answer to your question is plastered all over the manufacturer's website...
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/eeb544cf-6477-407d-ba87-6803359ec377)

**Comment by pnloud1** [comment]
Excuse me nerd but there is a device called Rtl sdr that is Not the NESDR
Smart sdr. By a different company.
