### ISSUE TITLE
Pager decoder not working in FLEX mode

### ISSUE THREAD

**Issue by alphapats** [AlexandreRouma/SDRPlusPlus#1333]
**Hardware**
- CPU: 12 Gen Intel i7
- RAM: 16GB
- GPU: Yes
- SDR: File source (Link to IQ file being tested: https://www.sigidwiki.com/wiki/File:FLEX_Pager_IQ_20150816_929613kHz_IQ.zip)

**Software**
- Operating System: Ubuntu 22.04
- SDR++:  SDR++ v1.1.0 (compiled from source)

**Bug Description**
When I am trying to decode Pager message in FLEX protocol, waterfall freezes and there is no output. When I deselect the FLEX protocol, file starts playing and waterfall is dispalyed.

**Steps To Reproduce**
1. Select File using file source
2. Enable Pager decoder
3. Select Protocol Flex
4. Waterfall freezes

Link to IQ file being tested: https://www.sigidwiki.com/wiki/File:FLEX_Pager_IQ_20150816_929613kHz_IQ.zip

**Screenshots**
![Screenshot from 2024-02-21 11-47-05](https://github.com/AlexandreRouma/SDRPlusPlus/assets/20792136/8cffa926-9649-437b-959d-fda25bc83cdd)

**Additional info**
Decoder is working fine for POCSAG protocol when using file (https://www.sigidwiki.com/wiki/File:POCSAG_IQ.zip)

**Comment by AlexandreRouma** [comment]
Interesting, there's might be a reason why its build is disabled, it's not included in any of the nightly builds and the readme says it's unfinished
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/32ccec75-e7f1-4f31-94ae-50b61f9e88c2)
