### ISSUE TITLE
Home button only toggles waterfall if display menu is not collapsed

### ISSUE THREAD

**Issue by KubaPro010** [AlexandreRouma/SDRPlusPlus#1335]
**Hardware**
- CPU: Intel Xeon L5640 (amd64)
- RAM: 24GB
- GPU: GTX 1070
- SDR: Any

**Software**
- Operating System: Windows 10
- SDR++: v1.1.0 20:58:19 Feb 8 2024

**Bug Description**
The home button should toggle the waterfall, but that only works if the display menu isnt collapsed, but when it is it doesnt to anything, no error or anything, even no nothing in the console

**Steps To Reproduce**
1. Collapse "Display"
2. Press `Home`

**Additional Info**
from what i can see its probably caused because of [this file, the display menu](https://github.com/AlexandreRouma/SDRPlusPlus/blob/7c933d51037ce8c8e703e6869d8ff36e9cd6476e/core/src/gui/menus/display.cpp#L132) it checks the home button here to fix this it the logic to toggle the waterfall should be moved somewhere else

**Comment by AlexandreRouma** [comment]
Fixed
