### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Schrille** [AlexandreRouma/SDRPlusPlus#1339]
APK on my Smartphone withAndroid 12  works,but it seems to need a external Screen,since only a part of the modules where seen on 7" smartphone
It should be divided on more screens,so that could be use as the home screen's
e.g. brush left or right to get next modules?🤷🏼‍♀️

**Comment by AlexandreRouma** [comment]
Not a valid bug report. Additionally, check the manual for how to set the UI scale.
