### ISSUE TITLE
No signal only white noise with RTLsdr v4

### ISSUE THREAD

**Issue by Schrille** [AlexandreRouma/SDRPlusPlus#1340]
I have downloadet sdrpp but only noise.
No signals received on FM broad band.direct sampling is of, gain is high, mod is WFM

In sdr# every thing works fine.
I guess sdrpp does not work with my dongle

![20240225_214406](https://github.com/AlexandreRouma/SDRPlusPlus/assets/57689636/2f0da1ed-26c9-42b2-9d38-7e3ec1724257)
any suggestion's?🤷🏼‍♀️

**Comment by kmp56** [comment]
https://www.rtl-sdr.com/V4/

" Download the Releases.zip file from our [RTL-SDR Blog Driver GitHub releases page](https://github.com/rtlsdrblog/rtl-sdr-blog/releases). 
   - Copy the rtlsdr.dll file into the folder of the software you are using. Usually this will be replacing an existing rtlsdr.dll file.
   - On some computers you may also need to copy the msvcr100.dll and pthreadVC2.dll file into the folder too. It does not hurt to copy these in anyway, even if you don't need them.

If for some reason the RTL-SDR Blog release is not working for you, please try the latest Osmocom build at https://ftp.osmocom.org/binaries/windows/rtl-sdr/ which is now also compatible. "

**Comment by Schrille** [comment]
thanks, copy these .dll files that reallydid the trickVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: kmp56 ***@***.***> Datum: 26.02.24  22:43  (GMT+01:00) An: AlexandreRouma/SDRPlusPlus ***@***.***> Cc: Nicole ***@***.***>, Author ***@***.***> Betreff: Re: [AlexandreRouma/SDRPlusPlus] No signal only white noise with RTLsdr v4 (Issue #1340) 
https://www.rtl-sdr.com/V4/
" Download the Releases.zip file from our RTL-SDR Blog Driver GitHub releases page.

Copy the rtlsdr.dll file into the folder of the software you are using. Usually this will be replacing an existing rtlsdr.dll file.
On some computers you may also need to copy the msvcr100.dll and pthreadVC2.dll file into the folder too. It does not hurt to copy these in anyway, even if you don't need them.

If for some reason the RTL-SDR Blog release is not working for you, please try the latest Osmocom build at https://ftp.osmocom.org/binaries/windows/rtl-sdr/ which is now also compatible. "
