### ISSUE TITLE
Manjaro just stopped working can't find libvolk.so.3.0

### ISSUE THREAD

**Issue by phoniclynx** [AlexandreRouma/SDRPlusPlus#1342]
**Hardware**
- CPU: i7
- RAM: 32gb
- GPU: 
- SDR: Local

**Software**
- Operating System: Manjaro Rolling
- SDR++: Not too sure as I can't open it

**Bug Description**
For the longest time, this was working fine then one day out of the blue SDR++ decided it wouldn't open. When opening It from the command line I get the following error:
```
sdrpp: error while loading shared libraries: libvolk.so.3.0: cannot open shared object file: No such file or directory

```
**Steps To Reproduce**

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Linux: Open a terminal and run `sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

```
sdrpp -c                                                     127 ✘ 
sdrpp: error while loading shared libraries: libvolk.so.3.0: cannot open shared object file: No such file or directory
```

**Comment by AlexandreRouma** [comment]
If it was installed with the AUR, stop using that, it's unofficial and unsupported.*
If it was installed from source, just rebuild and reinstall. This is normal on all rolling release distros.
