### ISSUE TITLE
Error -lglfw3 while make step

### ISSUE THREAD

**Issue by PuperzenWalter** [AlexandreRouma/SDRPlusPlus#1348]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU:  Broadcom Quad-Core Cortex-A72 (ARM v8), 1,5 GHz
- RAM:  8GB LPDDR4
- GPU:  Broadcom VideoCore VI, 500 MHz
- SDR:  RTL-SDR.com V4

**Software**
- Operating System: Raspberry Pi OS 64Bit - Debian GNU/Linux 12 (bookworm)
- SDR++:  i tried: "SDRplay_RSP_API-Linux-3.14.0  &  sdrpp_raspios_bullseye_arm64.deb & sdrpp_raspios_bullseye_armhf.deb"
                              same error on every installation....

**Bug Description**
in the "make" step every time I get this error:
########################################
[ 48%] Linking CXX shared library libsdrpp_core.so
/usr/bin/ld: skipping incompatible /usr/local/lib/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/local/lib/libglfw3.a when searching for -lglfw3
/usr/bin/ld: cannot find -lglfw3: No such file or directory
/usr/bin/ld: skipping incompatible /usr/local/lib/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libglfw3.a when searching for -lglfw3
/usr/bin/ld: skipping incompatible /usr/local/lib/libglfw3.a when searching for -lglfw3
/usr/bin/ld: cannot find -lglfw3: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [core/CMakeFiles/sdrpp_core.dir/build.make:1000: core/libsdrpp_core.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:876: core/CMakeFiles/sdrpp_core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
########################################

I tried to change the name from -lglfw3 to -lglfw in the /home/pi/SDRPlusPlus/build/CMakeFiles/sdrpp.dir/link.txt:
####### original ########
/usr/bin/c++ CMakeFiles/sdrpp.dir/src/main.cpp.o -o sdrpp   -L/usr/local/lib  -Wl,-rpath,/usr/local/lib:/home/pi/SDRPlusPlus/build/core: core/libsdrpp_core.so core/libcorrect/lib/libcorrect.a -lglfw3 /usr/lib/aarch64-linux-gnu/libOpenGL.so /usr/lib/aarch64-linux-gnu/libGLX.so /usr/lib/aarch64-linux-gnu/libGLU.so -lfftw3f -lglfw3 /usr/lib/aarch64-linux-gnu/libOpenGL.so /usr/lib/aarch64-linux-gnu/libGLX.so /usr/lib/aarch64-linux-gnu/libGLU.so -lfftw3f -lvolk -lzstd -lstdc++fs 
######################
but this didn't solve my problem.

If someone could help me in this case, please let me know. I spend hours and hours and didn't fix that.
Thx in advance.

**Comment by AlexandreRouma** [comment]
there's just something really messed up about the linux environment and I honestly can't tell you what it is.

In any case, it's not a bug with SDR++.
