### ISSUE TITLE
Any chance of upgrade to SdrPlay API 3.14.0

### ISSUE THREAD

**Issue by Durakill** [AlexandreRouma/SDRPlusPlus#1349]
**Feature description**

I'm greedy, I know, but I'd like to swap between SdrAngel and SDR++ without having to install different SdrPlay APIs - 3.12 for SDR++, 3.14 for SdrAngel, on M1 Mac, Sonoma 14.2.1

It only takes a couple of minutes to swap between the two by installing the appropriate .pkg, but each app has its own benefits for me.

I use the pre-built downloads, being very old. I guess dependencies on the 3.12  SdrPlay API will be upgraded to 3.14 eventually, so no real problem. 

Excellent app, by the way.

**Comment by AlexandreRouma** [comment]
followi this issue instead since it's basically the same root cause: #1311
