### ISSUE TITLE
pre-setup dependency install fails on debian bullseye

### ISSUE THREAD

**Issue by mabra** [AlexandreRouma/SDRPlusPlus#1350]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: AMD EPYC 7252
- RAM: 64 GB
- GPU: Radeon RX 5500/5500M
- SDR: (Remote or local? If remote, what protocol?) local, 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)
  Debian GNU/Linux 11 (bullseye)
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the 
  does not apply - cannot install dependencies
- SDR++ icon in the top right corner of the software).

**Bug Description**
A clear description of the bug.

**Steps To Reproduce**
1. 
apt install --assume-no -V libfftw3-dev libglfw3-dev libvolk2-dev libzstd-dev libsoapysdr-dev libairspyhf-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfftw3-dev is already the newest version (3.3.8-2).
libfftw3-dev set to manually installed.
libvolk2-dev is already the newest version (2.4.1-2).
libvolk2-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.66.8-1+deb11u1) but 2.72.3-1 is to be installed
                  Depends: libglib2.0-bin (= 2.66.8-1+deb11u1) but 2.72.3-1 is to be installed
                  Depends: libglib2.0-dev-bin (= 2.66.8-1+deb11u1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.

**Comment by AlexandreRouma** [comment]
Ask support from your distro, nothing to do with SDR++
