### ISSUE TITLE
It should not be possible to change the center frequency when recording to a baseband file

### ISSUE THREAD

**Issue by ChrisSmolinski** [AlexandreRouma/SDRPlusPlus#1353]
Currently it's possible to change the center frequency while recording to a baseband file. This should not be the case, center frequency changes should be disabled until the user stops recording.

**Comment by AlexandreRouma** [comment]
It very much should. The recorder module has no business locking out the user from tuning the SDR. It's the user's responsibility to keep the center frequency constant if that's what they want in their recording.
