### ISSUE TITLE
Android app is oversized

### ISSUE THREAD

**Issue by TechnoZombie** [AlexandreRouma/SDRPlusPlus#1355]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: Qualcomm SM6115 Snapdragon 662 (11 nm) - Octa-core (4x2.0 GHz Kryo 260 Gold & 4x1.8 GHz Kryo 260 Silver)
- RAM: 3GB
- GPU: Adreno 610
- SDR: Local

**Software**
- Operating System: Android 12
- SDR++: 1.1.0 android (can't see build because of bug being reported)

**Bug Description**
On a 10' android tablet display, the app is oversized, making it difficult to use.

**Steps To Reproduce**
1. Install app on 10' tablet (or a screen bigger than a phone)
2. Verify oversizing.
(verify attached picture) 

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
![Screenshot_20240308-234542](https://github.com/AlexandreRouma/SDRPlusPlus/assets/124879219/57cb5d16-35b1-452e-b9e4-3076758482ae)

**Additional info**
I'm available to do further testing and providing other screenshots

**Comment by AlexandreRouma** [comment]
https://www.sdrpp.org/manual.pdf page 13
