### ISSUE TITLE
SDR++ crashes silently when SoapySDR driver raises an exception

### ISSUE THREAD

**Issue by alexander-sholohov** [AlexandreRouma/SDRPlusPlus#1361]
**Software**
- Operating System: Windows 10 x64
- SDR++: Is built from master branch using MSVC toolchain

**Bug Description**
SoapySDR drivers can raise an exception in SoapySDR::Device::make(). When this happens SDR++ crashes silently. 
This fix [link](https://github.com/alexander-sholohov/SDRPlusPlus/commit/712d771952a3603c039f64929f2f591882c3020a) fixes this issue.

**Comment by AlexandreRouma** [comment]
It's polishing a turn at this point considering I want to sunset the soapysdr support but anyway.

Unless you use some really esoteric hardware, there should be no reason for you to use the SoapySDR source, almost all mainstream SDRs are natively supported.
