### ISSUE TITLE
VirusTotal Flagging as Containing Trojan

### ISSUE THREAD

**Issue by dustin33547** [AlexandreRouma/SDRPlusPlus#1362]
VirusTotal is flagging the zip folder for Windows as containing Trojan.Malware.300983.susgen

This was flagged by an antivirus company named MaxSecure. I have no history with using this company, so this may be a false positive. Waiting to hear response before installing software.

The issue appears to be with the two files below:
sdrpp_windows_x64/perseus-sdr.dll
sdrpp_windows_x64/modules/frequency_manager.dll

Link to analysis: https://www.virustotal.com/gui/file/957fdedbc44d94b1ef767e7b319ea2b0607cfb046b029db865744d77e39fcb5b/detection

**Comment by AlexandreRouma** [comment]
False positive and can't do anything about it. The builds are made on github's own servers and are fully traceable if you don't trust it.

In any case, it's not a bug and there's nothing I can do about it?
