### ISSUE TITLE
Crash when scrolling mouse over FFT and waterfall.

### ISSUE THREAD

**Issue by daianjibetu** [AlexandreRouma/SDRPlusPlus#1367]
**Hardware**
- CPU: Apple M1
- RAM: 8GB
- GPU: 
- SDR: USRP B210

**Software**
- Operating System: MacOS 14.4.1
- SDR++: Nightly Build (currently 1.1.0)

**Bug Description**
Crash when scrolling mouse over FFT and waterfall.

The crash report is below.
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000028
> Exception Codes:       0x0000000000000001, 0x0000000000000028
> 
> Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
> Terminating Process:   exc handler [5819]
> 
> VM Region Info: 0x28 is not in any region.  Bytes before following region: 4342415320
>       REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
>       UNUSED SPACE AT START
> --->  
>       __TEXT                      102d40000-102d44000    [   16K] r-x/r-x SM=COW  /Applications/SDR++.app/Contents/MacOS/sdrpp
> 
> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   libsdrpp_core.dylib           	       0x103411820 MainWindow::draw() + 8408
> 1   libsdrpp_core.dylib           	       0x103411820 MainWindow::draw() + 8408
> 2   libsdrpp_core.dylib           	       0x1034fdc70 backend::renderLoop() + 1840
> 3   libsdrpp_core.dylib           	       0x1033e78a8 sdrpp_main(int, char**) + 28644
> 4   dyld                          	       0x18252a0e0 start + 2360

**Additional info**

The application crashes because `if(vfo != null)` is missing in the following part.
It looks like you are assigning an undefined value.
After modifying the code, the crash no longer occurs.

https://github.com/AlexandreRouma/SDRPlusPlus/blob/e1c48e9a1f6eca5b7c0a9cc8e0029181ac6c5f2d/core/src/gui/main_window.cpp#L581-L589

I will submit a pull request if needed.

**Comment by AlexandreRouma** [comment]
Fixed
