### ISSUE TITLE
AM Squelch Buzz

### ISSUE THREAD

**Issue by Starman0620** [AlexandreRouma/SDRPlusPlus#137]
### Issue
While listening to AM radio with a squelch of -20 (haven't bothered to try others), there is a very loud buzzing sound that occurs.
This does **not** occur in any other mode for me.

### Reproducing
To reproduce this issue, set your radio mode to AM and set your squelch to -20dB. After some time (about a minute usually for me), there will be a very loud buzzing sound that will not stop unless you set the squelch to -100dB or, in some cases, if there is a signal that can be heard past the squelch.

**Comment by AlexandreRouma** [comment]
should be fixed
