### ISSUE TITLE
Switching to Larger Fonts makes all Characters 9's

### ISSUE THREAD

**Issue by rogerxxxx** [AlexandreRouma/SDRPlusPlus#1376]
**Hardware**
- CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
- RAM: 32G
- GPU: Intel Corporation DG2 [Arc A750]
- SDR: local

**Software**
- Operating System: Linux Void, rolling release
- SDR++: SDRPlusPlus-1.0.4_3

**Bug Description**
Switching to Larger Fonts makes all Characters 9's

**Steps To Reproduce**
1. Activate Debug > Show demo window
2. Configuration > Style > switch from Roboto-Medium.ttf 16px to Roboto-Medium.ttf 45px
3. Notice all characters within sdrpp are now 9's
4. Can escape/revert from anomaly by finding the second selection drop down box, selecting the first entry of 9's

**Screenshots**
![screenshot-20240405-211851](https://github.com/AlexandreRouma/SDRPlusPlus/assets/12102230/0c22b875-c114-48da-955a-2321d09638cb)
![screenshot-20240405-211944](https://github.com/AlexandreRouma/SDRPlusPlus/assets/12102230/359ae584-f7f5-43f6-afdd-385d1c86dc3c)

**Additional info**
Nothing is printed within stdout console, indicating font files not found or other errors/warnings.  Also, the font 45px font is huge!  Ah, just found the High-DPI option, for enlarging the font/graphical display size, located under the left-hand "Display" menu.  Only 100% (default), 200%, 300% ... options.  The 200% is really too large for my 27 inch Dell display, so should be also include 150%, 250%, ... as well.

**Comment by AlexandreRouma** [comment]
I'm not gonna waste time explaining why but this is completely normal and expected behavior, you just don't know what these debug settings do.
