### ISSUE TITLE
Spectrum/waterfall disappears after computer nap

### ISSUE THREAD

**Issue by JohBod** [AlexandreRouma/SDRPlusPlus#1381]
**Hardware**
- CPU: 
![bild](https://github.com/AlexandreRouma/SDRPlusPlus/assets/27567970/d4ce38b3-02e5-461b-bddd-dc23645aac42)

- RAM: 16GB
- GPU: 
![bild](https://github.com/AlexandreRouma/SDRPlusPlus/assets/27567970/0e8c99d7-73da-4c1f-abbd-2f57246d6578)

- SDR: (Remote or local? If remote, what protocol?)
Local. Airspy HF+ (old, "dual port" version)

- **Software** Win10
- SDR++: v1.1.0 Built at 20:19:27, Apr 10 2024

**Bug Description**
Spectrum display disappears after computer goes into nap mode (no user activity for some minutes => black screens on all attached monitors). After moving mouse, or touching a key, to wake the PC up from its nap, only the WF is shown in SDR++. I'm unable to find a "grab line" to move the border between spectrum and WF. Unchecking "Show Waterfall" in the display menu just swaps from waterfall to spectrum view but there is no way to show both. I never experienced this behaviour in earlier versions of SDR++.

**Steps To Reproduce**
1. ... See above..

Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).
After PC wake-up from nap:
![bild](https://github.com/AlexandreRouma/SDRPlusPlus/assets/27567970/22ceb03e-8b92-4338-a2e8-f4e691915ba6)

After unchecking "Show Warerfall": 
![bild](https://github.com/AlexandreRouma/SDRPlusPlus/assets/27567970/956824a1-f7be-43a7-9714-33b0f2887002)

**Comment by AlexandreRouma** [comment]
Seems to have come from a bad commit pushed on april 10th.
Should now be fixed, let me know if not.

**Comment by AlexandreRouma** [comment]
Additional note: If the broken FFT display persists after restarting SDR++, delete the `config.json` file to reset the main configuration.

**Comment by JohBod** [comment]
Thank you for the quick fix! Will test immediately. Regarding the deletion of config.json, I figured out that trick myself ;)
