### ISSUE TITLE
Errors when running on Ubuntu 24.04

### ISSUE THREAD

**Issue by S5NC** [AlexandreRouma/SDRPlusPlus#1392]
**Software**
Ubuntu 24.04
sdrpp_ubuntu_mantic_amd64.deb (nightly as of now)

**Bug Description**
There is no noble numbat target and running fails due to the error below. It is similar to errors when other Ubuntu releases were made https://github.com/AlexandreRouma/SDRPlusPlus/issues/604
> sdrpp: error while loading shared libraries: libvolk.so.3.0: cannot open shared object file: No such file or directory

**Steps To Reproduce**
1. Download the file
2. `sudo apt install ./sdrpp_ubuntu_mantic_amd64.deb`
3. `sdrpp`

Can releases be made such that there is no need for specific OS-version release?

I can't build from source because I get the error 

> CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message): The following required packages were not found: - libairspy

**Comment by KubaPro010** [comment]
Looks like you don't have the libraries installed (atleast for self-compile), you need to run `sudo apt install libfftw3-dev libglfw3-dev libvolk2-dev libzstd-dev libairspyhf-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev` or just disable the modules ([list](https://github.com/AlexandreRouma/SDRPlusPlus?tab=readme-ov-file#module-list)) with `-D{name}=OFF` appended to the `cmake ..`

**Comment by AlexandreRouma** [comment]
@KubaPro010 No.

I can't believe I need to say this shit every time a new ubuntu or debian version is released:
You are trying to install a deb built for the wrong OS version... If you don't see a build for your distro version, build from source.

**Comment by AlexandreRouma** [comment]
because it doesn't say the package name, it says the library name

**Comment by arekm** [comment]
Author doesn't want official build for 24.04 LTS it seems (judging from closing https://github.com/AlexandreRouma/SDRPlusPlus/pull/1395 without any comment).

Anyway here is a build (deb inside) made by github using workflow job from above pull request:

[sdrpp_ubuntu_noble_amd64.zip](https://github.com/AlexandreRouma/SDRPlusPlus/files/15205146/sdrpp_ubuntu_noble_amd64.zip)

**Comment by AlexandreRouma** [comment]
1) As clearly stated in multiple places (including issues, contributing.md, etc), I don't accept pull request for anything except local band plans.
2) I accept even less pull requests to create builds for an OS on which I haven't tested anything.

There will be a build when it is ready and tested

**Comment by arekm** [comment]
Actually I saw pull request template but thought... that cannot be *that* crazy. Turns out it is. My mistake.

I would submit a pull request improving that template, like adding bit fat warning

"IMPORTANT NOTICE: Really, only requests that meet the specified criteria will be considered. Any other submissions will be disregarded and closed without further comment."

there but... such pull request would also be ignored.

**Comment by AlexandreRouma** [comment]
There is nothing "crazy" about not accepting pull requests. Reviewing changes usually takes longer than just implementing them myself, especially when they're large. The time I've wasted back when pull requests were accepted more than justifies not accepting them. If you want to contribute, do like the template says and open an issue suggesting changes.

And lets not even mention the basic common sense if not adding a nightly build for an OS the dev hasn't tested anything on. YOU are not the one that is going to get flooded by angry emails the next day saying there is a problem if these problems haven't showed themselves on your system. Trust me, it happens.
