### ISSUE TITLE
Hermes - fixed IP / No discovery

### ISSUE THREAD

**Issue by ok2it** [AlexandreRouma/SDRPlusPlus#1393]
Hello

for us behind NAT and Remote HL2 can you please add same feature as RTL_TCP etc. so having a input for:
IP Address
PORT
(Port can stay 1024....we all mostly use it).
Other SW - SparkSDR,SDR-Console etc.all allow for setting a static IP without need of broadcast discovery.

BR Jiri

**Comment by AlexandreRouma** [comment]
You really should not be running an SDR like this over the internet allowing anyone with your IP address full control of your TX capable SDR...

I'm not gonna add features encouraging this, use something like wireguard instead to access your network remotely.
