### ISSUE TITLE
Program exits on startup, fails on properly using OpenGL 2.1

### ISSUE THREAD

**Issue by Peter3579** [AlexandreRouma/SDRPlusPlus#1408]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: 
          product: Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          version: 6.37.5
          size: 3200MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid dtherm arat vnmi flush_l1d cpufreq
          configuration: microcode=7

- RAM:
description: System memory
          physical id: 0
          size: 11GiB

- GPU: 
description: VGA compatible controller
             product: Core Processor Integrated Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             logical name: /dev/fb0
             version: 18
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom fb
             configuration: depth=32 driver=i915 latency=0 resolution=2560,1440
             resources: irq:30 memory:fb800000-fbbfffff memory:e0000000-efffffff ioport:ff00(size=8) memory:c0000-dffff

- SDR: (Remote or local? If remote, what protocol?)
not relevant, fails before

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)
Linux 6.6.30-2-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May  8 17:46:43 UTC 2024 x86_64 GNU/Linux

- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).
Latest source code version from git. Local build.

**Bug Description**
A clear description of the bug.

Program aborts on startup. See below.

**Steps To Reproduce**

$ ./sdrpp -r root_dev/
[26/05/2024 21:09:21.000] [INFO] SDR++ v1.2.0
[26/05/2024 21:09:21.000] [INFO] Loading config
[26/05/2024 21:09:21.000] [INFO] Unused key in config fftRedrawingThreads, repairing
[26/05/2024 21:09:21.000] [ERROR] Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
[26/05/2024 21:09:21.000] [INFO] OpenGL 3.0 was not supported
[26/05/2024 21:09:21.000] [ERROR] Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
[26/05/2024 21:09:21.000] [INFO] OpenGL 3.1 ES was not supported
[26/05/2024 21:09:21.000] [INFO] Using OpenGL 2.1
Failed to initialize OpenGL loader!
[26/05/2024 21:09:21.000] [WARN] Could not init using OpenGL with normal GLSL version, falling back to GLSL 1.2
Failed to initialize OpenGL loader!
[26/05/2024 21:09:21.000] [ERROR] Failed to initialize OpenGL with GLSL 1.2
$ 

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

$ ./sdrpp -c
[26/05/2024 21:18:32.000] [INFO] SDR++ v1.2.0
Unknown argument
-a --addr		Server mode address
   --autostart		Automatically start the SDR after loading
-h --help		Show help
-p --port		Server mode port
-r --root		Root directory, where all config files are stored
-s --server		Run in server mode
$ 

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.

See  https://github.com/AlexandreRouma/SDRPlusPlus/issues/1325. The issue is still present and needs fixing.
Everything else on my Linux installation works fine. It is your software only.

**Comment by AlexandreRouma** [comment]
Hardware too old, GLSL 1.2 is required **in addition to OpenGL 2.1**.

Stop blaming developers for your prehistoric hardware.
