### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by doddy74** [AlexandreRouma/SDRPlusPlus#1411]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: 64-bit quad-core Cortex A-72 (ARM v8) processor at 1.5GHz
- RAM: 2GB
- GPU: 
- SDR: Local

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).

**Bug Description**
A clear description of the bug.
CMake Error at /usr/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/doddy74/Desktop/SDRPlusPlus/build/CMakeFiles/CMakeScratch/TryCompile-cFyegT
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_d02ce/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_d02ce.dir/build.make CMakeFiles/cmTC_d02ce.dir/build
    gmake[1]: Entering directory '/home/doddy74/Desktop/SDRPlusPlus/build/CMakeFiles/CMakeScratch/TryCompile-cFyegT'
    Building C object CMakeFiles/cmTC_d02ce.dir/testCCompiler.c.o
    Bus error
    gmake[1]: *** [CMakeFiles/cmTC_d02ce.dir/build.make:77: CMakeFiles/cmTC_d02ce.dir/testCCompiler.c.o] Error 135
    gmake[1]: Leaving directory '/home/doddy74/Desktop/SDRPlusPlus/build/CMakeFiles/CMakeScratch/TryCompile-cFyegT'
    gmake: *** [Makefile:127: cmTC_d02ce/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Steps To Reproduce**
1. sudo apt update
2. git clone https://github.com/AlexandreRouma/SDRPlusPlus.git
3. cd SDRPlusPlus
4. sudo apt install -y build-essential cmake git libfftw3-dev libglfw3-dev libglew-dev libvolk2-dev libsoapysdr-dev libairspyhf-dev libairspy-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev librtlsdr-dev libbladerf-dev liblimesuite-dev p7zip-full wget
5. mkdir -p build
6. cd build
7. cmake .. -DOPT_BUILD_LIMESDR_SOURCE=ON -OPT_BUILD_RTL_SDR_SOURCE

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.

**Comment by AlexandreRouma** [comment]
Definitely nothing to do with SDR++, there's an issue with your C compiler or your environment in general.
