### ISSUE TITLE
Update to new RFNM API names

### ISSUE THREAD

**Issue by bkerler** [AlexandreRouma/SDRPlusPlus#1425]
**Feature description**
Update the librfnm support. Fix is here, as you obviously don't want PRs : 
[Patch](https://github.com/AlexandreRouma/SDRPlusPlus/compare/master...bkerler:SDRPlusPlus:librfnm_support.patch)

**Comment by AlexandreRouma** [comment]
No need to post some code, I know what has to change and I don't copy code. I'm just busy at the moment.

**Comment by AlexandreRouma** [comment]
update done

**Comment by bkerler** [comment]
;)
