### ISSUE TITLE
rigctl_server unable to evaluate mode change bandwidth string

### ISSUE THREAD

**Issue by guitarpicva** [AlexandreRouma/SDRPlusPlus#1434]
**Bug Description**
misc_modules/rigctl_server/src/main.cpp

~ line 450 the Mode setting string for the bandwidth is evaluated for being all digits or
the first char being '-'.  Looping through the std::string for chars seems to also eval 
the closing NULL of the c_str and so the evaluation always fails.

**Steps To Reproduce**
1. start sdrpp
2. telnet to running rigctl_server on the sdrpp
3. send mode change command e.g. M AM 6000

Eliminating that section of the code allows properly formatted commands to work.

**Comment by AlexandreRouma** [comment]
Works fine for me. You're probably trying to connect with telnet which adds extra terminal control junk.
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/ff64f031-322a-4590-9d1e-25c569a49995)
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/81b44fae-03b0-4c26-aff7-e3906c975a0d)

**Comment by guitarpicva** [comment]
You are perhaps correct, though I did try raw TCP socket from PuTTY as well.

**Comment by guitarpicva** [comment]
Tested your way and worked correctly with original code.   I guess I"m used to using Hamlib  rigctl via a telnet session.  Sorry to bother!!

**Comment by guitarpicva** [comment]
adding the line marked "// MW remove...." seems to tolerate telnet sessions.  It 
seems it was only the carriage returns causing angst with normal linux telnet.  Not 
really important, but I was curious. :)

// Split command into parts and remove excess spaces
        for (char c : cmd) {
            if(c == '\r') {continue;} // MW remove carriage returns from things like telnet
            if (lastWasSpace && c == ' ') { continue; }
            else if (c == ' ') {
                parts.push_back(corr);
                corr.clear();
                lastWasSpace = true;
            }
            else {
                lastWasSpace = false;
                corr += c;
            }
        }
