### ISSUE TITLE
disable grids

### ISSUE THREAD

**Issue by coolest42u** [AlexandreRouma/SDRPlusPlus#1441]
**Feature description**
Hello,

is there a way to disable grids on spectrum ?

**Comment by AlexandreRouma** [comment]
there is not.
Why would you want to make the FFT plot *less* useful?

**Comment by coolest42u** [comment]
> there is not. Why would you want to make the FFT plot _less_ useful?

Your are right BUT, If you have an eye disorders like astigmatism or else lines becomes curved and flu.
