### ISSUE TITLE
how to upgrade SDR++ to v1.2.0 on intel MacBook

### ISSUE THREAD

**Issue by RickReale** [AlexandreRouma/SDRPlusPlus#1446]
I have SDR++ v1.1.0 and wish to upgrade to 1.2.0.
2017 MacBook 12' Retina running Monterey 12.7.5.
Download won't install. Get this:

<img width="990" alt="Screen Shot 2024-08-10 at 08 26 21" src="https://github.com/user-attachments/assets/76705298-1cac-437e-a541-c500392c5de1">

Don't remember just how I installed my original version last year or so, but do recall there was some other steps involving some other app to make it all happen.
Anyone here able to help me out with this?
Cheers.

**Comment by RickReale** [comment]
Further to above. It seems I have MacPorts installed but app still won't install.
Assuming I get there, will the Bookmarks and other settings be retained after the upgrade to 1.2.0?

**Comment by Axpelle** [comment]
This is a precaution against malware. SDR++ is legit but you must grant it permission to be opened. Google how to do this.

**Comment by RickReale** [comment]
Thanks Axpelle. Got it sorted and 1.2.0 is now installed and running well.
