### ISSUE TITLE
FFT resolution way worse than SDR#

### ISSUE THREAD

**Issue by mrx23dot** [AlexandreRouma/SDRPlusPlus#1451]
Same HW (chinese RTL SDR) on same signal:

in SDR#
![SDRsharp FFT](https://github.com/user-attachments/assets/a958aa9b-fdc3-4d69-b4d9-7ea40a7602b7)

vs in SDR++
![SDRpp FFT](https://github.com/user-attachments/assets/f2f79125-e563-4b10-bbb0-7c47727c98ab)

I couldn't get the same resulution anywhere near it, modulation is only 200Hz

**Comment by AlexandreRouma** [comment]
I have no fucking idea what the hell you're trying to do but your settings are nonsensical and you're zoomed in all the way.

Please just don't use my software, I'm not wasting time helping people this clueless.
