### ISSUE TITLE
SoapySDR module missing

### ISSUE THREAD

**Issue by daochild** [AlexandreRouma/SDRPlusPlus#1463]
**Hardware**
- CPU: 4Cores
- RAM: 6GB
- GPU: N/A
- SDR: SoapySDR

**Software**
- Operating System: De
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).

**Bug Description**
SoapySDR not found in the modules list

**Steps To Reproduce**
SoapySDR driver installed
SDR++ Installed by instruction on github
No errors!

![photo_2024-09-03_12-57-18](https://github.com/user-attachments/assets/13706b7b-af37-4c4f-85f2-16b2322ba673)

**Comment by daochild** [comment]
Do I need pass any parameters in cmake for this SDR?

**Comment by AlexandreRouma** [comment]
https://github.com/AlexandreRouma/SDRPlusPlus/issues/1455#issuecomment-2306309845
