### ISSUE TITLE
bladeRF module is loaded but not initialized on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [AlexandreRouma/SDRPlusPlus#147]
Hi
I just compiled the latest source on macOS.
When I run `sdrpp` from terminal, I can see the line that loads the bladeRF module in stdout:
`[2021-06-12 23:30:31.522] [info] Loading /usr/local/lib/sdrpp/plugins/bladerf_source.dylib`
But it's not initialized later (unlike RTL-SDR, HackRF and other modules) and for that reason, I don't have bladeRF in the `Source` drop-down menu.
Do you have an idea what might have gone wrong?
Not sure if this helps, but I've already made sure the bladeRF libraries are installed and also tested my bladeRF with gqrx to make sure it's detected and working.
Thanks

**Comment by AlexandreRouma** [comment]
This is normal, the module is currently unfinished.
You can create a module instance in the config if you wish to try it but using SoapySDR for it might work better
