### ISSUE TITLE
SDR++ Nightly Build (currently 1.2.0) doesn't have support for RTL-SDR on .deb files for Linux

### ISSUE THREAD

**Issue by mrgadotti** [AlexandreRouma/SDRPlusPlus#1471]
**Software**
- Operating System: Ubuntu 24.04
- SDR++: Nightly Build (currently 1.2.0)

**Bug Description**
- SDR++ Nightly Build (currently 1.2.0) doesn't have support for RTL-SDR on .deb files for Linux
- Before this download from Nightly, it's working fine on older version instaled before 2024-09-10
- Same error on Linux Mint 22
- I did build from sources and the RTL-SDR support return and it's working again
- MacOs build is working fine with RTL-SDR support

**Steps To Reproduce**
1. Download SDR++ Nightly Build (currently 1.2.0) for Ubuntu (sdrpp_ubuntu_noble_amd64.deb)
2. Install
3. Run

**Screenshots**

![image](https://github.com/user-attachments/assets/01b1f7ef-4aa8-4a34-98b3-9732b123c92a)

**Comment by AlexandreRouma** [comment]
Works fine here, make sure you're up to date.

**Comment by mrgadotti** [comment]
I did try on another VM from Linux Mint 21.2, with clean install, same error. The RTL-SDR doesn't appear on the list...
Interesting that it only occurs on Linux, on MacOS it works fine, list the RTL-SDR

![image](https://github.com/user-attachments/assets/0fcb5779-5f6d-4fc8-bc67-18697902d858)

**Comment by mrgadotti** [comment]
Build from yesterday, 2024-09-10

**Comment by AlexandreRouma** [comment]
You're probably using the wrong deb.

**Comment by AlexandreRouma** [comment]
is librtlsdr installed on that clean install?

**Comment by mrgadotti** [comment]
I need to really apologize, it works after install librtlsdr. Works on Ubuntu and Mint

sudo apt install librtlsdr2 librtlsdr-dev
