### ISSUE TITLE
Can’t find recording made on Android

### ISSUE THREAD

**Issue by trent78y** [AlexandreRouma/SDRPlusPlus#1481]
I made a recording recently and I cannot find it anywhere in the files app. I made the recording on a Samsung A51 and when I go into settings I can see the app is taking up 900MB so there is something saved but I don’t know where.

**Comment by c3kkos** [comment]
try listing all files in memory and sorting for decreasing size?

**Comment by trent78y** [comment]
> try listing all files in memory and sorting for decreasing size?

Sorry, I have tried lots of different file managers, adb. Not really sure where to go next.

I should have probably clarified in the original post that I am NOT rooted.

**Comment by AlexandreRouma** [comment]
the default path is in the app's own directory and modern android doesn't let you access it. You need ADB to get there.

Next time change the recording path to your SD card or something

**Comment by trent78y** [comment]
> the default path is in the app's own directory and modern android doesn't let you access it. You need ADB to get there.
> 
> Next time change the recording path to your SD card or something

I have tried adb and looked in so many directories but I still can’t find it.

**Comment by AlexandreRouma** [comment]
You need to go into the app's private directory.

**Comment by dsaderholm** [comment]
I am using adb to access this directory. I can see the two recordings there. Now how can I download them or access them?

**Comment by trent78y** [comment]
> I figured it out. This command will put those files into whatever direcory you ran ADB in:
> 
> `adb exec-out run-as org.sdrpp.sdrpp tar -cf - -C /data/user/0/org.sdrpp.sdrpp/files/recordings . | tar xf -`

This command saved my recording!!!!! Thank you so much!!!!!
