### ISSUE TITLE
Fobos not included in Mac build

### ISSUE THREAD

**Issue by thereisnocat** [AlexandreRouma/SDRPlusPlus#1485]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: Apple M1 Max
- RAM: 64 GB
- GPU: Built-in
- SDR: (Remote or local? If remote, what protocol?)  Fobos SDR (local)

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)  macOS 15.0
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).   1.2.0

**Bug Description**
A clear description of the bug.

The Mac build does not include the library for the FobosSDR due to a typo.

**Steps To Reproduce**
1. Download and open the macOS nightly build
2. Open the list of receivers under Source
3. Note that FobosSDR is not included.

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead…)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is…**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc…).

**Additional info**
Add any other relevant information.

I was able to pull the source from Github and build locally and saw the same thing. The issue is in `make_macos_bundle.sh`.  Line 38 points to `fobossdr_source.dylib` in the wrong directory (`file_source` instead of `fobossdr_source`).  The dylib is created, but it is not incorporated into the application. By updating the directory, I was able to build the application with support for FobosSDR.

**Comment by AlexandreRouma** [comment]
Should be fixed, I'll reopen if not.
