### ISSUE TITLE
there is no RTL-SDR option in the settings

### ISSUE THREAD

**Issue by toxa1983poloskov** [AlexandreRouma/SDRPlusPlus#1491]
version for [noble_amd64.deb]    1.2.0    there is no choice in the menu RTL-SDR .
why not and how to make it work? 
installed  deb file

drivers are installed, GQRX for example this works!

**Comment by AlexandreRouma** [comment]
template not filled out

**Comment by toxa1983poloskov** [comment]
what template?
![11 10](https://github.com/user-attachments/assets/0f0d60b7-511c-4242-a02d-edb062bf8658)
how to choose RTL-SDR ?

**Comment by KubaPro010** [comment]
install librtlsdr

**Comment by toxa1983poloskov** [comment]
drivers librtlsdr  installed!

in any case, there is no choice RTL-SDR

**Comment by KubaPro010** [comment]
run `sdrpp` in the terminal and post output
