### ISSUE TITLE
Shortcuts interfering when inside a text field

### ISSUE THREAD

**Issue by larsen0815** [AlexandreRouma/SDRPlusPlus#1493]
**Hardware**
- CPU: Intel i7-11800H @ 2.3 GHz
- RAM: 16 GB
- GPU: onboard
- SDR: local

**Software**
- Operating System: Windows 11 x64
- SDR++: 1.2.0, Jul 6 2024

**Bug Description**
When inside a text field (e.g. for Bandwith), shortcuts like the Home button (etc.) should be disabled so the waterfall won't be toggled when I press Home to go to the first char in the text field.

**Steps To Reproduce**
1. Have cursor active inside a text field
2. Enter some text
3. Press Home button

**Comment by AlexandreRouma** [comment]
imgui doesn't have a clean way to do it, not really worth the effort.
