### ISSUE TITLE
SDR++ keeps stopping

### ISSUE THREAD

**Issue by phred01** [AlexandreRouma/SDRPlusPlus#1495]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: 
- RAM:
- GPU: 
- SDR: (Remote or local? If remote, what protocol?)

**Software**
- Operating System: Name + Exact version (eg. Windows 10 x64, Ubuntu 22.04, MacOS 10.15)
- SDR++: Version + Build date (available either in the window title or in the credits menu which you can access by clicking on the SDR++ icon in the top right corner of the software).

**Bug Description**
A clear description of the bug.

**Steps To Reproduce**
1. ...
2. ...
3. ...

**Only If SDR++ fails to lauch or the SDR fails to start:**
Run SDR++ from a command line window with special parameters:
* On Windows, open a terminal and `cd` to SDR++'s directory and run `.\sdrpp.exe -c` (if running SDR++ version 1.0.4 or older, use `-s` instead, though you should probably update SDR++ instead...)
* On Linux: Open a terminal and run `sdrpp -c`
* On MacOS: Open a terminal and run `/path/to/the/SDR++.app/Contents/MacOS/sdrpp -c`
Then, post the **entire** logs from start to after the issue. **DOT NOT truncate to where you *think* the error is...**

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.
Just purchased Laser android tablet with the following specs
OS Android10
storage 16 G
ram 2 G
cpu armv7 processor rev5 (v7) 
cpu architecture 4x 1.51 ghz 4 core
cpu h/w A50 32 bit
![Screenshot_20241015-132718](https://github.com/user-attachments/assets/29eecb2d-8a80-4004-98ac-1771e6424745)
![Screenshot_20241015-132739](https://github.com/user-attachments/assets/9a140501-7855-4096-a76c-06f6f04b155f)
![Screenshot_20241015-132259](https://github.com/user-attachments/assets/385e246a-8dff-4895-89e8-b92a2eda977a)
I have successfully run SDR++ RPI 4 on Dragon OS.....no issues

**Comment by AlexandreRouma** [comment]
The issue template is not filled out. As warned by the template itself, this issue is being closed without review.
