### ISSUE TITLE
OPT_BUILD_PORTAUDIO_SINK is broken: add_library cannot create target "audio_sink" because another target with   the same name already exists.

### ISSUE THREAD

**Issue by yurivict** [AlexandreRouma/SDRPlusPlus#1510]
**Hardware**
Irrelevant.

**Software**
- Operating System: FreeBSD 14.1
- SDR++: 20241022

**Bug Description**
configure fails when -DOPT_BUILD_PORTAUDIO_SINK=ON is added:
```
CMake Error at sdrpp_module.cmake:10 (add_library):
  add_library cannot create target "audio_sink" because another target with
  the same name already exists.  The existing target is a shared library
  created in source directory
  "/usr/ports/comms/sdr++/work/SDRPlusPlus-3982db7/sink_modules/audio_sink".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  sink_modules/portaudio_sink/CMakeLists.txt:6 (include)
```

**Steps To Reproduce**
regular build

**Additional info**
Complete cmake flags:
-DOPT_BUILD_ATV_DECODER:BOOL=false -DOPT_BUILD_BADGESDR_SOURCE:BOOL=true -DOPT_BUILD_DAB_DECODER:BOOL=false -DOPT_BUILD_M17_DECODER:BOOL=false -DOPT_BUILD_NETWORK_SINK:BOOL=true -DOPT_BUILD_PORTAUDIO_SINK:BOOL=true -DOPT_BUILD_AUDIO_SINK:BOOL=true -DOPT_BUILD_AUDIO_SOURCE:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_AUTOGEN_PARALLEL:STRING="7"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -GNinja

**Comment by AlexandreRouma** [comment]
they're not supposed to both be built. The rtaudio based one is for linux and windows, the portaudio one is for MacOS.
