### ISSUE TITLE
PlutoSDR Ehancement

### ISSUE THREAD

**Issue by F5OEO** [AlexandreRouma/SDRPlusPlus#1513]
Rework on PlutoSDR plugin and use (if custom firmware present) CS8 to have higher bandwidth.
Attached a 14Mhz on FM band.
See description of commit : https://github.com/F5OEO/SDRPlusPlus/commit/671464c88cc92e735e9b6be2014114a1758d43bc

![sdrpp14mhz](https://github.com/user-attachments/assets/e6eb39df-0323-4fcf-b2b7-040a107ce7e1)

**Comment by AlexandreRouma** [comment]
So what is the feature request? I don't want to read code.
