### ISSUE TITLE
SNR Meter doesn't work when "Show Waterfall" is toggled off

### ISSUE THREAD

**Issue by KentuckyFriedData** [AlexandreRouma/SDRPlusPlus#152]
SNR meter doesn't seem to update when the waterfall is hidden, didn't know if its intentional but i have included a video of it

https://user-images.githubusercontent.com/31137660/123710670-05a42d80-d824-11eb-8d30-43e292d58500.mp4

**Comment by AlexandreRouma** [comment]
Can replicated, gonna try to fix it.
Thansk for reporting.

**Comment by AlexandreRouma** [comment]
Issue should now be fixed, please try the latest comment and let me know if it's fixed for you.

**Comment by KentuckyFriedData** [comment]
That fixed it, thanks!
