### ISSUE TITLE
More colors for bandplans

### ISSUE THREAD

**Issue by kord1e** [AlexandreRouma/SDRPlusPlus#1520]
**Feature description**

I think it would be useful for custom bandplan makers if there were more colors (categories) in the default config, for example

Government/authorities 
Personal radio services (e.g. CB, PMR446, FRS)
Commercial users
Trunked radio networks
ISM and SRD/LPD433/part 15 equipment

and others if needed.

**Comment by AlexandreRouma** [comment]
Has always been possible, you just need to add color definitions in the config file.
![image](https://github.com/user-attachments/assets/5bf64653-8fb7-43b9-960b-9c5cfa6a70e3)

**Comment by kord1e** [comment]
Anyone who makes new bandplan would benefit from it. Compatibility with SDR# is nice yes but extra colors would not harm that.
