### ISSUE TITLE
Apple blocks nightly SDR++ build for MacOS ARM

### ISSUE THREAD

**Issue by RobinCutshaw** [AlexandreRouma/SDRPlusPlus#1526]
**Hardware**
- CPU: Apple M1 Ultra
- RAM: 64GB
- GPU: 
- SDR: RTL-SDR local

**Software**
- Operating System: MacOS Sonoma 14.6.1
- SDR++: Nightly 2024/11/09

Mac ARM nightly won't run.  Popup says: "SDR++” can’t be opened because Apple cannot check it for malicious software.

**Comment by AlexandreRouma** [comment]
Not a bug, the app just isn't signed because I'm not paying apple hundreds of dollars.
[Apple itself tells you how to get around this.](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac)

**Comment by RobinCutshaw** [comment]
I already pay them for the developer account.  Any interest in a signature?

Robin

**Comment by Terminator0007** [comment]
Any problems to open nightly version for mac OS ARM. Only to accept opening in security section.

**Comment by RobinCutshaw** [comment]
That works.  It is just nice to have trusted software.

**Comment by AlexandreRouma** [comment]
I don't want to rely on someone else's keys, so this is how it will stay.

**Comment by denisbondar** [comment]
> Any problems to open nightly version for mac OS ARM. Only to accept opening in security section.

I have macOS 15.2. Can you tell me how I can launch the application? The operating system offers only to remove the application.

**Comment by johntdavis84** [comment]
Try this:

1. Try to open the app, dismiss the error.
2. Go to System Settings > Privacy and Security.
3. Scroll down until you see Security at the bottom.
4. There should be a message about it having blocked SDR++. There will be a button to open it anyway. You only hav to do this once.
