### ISSUE TITLE
Could not open RTL-SDR: -6

### ISSUE THREAD

**Issue by blul1ghtz** [AlexandreRouma/SDRPlusPlus#1537]
**Software and specs**
- Operating System: Debian 12 live boot
- RTL-SDR V4

**Bug Description**
It just says "Could not open RTL-SDR: -6" in terminal and obviously it isn't reading any data on that device

**Steps To Reproduce**
1. run sdrpp on debian 12

**Additional Information**
i haven't setup the drivers in linux yet i just thought sdr++ automatically did all of that

**Comment by AlexandreRouma** [comment]
you answered your own question, follow the manufacturer's instructions. Literally nothing to do with SDR++.

**Comment by blul1ghtz** [comment]
lol thank you soo much. i found a different source of help anyway...
