### ISSUE TITLE
Why my ui are too big

### ISSUE THREAD

**Issue by KARIM-KING-GAMING** [AlexandreRouma/SDRPlusPlus#1538]
![Screenshot_٢٠٢٤١٢٠١_١١١٩٢٥](https://github.com/user-attachments/assets/3caa1bf6-fe55-4796-a1d2-f39ce536a2b2)
Guys my ui are too big it's normal?

**Comment by AlexandreRouma** [comment]
https://www.sdrpp.org/manual.pdf page 13.

**Comment by KARIM-KING-GAMING** [comment]
> https://www.sdrpp.org/manual.pdf page 13.

Thank you man
