### ISSUE TITLE
Is there an ETA on the next release ?

### ISSUE THREAD

**Issue by luzpaz** [AlexandreRouma/SDRPlusPlus#1542]
I'm aware of the ongoing dev builds but just wondering if there is a oradmap that eventually leads to cutting another release? TIA!

**Comment by AlexandreRouma** [comment]
No, SDR++ is rolling release, I don't tag releases.

**Comment by melroy89** [comment]
If that is the case. Remove all tagged releases: https://github.com/AlexandreRouma/SDRPlusPlus/releases

But to be honest, I would rather see a new tag release still.
