### ISSUE TITLE
please allow to include SDR++ to F-Droid

### ISSUE THREAD

**Issue by Milo078** [AlexandreRouma/SDRPlusPlus#1543]
Hi

please allow to include SDR++ to F-Droid. It will be much more convenient if it will be possible to update all apps in one place.

Visit GitHub and check for updates manually is extremely inconvenient. Moreover to check app hash every time or build it by myself is inconvenient too.

F-Droid will do it automatically and ensure that there is no backdoor or some other differences between source.

Also it will help users to get updates without manually checking github.

F-Droid build everything correctly (I am using it since 2018 and there was NO issues withF-Droid buids) and it will attract more users.

F-Droid allows to add donation link too, so you may have some additional donations.

Regards,

**Comment by AlexandreRouma** [comment]
No.
