### ISSUE TITLE
Nightly for AARCH64 Bullseye build for RPi's

### ISSUE THREAD

**Issue by waltje** [AlexandreRouma/SDRPlusPlus#1546]
Please also generate a 64-bit (aarch64) build for the RPi platforms (for RPi 3B and up), so we can avoid having to install a truckload of 32-bit runtime specifically for this application... my small SD card thanks you ;-)

**Comment by AlexandreRouma** [comment]
duplicated of #1154

**Comment by waltje** [comment]
It now DOES have one for aarch64.
At any rate, I'd be happy to send you an RPi for that if it helps.
--Fred

duplicated of #1154
