### ISSUE TITLE
ka9q-radio support

### ISSUE THREAD

**Issue by helioshk** [AlexandreRouma/SDRPlusPlus#1547]
It would be great if it was possible to connect to ka9q-radio server, which is used more and more widely for a wide range of receivers, but unfortunately lack a comprehensive UI like sdr++ so far.

**Comment by AlexandreRouma** [comment]
Not widely used enough for me to bother create a first-party source module for it, especially since I've never used ka9q-radio.

Anyone else can feel free to write and maintain a source module of their own.
