### ISSUE TITLE
VFO Lock button, and waterfall slide

### ISSUE THREAD

**Issue by cole8085** [AlexandreRouma/SDRPlusPlus#1548]
I'd like to see a VFO and settings lock to avoid accidental frequency changes, or settings from being changed, while allowing something like a sat. tracking plugin to continue making adjustments. : And to be able to click > drag water fall to visually scan rather than jump +- ~SDR base band size.

**Comment by AlexandreRouma** [comment]
duplicate of #1298

**Comment by cole8085** [comment]
> duplicate of #1298

Sorry I thought I searched that one, did you put the click and drag of the waterfall on the to do list?

**Comment by AlexandreRouma** [comment]
Already a thing, just that you have to grab the frequency scale and not the waterfall.

**Comment by cole8085** [comment]
> Already a thing, just that you have to grab the frequency scale and not the waterfall.

Oh ok, I never tried that, thanks.
