### ISSUE TITLE
SDR++ forgets the DAB bandstop option

### ISSUE THREAD

**Issue by OneOfEleven** [AlexandreRouma/SDRPlusPlus#1551]
# WARNING: Filling out the template below is NOT optional. Issues not filling out this template will be closed without review.

FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU: Intel i7 2.7GHz
- RAM: 16GB
- GPU: None (basic DELL laptop)
- SDR: local RSP1B USB

**Software**
- Operating System: Windows 10 Pro Build 1904.vb.release.191206-1406
- SDR++: SDR++ v1.2.1 (Built at 23:10:55, Dec 18 2024)

**Bug Description**
1. SDR++ seems to forget that the DAB bandstop option is ticked and so doesn't enable the RSP1B's DAB notch/bandstop filter, most likely the FM bandstop filter too if it's ticked.

**Steps To Reproduce**
1. Start SDR++ streaming (play butt)
2. Play about with frequency
3. Stop streaming
4. Play with bandwidth changes (say 2MHz to 8MHz)
5. Restart stream (play butt)
6. Even though the DAB filter is ticked SDR++ doesn't appear to enable the filter in the RSP1B (not telling the SDR driver to enable the bandstop filter).
7. While it's streaming, re-tick the DAB filter option to get SDR++ to enable it.
 
**Additional info**
Soon be xmas :(

**Comment by AlexandreRouma** [comment]
Fixed, wait for the new nightly to finish building.
