### ISSUE TITLE
Missing SDRplay support in latest version

### ISSUE THREAD

**Issue by loewal** [AlexandreRouma/SDRPlusPlus#1552]
**Hardware**
- CPU:  Mac Mini M2
- RAM: 8 GB
- GPU: ..
- SDR: local.. last version before installing 1.2.1 worked

**Software**
- MacOs Sequoia
- SDR++:  1.2.1 built on 19-12-2024 both AMD and Arm not wrking; AMD64 worked!

**Bug Description**
SDRplay is not supported anymore. Version before this one worked. Other software like SDRangel recognizes ok.

**Steps To Reproduce**
1. try to load SDRplay module
2. module not present

Where can I find the before-version?
Restored  from Timemachine v1.2.1 built 9 nov. Works!

**Comment by AlexandreRouma** [comment]
Update the SDRplay API to 3.15.
