### ISSUE TITLE
Set up repositories?

### ISSUE THREAD

**Issue by DC7IA** [AlexandreRouma/SDRPlusPlus#179]
Hey there,

how about a repository for the .deb files? Downloading files manually is just annoying. :D

**Comment by AlexandreRouma** [comment]
Hello,

I'm already working on this but since I don't have any ubuntu or debian system I haven't finished it yet.
The SDR++ PPA is already registered.

**Comment by DC7IA** [comment]
Maybe also try to get it into the Ubuntu repositories and other repositories like Debian and FreeBSD. :D 

That'd be cool!

**Comment by AlexandreRouma** [comment]
> Maybe also try to get it into the Ubuntu repositories and other repositories like Debian and FreeBSD.

For this, debian requires you to be "sponsored" by a debian developper and I hate that system.
Not to mention that if it ever gets into the official repos you can be sure it'll never be updated...

For freebsd it might be possible, I know someone who messes with that.

**Comment by AlexandreRouma** [comment]
Seeing how stalled it is (over a year, they're still on 1.0.3), having it on debian probably won't happen, and I'm not gonna waste time with an Ubuntu PPA because I never use ubuntu.
