### ISSUE TITLE
Ubuntu Mate: Shows up in "other" not "hamradio"

### ISSUE THREAD

**Issue by DC7IA** [AlexandreRouma/SDRPlusPlus#184]
SDR++ uses the wrong category on Ubuntu Mate (and possibly other OSes with Mate Desktop?), instead of showing up in the "hamradio" category, it shows up in the category "other".

Not exactly sure if this is the right place, as I don't know what determines what category is used.

**Comment by AlexandreRouma** [comment]
Hello

"hamradio" isn't a standard category. Moreover, if you would chose a non-standard category, "SDR" would make more sense.

**Comment by DC7IA** [comment]
> "hamradio" isn't a standard category. Moreover, if you would chose a non-standard category, "SDR" would make more sense.

Not really, as I already have a lot of stuff in the "hamradio" category, so I don't want a new category consisting only of a single pogram.

Exhibit A:

![Screenshot_2021-07-26_17-39-59](https://user-images.githubusercontent.com/26351852/127017908-027c3a7f-583e-421f-9e10-019f464b6b5c.png)

Exhibit B:

![Screenshot_2021-07-26_17-40-19](https://user-images.githubusercontent.com/26351852/127017925-ae2214dc-3ea6-4a67-9d9a-c110d552e22f.png)

**Comment by AlexandreRouma** [comment]
Are you sure that this is an official category?

**Comment by AlexandreRouma** [comment]
Alright updated the category, lemme know if it works

**Comment by DC7IA** [comment]
> Are you sure that this is an official category?

It exists by default on Ubuntu, just wanted to look at FreeBSD, but my FreeBSD laptop just died when I turned it on, so cannot check right now.

**Comment by shuyuan-liu** [comment]
> Are you sure that this is an official category?

I know this issue is old, but just for documentation, `HamRadio` is a registered category under Additional Categories in the freedesktop.org Desktop Menu Specification: https://specifications.freedesktop.org/menu-spec/latest/apas02.html
