### ISSUE TITLE
[question] How to enable modules..?

### ISSUE THREAD

**Issue by DC7IA** [AlexandreRouma/SDRPlusPlus#185]
Let's say I want to enable `weather_sat_decoder`, how can this be done?

I don't see a menu and there are no man pages. :D

**Comment by AlexandreRouma** [comment]
the `weather_sat_decoder` as mentioned [here](weather_sat_decoder), is unfinished. I wouldn't recommend using it at the moment.

If you still wish to enable another module, you need to add a module instance in the config (in the `moduleInstance` parameter). Make sure to respect json synthax.
