### ISSUE TITLE
Glfw Error 65543: GLX

### ISSUE THREAD

**Issue by Lesprilibre** [AlexandreRouma/SDRPlusPlus#191]
hi !

I have just try to intall your sdr programm on my laptop, everythnig running fine during install, but when i try to start it, i receive the following error :

Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig

I suppose that the problem is due to Mesa driver or osbolete graphic card driver ?

**Comment by Lesprilibre** [comment]
I thnik i got the answer my GLEW version seems to be out of date :+1: 
---------------------------
    GLEW Extension Info
---------------------------

GLEW version 2.1.0
Reporting capabilities of display , visual 0xe4
Running on a Mesa DRI Intel(R) HD Graphics (ILK) from Intel Open Source Technology Center
OpenGL version 2.1 Mesa 20.2.6 is supported

the version should be 3.x ?

**Comment by starvald** [comment]
yeah you need 3.x

**Comment by Lesprilibre** [comment]
It's a laptop... Obviously, I won't update it..  😭

**Comment by Lesprilibre** [comment]
I'ill give a try on the Rapi, if the version does exist, thanks !

**Comment by starvald** [comment]
i've ran it on the raspberry pi 4 but you'll need to self compile and alter file.

core/src/core.cpp line 278. change to 

const char* glsl_version = "#version 300 es";
glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API)
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);

then compile.
