### ISSUE TITLE
Check and Fix issue(s) found with CppCheck

### ISSUE THREAD

**Issue by bvernoux** [AlexandreRouma/SDRPlusPlus#196]
Check and Fix issue(s) found with CppCheck
https://github.com/danmar/cppcheck
It can be used in the workflow too https://github.com/marketplace/actions/cppcheck-action or maybe something better like https://github.com/danmar/cppcheck/blob/main/.github/workflows/codeql-analysis.yml

It will be even better (for mid/long term) to add some workflow to check Cpp for code bug/security issues in code ...

**Comment by AlexandreRouma** [comment]
Iirc last time I ran it through a few weeks ago it didn't find anything

**Comment by bvernoux** [comment]
When I have launched it (manually) I have found mainly some optimizations and minor stuff(related to portability...) but it is always interesting to apply them when they bring something, I think codeql is even better/complementary to check other potential code vulnerabilities...
