### ISSUE TITLE
Mac build should be an app bundle

### ISSUE THREAD

**Issue by orryverducci** [AlexandreRouma/SDRPlusPlus#197]
Currently the install package created in the Mac build on GitHub Actions installs SDR++ to `/usr/local/bin` and requires the external dependencies to be already installed.

This is different to most GUI applications on the Mac platform, which are usually distributed as app bundles installed to `/Applications`, with the external dependencies included in the bundle. As such the current build is not user friendly, as SDR++ doesn't appear as an icon in Launchpad or the Applications folder as Mac users would expect, and requires dependencies to be installed (e.g. via Homebrew) which most Mac users won't expect or be familiar with.

The SDR++ build for Mac should be changed to create and distribute an app bundle, which would bring it in line with other Mac GUI apps and user expectations. This would also resolve #189.

I've made an attempt myself at modifying CMakeLists to build a bundle and copy the dependencies. It works but it doesn't copy the plugins or shared files (e.g. icons), and CMake is not my area of expertise so I don't know the best way to resolve it. It might be helpful to someone else, so it's here for anyone who wants to take a look: https://github.com/orryverducci/SDRPlusPlus/tree/mac-build-tweaks

More info about app bundles can be found at: https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AboutBundles/AboutBundles.html

**Comment by AlexandreRouma** [comment]
I switched to bundles a while back, forgot to close
