### ISSUE TITLE
Rewrite SDR++ in Rust for 2.0 (renaming to SDR-rs ?)

### ISSUE THREAD

**Issue by aosync** [AlexandreRouma/SDRPlusPlus#199]
I believe the project could benefit greatly from a rewrite in a language that is :rocket: blazing :zap: fast :bullettrain_side: and memory :computer: safe :police_officer: 
[rust](https://www.rust-lang.org/).

**Comment by STBoyden** [comment]
Yes 100%, no meme

**Comment by Tyrving** [comment]
I wholeheartedly agree. This needs to happen ASAP.

**Comment by STBoyden** [comment]
Why use C with Classes when you can use a better language as a whole?

**Comment by JackHunt** [comment]
Strong disagree. What would be the point in this particular case? What benefits would a complete rewrite of this software yield beyond the novelty of using a trendy language?

Also, @STBoyden it has been a very long time since C++ can be considered simply "C with classes".

**Comment by STBoyden** [comment]
> Strong disagree. What would be the point in this particular case? What benefits would a complete rewrite of this software yield beyond the novelty of using a trendy language?
> 
> Also, @STBoyden it has been a very long time since C++ can be considered simply "C with classes".

I wouldn't worry mate, this was a joke issue created by a few people who know @AlexandreRouma.
