### ISSUE TITLE
The highest zoom level is unnecessarily large

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#200]
Hi! The highest zoom level zooms so much that each bin in the spectrogram is some 80 pixels wide, which I can't think of a use for. Would you be able to decrease the max zoom level a bit?

![Screenshot from 2021-08-02 11-25-20](https://user-images.githubusercontent.com/41851763/127800998-c745a843-84fd-484b-834d-10ba3a71aef6.png)

**Comment by AlexandreRouma** [comment]
Hello,

I use this myself when I need to check precise FFT bins. What I'll do is make the slider easier to use without going into full zoom.
