### ISSUE TITLE
macOS audio freeze

### ISSUE THREAD

**Issue by mehdideveloper** [AlexandreRouma/SDRPlusPlus#206]
Hey. I just built the latest version from source (v1.0.0) and it works without issues.
One issue I have is when I stop the SDR, the last milliseconds of the audio that was being played, gets stuck in a loop and plays again and again. I either need to click on the play button again to continue, or to close the app.
First I built the app without the portaudio options enabled in the cmake, and then I enabled the new portaudio and built again but the same problem still happens.
Here's my setup: macOS 11.5.1, tested with AirSpy R2 at 2.5MHZ, on WFM 200KHZ demod.

**Comment by AlexandreRouma** [comment]
Hello,

Make sure you use the following arguments in the cmake command to switch to the MacOS compatible audio sink:
`-DOPT_BUILD_PORTAUDIO_SINK=ON -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON`

Make sure you've got portaudio installed.
