### ISSUE TITLE
Enabling Soapy source on macOS makes the app freeze

### ISSUE THREAD

**Issue by mehdideveloper** [AlexandreRouma/SDRPlusPlus#207]
Hey. Compiling the last version from source on macOS works.
If I enable the Soapy source in the cmake, the app freezes in the startup dialog.
Here's the last log lines:

> [2021-08-02 13:14:50.187] [error] Could not intiatialized the SDRplay API. Make sure that the service is running.
> [2021-08-02 13:14:50.187] [info] Initializing SoapySDR Source (soapy_source)
I have also attached a screenshot.
FYI, the SoapySDR is installed on my machine and is available in the PATH and also works (finds the connected SDRs, also works in gqrx)
<img width="1392" alt="Screenshot 2021-08-02 at 13 14 57" src="https://user-images.githubusercontent.com/12119776/127853666-9b8c25b5-0e0a-4cd6-ae0c-d2b954ac488e.png">

**Comment by AlexandreRouma** [comment]
Hello,

The soapy source isn't supported on MacOS. Unless you need it for a USRP or soundcard SDR I'd suggest completely removing it by defeling the dylib
