### ISSUE TITLE
[Feature]Spectrum averaging

### ISSUE THREAD

**Issue by Radiomix2000** [AlexandreRouma/SDRPlusPlus#212]
Thank you for your software! It becomes more and more awesome.
Can I ask, how to apply averaging to spectrum plot?
If there is no such feature, is any chances to see it in future releases?

**Comment by AlexandreRouma** [comment]
Hello,

This is a planned feature is denoted in https://github.com/AlexandreRouma/SDRPlusPlus/projects/2

**Comment by 0xCoto** [comment]
Any updates on this? Definitely a must-have in my opinion! 🙂

**Comment by AlexandreRouma** [comment]
it's in the todo list but I've been more focused on bugfix lately

**Comment by AlexandreRouma** [comment]
has been implemented. See "FFT Smoothing" and "FFT Smoothing Speed" options in the "Display" menu.

**Comment by helioshk** [comment]
Can the FFT smoothing also be applied to the waterfall?

**Comment by KubaPro010** [comment]
@helioshk No, there's no need for waterfall smoothing at all

**Comment by AlexandreRouma** [comment]
Feel free to smear some vaseline on your screen if you'd like smoothing on the waterfall. It would be a nonsensical feature...

**Comment by helioshk** [comment]
It would increase the visual SNR for persistant signals. (Average of noise gets lower while the average of the signal stays the same)

**Comment by AlexandreRouma** [comment]
Just increase the FFT size and decrease the FFT rate. It'll integrate over a long time

**Comment by helioshk** [comment]
It doesn't seem to go below 1/s

**Comment by helioshk** [comment]
I think it isn't integrating at all. Or am I doing something wrong?
I see no difference between FFT framerate of 1 vs 30, apart from all levels being a bit lower. But the visual SNR stays the same:
![diff](https://github.com/user-attachments/assets/7ef40060-4b76-4080-b5c7-becac5601a4a)
