### ISSUE TITLE
Frequency Manager: minor cosmetic issue

### ISSUE THREAD

**Issue by limaunion** [AlexandreRouma/SDRPlusPlus#213]
Hi! I'm running a release from a few days ago under Manjaro Linux. Superb application improving every day!

This is just a minor cosmetic issue, low priority probably.

From the 'Frequency Manager' if I click 'Select displayed lists' a pop-up window will appear. The weird  behaviour is that you are forced to chose some option, but the ESC key to cancel won't work and if I click anywhere in the screen the pop-up window will be redrawn at that place. 

Keep up the great work!

**Comment by AlexandreRouma** [comment]
Hello,

If you wish to not select any option, just press "ok".
the option showed are their current state (aka checked if displayed, unchecked if not displayed)

Will consider adding a shortcut if more people find it annoying

**Comment by limaunion** [comment]
Thanks!
