### ISSUE TITLE
tuning by click - strange behaviour

### ISSUE THREAD

**Issue by iu1mrd** [AlexandreRouma/SDRPlusPlus#222]
just installed v 101
issue: let say I'm on 14.250.000 and I see a signal at 14.290.00. I click on the signal. Now the vfo is 14.661.000

I'm an sdr# user. 
This sdr++ seems very promising.
thanks for your work

**Comment by iu1mrd** [comment]
I forgot to say the issue is about "center tuning mode"
"free tuning mode" seems ok.

**Comment by AlexandreRouma** [comment]
Hello,

Yes this is indeed a duplicate opf #136 

I've yet to implement that part of the code. In the mean time I'd recommend using center tuning only when tuning with the frequency selector rather than clicking in the waterfall.
