### ISSUE TITLE
airspy missing symbol

### ISSUE THREAD

**Issue by sgoudelis** [AlexandreRouma/SDRPlusPlus#230]
Good evening,

I am getting this when starting sdrpp. Any ideas what I should try?

```
sdrpp: symbol lookup error: /usr/lib/sdrpp/plugins/airspy_source.so: undefined symbol: airspy_list_devices
```

**Comment by AlexandreRouma** [comment]
Hello,

Your version of libairspy is outdated, please update to a more recent version.
