### ISSUE TITLE
Ubuntu libvolk.so.2.2 missing

### ISSUE THREAD

**Issue by JosephTheTank13** [AlexandreRouma/SDRPlusPlus#231]
Hello! I installed all the dependencies from the list on the install instructions page, but when I try to run sdr++ it gives this error:
`sdrpp: error while loading shared libraries: libvolk.so.2.2: cannot open shared object file: No such file or directory` 

libvolk2-dev is version 2.4.1-2, so maybe it's a version difference problem? Is SDR++ looking for a specific version of SDR++ that isn't what I have? 
I installed the "sdrpp_ubuntu_focal_amd64.deb" Since I'm on Pop OS 21.04 which is ubuntu based.

**Comment by AlexandreRouma** [comment]
Hello,

You have downloaded the wrong version,  PopOS 21.04 is based on Ubuntu 21.04 (Hirsute)
You need to download sdrpp_ubuntu_hirsute_amd64.dev

**Comment by JosephTheTank13** [comment]
My bad! Thank you for the quick response!
