### ISSUE TITLE
No reception when free tuning (left/right arrows icon) under direct sampling using RTL-SDR or NESDR

### ISSUE THREAD

**Issue by cosmopotamian** [AlexandreRouma/SDRPlusPlus#232]
For some reason, when using direct sampling mode with any RTL2832U-based SDRs, no reception is possible when free-tuning (left/right arrows icon). Only when center tuning is toggled (cross hair icon) can I receive and see spikes on the spectrum.

**Comment by AlexandreRouma** [comment]
I suspect user error or an old bug that has more than likely been fixed by now. Reopen with more details if not.
