### ISSUE TITLE
LimeSdr does not work correctly (no signal)

### ISSUE THREAD

**Issue by netdoggy** [AlexandreRouma/SDRPlusPlus#237]
I haven't been able to quickly find exactly what the problem is (technically). However, the waterfall looks like a gain of 0 and does not change in any way when you change the gain or antenna channel.

sdrpp v.1.0.2 win64

**Comment by AlexandreRouma** [comment]
1) is the input set to LNAW
2) Raise the min value

A screenshot would be useful to see what the error is.

**Comment by netdoggy** [comment]
While I was taking screenshots, I did some research and it turned out that it is the Ch2 channel that does not work. For technical reasons I use the default CH2 for reception.

I switched to CH1 and it looks like a signal appeared. So the problem is probably in the choice of the antenna channel.

**Comment by netdoggy** [comment]
![image](https://user-images.githubusercontent.com/3543540/128768845-597fd6d4-0b2e-4050-9430-df20f169fc43.png)
![image](https://user-images.githubusercontent.com/3543540/128768855-e9be0616-7bac-4127-bee5-1fa54ce04e3d.png)

**Comment by netdoggy** [comment]
here :) 
https://github.com/AlexandreRouma/SDRPlusPlus/blob/fa9347f2eed756c31e339291d343526f069e5186/limesdr_source/src/main.cpp#L338

**Comment by AlexandreRouma** [comment]
I can change that but I have no way to test it (I only have a LimeSDR mini)

Can you check that `0` switching to `_this->chanId` fixes the issue?

**Comment by netdoggy** [comment]
the problem is probably here https://github.com/AlexandreRouma/SDRPlusPlus/issues/237#issuecomment-895553624

**Comment by netdoggy** [comment]
Unfortunately, I'm not ready now build it, but I'll check how the fix will be :)

**Comment by AlexandreRouma** [comment]
Fixed it in the latest 1.0.3 release

**Comment by netdoggy** [comment]
Cool, it works, thanks.
