### ISSUE TITLE
sdrpp won´t start - won´t pass "Initializing SoapySDR Source" on Ubuntu 21.04

### ISSUE THREAD

**Issue by chexclaim** [AlexandreRouma/SDRPlusPlus#240]
Hello,  I am trying to run SDR++ on Ubuntu 21,04. Installation went no problems but when I run the app it won´t pass the "Initializing SoapySDR Source" stage. And Ubuntu keeps asking if I would like to wait or force quit.
Thank you.

**Comment by AlexandreRouma** [comment]
Hello,
this is likely related to [this issue](https://github.com/AlexandreRouma/SDRPlusPlus#hash-collision-error-when-starting).

**Comment by chexclaim** [comment]
Yes! I ran:
apt remove soapysdr*

and the it started fine.  I DIDN´T do anything else. I did not install anything else but seems to work. 
My hardware is: Realtek RTL2832 SDR

Thank you.

**Comment by AlexandreRouma** [comment]
Yes that's not an issue, only install soapysdr if you actually need it.

SDR++ has dedicated support for the RTL-SDR so you won't need soapy.
