### ISSUE TITLE
FR: Addon architecture?

### ISSUE THREAD

**Issue by tubalainen** [AlexandreRouma/SDRPlusPlus#242]
Hi all fantastic devs!

This is such a welcome addition to the SDR world! Thank you guys so much! The SDRPlusPlus is so much more "hardcore" and "back to basics" than the other software's out there.

How would we as a community go about expanding the capabilities of SDR++?
There are some things I personally do miss such as freq scanner and integrations/addons for digital mode decoding. Yes yes, One can always pipe the audio to the virtual cable, but it is not always as convenient.

So what are your thoughts on an addon architecture? Would it even be possible to make it compatible with existing SDR# addons?

The latest release runs great on my Windows 10 machine.

**Comment by AlexandreRouma** [comment]
SDR++ is already fully modular, so anyone can write any part of the software as a plugin.
The radio is its own module, the recorder too, every source and sink is its own module, etc...
