### ISSUE TITLE
Audio cut out MacOS 11.4

### ISSUE THREAD

**Issue by chrjohns** [AlexandreRouma/SDRPlusPlus#248]
Very grateful to have this app working natively on the Mac.  Beautiful audio when SDRPP is the frontmost window, but audio cuts out momentarily and intermittently when transitioning to another app or window or when other operations unrelated to SDRPP take resources.  It settles back to smooth sound pretty quickly.

**Comment by AlexandreRouma** [comment]
which build are you using? built yourself or an official release?

**Comment by chrjohns** [comment]
1.03 - you helped me build it in discord (northcountry)

**Comment by AlexandreRouma** [comment]
I see,
I'll have to try it out again, don't have access to a mac anymore for now

**Comment by chrjohns** [comment]
Happy to help test things if you need it.

**Comment by AlexandreRouma** [comment]
Likely fixed in the nightly, please reopen if not.
