### ISSUE TITLE
Spyserver issue & suggestion

### ISSUE THREAD

**Issue by pbij2001** [AlexandreRouma/SDRPlusPlus#264]
When the spyserver is locked in frequency range, the sdrpp VFO still tunes outside the spyserver restricted range, losing correct frequency correlation.

-suggestion: make the spyserver IP field compatible with the spyserver URL format.
sdr://IP:port (all in one field)
This way it is easier to cut/copy from the spyserver map website in a single action
There is a ready-to-go "clipboard copy" on the website available.

**Comment by AlexandreRouma** [comment]
That is a known issue and is the case for all SDR drivers, SDR++ doesn't currently have a way of limiting the frequencies the user can tune to.

As for the URL, I'll have to see if I can just add an automated decoding of the "spyserver" format, I personnaly really don't like that formatting so I think allowing to paste it into the host field and be automatically decoded would be a better option

**Comment by pbij2001** [comment]
Manual entry is better in general.

Copy and decode would just be handy for the Spyserver net.
![Screenshot 2021-08-17 at 21 09 35](https://user-images.githubusercontent.com/88380553/129786287-56758d6d-7050-4b3c-9ee4-d2cef5dbb65f.png)

**Comment by AlexandreRouma** [comment]
Won't implement in the end. I wouldn't recommend using the spyserver source anyway due to the limitations of the "open source" spyserver client.

I recommend switching to SDR++ Server.
