### ISSUE TITLE
[Feature] Mouse wheel zoom

### ISSUE THREAD

**Issue by arkhnchul** [AlexandreRouma/SDRPlusPlus#281]
patch in attachment, it allows to change zoom level with mouse wheel while holding Shift button.

short demonstration: https://youtu.be/hoT2pMBhOsA

[0001-mouse-wheel-zoom-implementation.patch.txt](https://github.com/AlexandreRouma/SDRPlusPlus/files/7020904/0001-mouse-wheel-zoom-implementation.patch.txt)

**Comment by AlexandreRouma** [comment]
Hello,

Thanks for submitting this patch but unfortunately I think this is quite a dirty way of implementing this feature, I'll see if I can add this to my todo list.

**Comment by arkhnchul** [comment]
maybe i can remade it in more appropriate way?

**Comment by AlexandreRouma** [comment]
After reflection I won't be adding that feature. I scrolling (including with modifiers) will be reserved for other things.
