### ISSUE TITLE
SpyServer wrong frequency

### ISSUE THREAD

**Issue by randomtechkid** [AlexandreRouma/SDRPlusPlus#296]
I copied & pasted the correct URL and port but the connect button won't work.
Typing doesn't help either. Maybe it's a faulty GUI.

**Comment by randomtechkid** [comment]
I deleted the sdr:// prefix in the URL area, it worked but now the tuner is still in 100MHz while the radio is on another frequency.

**Comment by AlexandreRouma** [comment]
Some spyservers are locked onto a frequency. This can be the case when another use is already using it or if the owner has decided to lock it down.

SDR++ currently doesn't have a way of locking or setting the selectable frequency on the waterfall so in those cases, ti'll result in frequencies that don't match.
