### ISSUE TITLE
[Cosmetic] Text on labels and controls in UI are slightly offset

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#332]
They don't look _very_ bad, but each label still appears slightly offset from the slider / dropdown next to it. I might try fixing this myself.

![Screenshot from 2021-08-31 10-11-44](https://user-images.githubusercontent.com/41851763/131432735-8eb1311d-7e5f-4ec5-8cac-162d6eaf2a55.png)

**Comment by AlexandreRouma** [comment]
this is a known issue, have been a bit too lazy to fix it since it mostly doesn't really affect the usage and most people don't notice it until it's pointed out

**Comment by AlexandreRouma** [comment]
Alright, started working on a fix
![image](https://user-images.githubusercontent.com/17126412/131531794-fff6ed7f-8ce2-4bc9-8df4-5830bec4abff.png)
