### ISSUE TITLE
Feature request: Soundcard I/Q input

### ISSUE THREAD

**Issue by batica81** [AlexandreRouma/SDRPlusPlus#345]
Maybe it is there but I cannot find it? It is a very useful feature for older SDRs and all kind of experiments.

**Comment by AlexandreRouma** [comment]
Hello,

Currently there is indeed no audio source, in the mean time you can use the soapysdr source which supports soundcard input

**Comment by batica81** [comment]
Good to know, I will try that, thanks.

**Comment by jyrts** [comment]
with soapysdr sound input there are two problems:
1. You can not specify channel mode. How to use IQ audio input?
2. If you have multiple audio devices for different bands on you soapy remote server then you can not specify wich soundcard to use. How to specify device_id?

**Comment by AlexandreRouma** [comment]
@bubnikv I appreciate the gesture but there is no need, the audio source can be implemented using anything as input. Control of the frequency will be done through the rigctl client.

**Comment by AlexandreRouma** [comment]
Implemented

**Comment by batica81** [comment]
Works well with QDX radio controlled by flrig, also with any old SDR connected to Asus USB soundcard! Thank you!

**Comment by arampak** [comment]
> Implemented

I am unable to find a way to use the radio that has an IQ output connected to the USB sound card input in on my Mac. What are the particular steps to make SDR++ recieve the IQ data from a sound card?

**Comment by mabartibin** [comment]
Yes, how is this implemented?  None of the listed sources looks like it does this?

**Comment by AlexandreRouma** [comment]
it's disabled on macos due to rtaudio issues.

**Comment by mabartibin** [comment]
Aha, that explains it, thank you!
