### ISSUE TITLE
IQ File Player - any chance for other formats like SDR#

### ISSUE THREAD

**Issue by jeffreypkelly** [AlexandreRouma/SDRPlusPlus#357]
I spectrum capture @(240000hz) the 2 meter Amsat satellites and Meteor M2 using rtl_sdr IQ format and convert them to SDR# .wav format using iqToSharp for smaller size and playback in SDR#.

Is there any way the SDR# IQ file format can be supported in sdr ++?
Currently they load and try to play back in sdr ++ ~twice as fast and they seem to mirror the same signal on either side of the center DC line.

The files are captured, converted and auto uploaded to GDrive if you wanted to test:
https://drive.google.com/drive/folders/1fdqCko4e5XkTYRWZS5oJX6sz51CdhKPc?usp=sharing

TY!

**Comment by AlexandreRouma** [comment]
will group this with #129, follow that issue for updates instead
