### ISSUE TITLE
SDRPlay Issue

### ISSUE THREAD

**Issue by Charlier26** [AlexandreRouma/SDRPlusPlus#358]
I have installed v1.03 on Windows 10-64bit, and while when I select SDRPlay as the radio, it recognizes my RSP1A, and lists its serial number, below that in red it says "No device available". What am I doing wrong. If I try to start the radio, it shows no signals, and then no longer recognizes the receiver.

**Comment by AlexandreRouma** [comment]
Make sure no other software is using your RSP1A. A reboot can help.

**Comment by Charlier26** [comment]
I don't have any other program running, but DO have SDRPlay's API server running....could that be conflicting with it?

**Comment by AlexandreRouma** [comment]
If by the API server you mean the API service, it has to be running for SDR++ to work.
Only advice I can give to to uplug/replug the device and reboot

**Comment by Charlier26** [comment]
OK, I'll try that

**Comment by Charlier26** [comment]
I reloaded the API service, and I got it running......but it sure is deaf. In SDRUno, I get plenty of signals.  The RF Gain is all the way up, and the IF gain isn't available to adjust but it looks like it is at max.

**Comment by AlexandreRouma** [comment]
either user error or early bug, try the nightly
