### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by arcreigh** [AlexandreRouma/SDRPlusPlus#359]
P25 Phase 2 And POCSAG

POCSAG direct to discord would be awesome for keeping in the loop with pager events around your locality and could be used as an early warning of events in your area. Would LOVE to see this functionality added!

**Comment by AlexandreRouma** [comment]
Hello,

POCSAG to discord would be a bit out of scope imo.

In the mean time, you can simply use a 13KHz NFM demodulator with a network sink and decode the pocsag with multimon-ng, then you can use a script to send it to discord.

By the way, please make sure that this is legal in your area, sending pager data straight to a public service is generally considered illegal in most places.
