### ISSUE TITLE
Wrong word in french translation

### ISSUE THREAD

**Issue by ClaudeMa** [AlexandreRouma/SDRPlusPlus#362]
VHF  Aviation Radio Bands      show "Aviation voie" in french translation.    need to be "Aviation voix" 
voix is voice
voie is way

not found where translation file are located
                                                                 
![srd++](https://user-images.githubusercontent.com/2773730/133668246-f8ad9d73-420d-44a2-b794-d24673cda657.png)

**Comment by AlexandreRouma** [comment]
Hello,

I'll ask the author of the bandplan what he meant by it and correct if needed.

**Comment by AlexandreRouma** [comment]
Alright fixed in the latest commit
