### ISSUE TITLE
No UI scaling feature?

### ISSUE THREAD

**Issue by jaredkaragen** [AlexandreRouma/SDRPlusPlus#374]
I use a 4K monitor, with windows scaling for apps to not be tiny.

It seems SDR++ is still showing as if my desktop UI scaling was off;  so I would request some sort of UI scale factor that you can adjust would be an excellent add to the app.  The FFT and spectrum don't seem to need it, but the main UI bar on the left. 

I simply can not read anything from the app unless I change my desktop resolution or get up against the screen.

Not exactly a bug, but more of a feature request for creature comfort.

**Comment by AlexandreRouma** [comment]
Scaling isn't currently supported but it's a planned feature

**Comment by steve-m** [comment]
Same issue here, I can barely read the text on my 4K screen.

**Comment by AlexandreRouma** [comment]
it's being worked on at the moment since it was required to make the thing usable on android

**Comment by AlexandreRouma** [comment]
UI scaling was added and is now available
