### ISSUE TITLE
M17 mode decoder

### ISSUE THREAD

**Issue by sp5wwp** [AlexandreRouma/SDRPlusPlus#378]
It'd be really nice to have M17 decoder in your software.

In case you haven't heard about it already, it's a fully open-source digital communication mode made by hams.
Our website is m17project.org, Twitter: twitter.com/m17_project

**Comment by AlexandreRouma** [comment]
Hello,
If the phy and codec layers are relatively simple it should be a quick addition.

Could you provide a few IQ recordings of the protocol (if possible of different SNR and containing most features of the protcol)?
I don't think I own hardware that can use that mode

**Comment by sp5wwp** [comment]
If you have a Raspberry Pi (even Zero) you can use [rpitx by F5OEO](https://github.com/F5OEO/rpitx) to transmit M17. We can provide a baseband sample for you to experiment.

[Contact us directly](https://m17project.org/contact/) for more details.

**Comment by sp5wwp** [comment]
There's [coder/decoder ready](https://github.com/mobilinkd/m17-cxx-demod), written in C++. Take a look :-)
Also, check the [specification](https://m17-protocol-specification.readthedocs.io/en/latest/), it's pretty straightforward.

**Comment by AlexandreRouma** [comment]
Alright I'll give it a try with RPi TX, hopefully my currect clock recovery algo (M&M) is good enough for packet operation.
I've joined the matrix and the discord

**Comment by AlexandreRouma** [comment]
Added in this release
