### ISSUE TITLE
Crash after opening plutosdr_source

### ISSUE THREAD

**Issue by DL5SMB** [AlexandreRouma/SDRPlusPlus#38]
Hi,

after having everything compiled, I tried to open a stream with my pluto, but as soon as I hit the play button,
everything crashes.

In the log I can find various warnings and errors regarding ALSA, but there seems also to be a problem with the plutosdr_source.co

> sascha@think:~/SDRPlusPlus/build$ ./sdrpp 
> [2020-12-13 16:51:54.038] [info] SDR++ v0.2.5_alpha
> [2020-12-13 16:51:54.039] [info] Loading config
> [2020-12-13 16:51:54.654] [info] Loading icons
> [2020-12-13 16:51:54.662] [info] Loading band plans
> [2020-12-13 16:51:54.668] [info] Loading band plans color table
> [2020-12-13 16:51:54.678] [info] Loading modules
> [2020-12-13 16:51:54.678] [info] Loading ./radio/radio.so
> [2020-12-13 16:51:54.693] [info] Loading ./recorder/recorder.so
> [2020-12-13 16:51:54.710] [info] Loading ./soapy_source/soapy_source.so
> [2020-12-13 16:51:54.727] [info] Loading ./rtl_tcp_source/rtl_tcp_source.so
> [2020-12-13 16:51:54.743] [info] Loading ./audio_sink/audio_sink.so
> [2020-12-13 16:51:54.759] [info] Loading ./plutosdr_source/plutosdr_source.so
> [2020-12-13 16:51:54.776] [info] Initializing Audio Sink (audio_sink)
> [2020-12-13 16:51:54.792] [info] Initializing PlutoSDR Source (plutosdr_source)
> [2020-12-13 16:51:54.809] [info] PlutoSDRSourceModule 'PlutoSDR Source': Instance created!
> [2020-12-13 16:51:54.809] [info] Initializing RTL-TCP Source (rtl_tcp_source)
> [2020-12-13 16:51:54.826] [info] Initializing Radio 1 (radio)
> [2020-12-13 16:51:54.900] [info] Initializing Radio 2 (radio)
> [2020-12-13 16:51:54.957] [info] Initializing Recorder (recorder)
> [2020-12-13 16:51:54.957] [info] Initializing SoapySDR Source (soapy_source)
> [INFO] [UHD] linux; GNU C++ version 8.2.0; Boost_106700; UHD_3.13.1.0-3
> [2020-12-13 16:51:57.424] [info] Setting sample rate to 44100.0
> [2020-12-13 16:51:57.425] [info] SoapyModule 'SoapySDR Source': Instance created!
> [2020-12-13 16:51:57.426] [info] PlutoSDRSourceModule 'PlutoSDR Source': Menu Select!
> [2020-12-13 16:51:57.426] [info] PlutoSDRSourceModule 'PlutoSDR Source': Tune: 0.0!
> ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
> ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
> [2020-12-13 16:51:58.039] [warning] ConfigManager locked, waiting...
> [2020-12-13 16:51:58.106] [info] Audio device open.
> [2020-12-13 16:51:59.039] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:00.039] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:01.040] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:02.040] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:03.040] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:04.040] [warning] ConfigManager locked, waiting...
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
> [2020-12-13 16:52:04.515] [info] Audio device open.
> [2020-12-13 16:52:04.516] [info] PlutoSDRSourceModule 'PlutoSDR Source': Tune: 96500000.0!
> [2020-12-13 16:52:04.516] [info] Ready.
> **./sdrpp: symbol lookup error: ./plutosdr_source/plutosdr_source.so: undefined symbol: iio_create_context_from_uri**
> `

EDIT: Sorry for all the edits, but I had to find out first how to format logs correctly

**Comment by AlexandreRouma** [comment]
Hi,
the plutosdr module isn't currently compatible with linux because of some bugs,
I recommend you use the SoapySDR source while the bug is getting fixed.

**Comment by AlexandreRouma** [comment]
Bug fixed
