### ISSUE TITLE
Native Apple Silicon Support

### ISSUE THREAD

**Issue by bvogt3000** [AlexandreRouma/SDRPlusPlus#381]
First, thanks for the new SDR program! I am a mac guy and love SDR radio, so it is nice to finally see a new SDR program come to the Mac. Right now SDR++ is running through Rosetta on my m1 Mac Mini, it works rather well. I am still wondering though if there is a plan to have native Apple Silicon support?

**Comment by AlexandreRouma** [comment]
Hello,
Unfortunately don't own (and can't afford) any mac so I won't be able to add support for apple silicon myself.

**Comment by bvogt3000** [comment]
Ok, I just figured I would check. Nonetheless thanks for the SDR program! It still runs great through Rosetta.

**Comment by l-gothberg** [comment]
> Hello, Unfortunately I don't own (and can't afford) any mac so I won't be able to add support for apple silicon myself.

What if you could?

**Comment by AlexandreRouma** [comment]
> What if you could?

Unless \<insert price of a M1 machine here\> magically appears in my bank account, I can't
I'm just a student, I don't have the cash nor the need for a brand new apple device
Even used they're almost MSRP anyway...

Tried emulation for intel macs and that kinda works but I can't actually start the software since it needs OpenGL...

**Comment by l-gothberg** [comment]
> > What if you could?
> 
> Unless <insert price of a M1 machine here> magically appears in my bank account, I can't I'm just a student, I don't have the cash nor the need for a brand new apple device Even used they're almost MSRP anyway...
> 
> Tried emulation for intel macs and that kinda works but I can't actually start the software since it needs OpenGL...

Check your email.

**Comment by AlexandreRouma** [comment]
Checked and responded 👍

**Comment by n2iw** [comment]
> First, thanks for the new SDR program! I am a mac guy and love SDR radio, so it is nice to finally see a new SDR program come to the Mac. Right now SDR++ is running through Rosetta on my m1 Mac Mini, it works rather well. I am still wondering though if there is a plan to have native Apple Silicon support?

If you know how to compile, you can compile SDR++ from source. I compiled it on my M1 mini, and it runs natively. When I got sometime, I'll try to learn how to package Mac Applications and help provide ready to use application. I'm a software engineer, but I write web applications, C/C++ is not my strength.

**Comment by AlexandreRouma** [comment]
Apple silicon is supported but sitll haven't got hardware. no reason for it to not work so I'll close.
