### ISSUE TITLE
How reset configuration following crash?

### ISSUE THREAD

**Issue by K0HYD** [AlexandreRouma/SDRPlusPlus#391]
I was running fine with airspy on 1.03 and with both airspy and airspyhf modules with1.04. Then I tried to use spysever. Since I set it as a source sdrpp crashes on launch and I don't know how to get rid of the spyserver setting so I can use sdrpp again. When I tried to configure spyserver I couldn't type in the ip address field. I like this program and signed up with Pateron. Any suggestion appreciated.

**Comment by K0HYD** [comment]
MacOS builds. Running Monterey (MacOS 12, Beta 7). Forgot to note this in initial message.

**Comment by AlexandreRouma** [comment]
Hello,
Could you send startup logs to see when it crashes?
You can reset the configuration by deleting `~/.config/sdrpp` but don't do it now, I'd like to know why it crashes and fix the issue.
Would be nice if you could zip up that folder and send it here so I can have a look at the config files causing the issues

**Comment by K0HYD** [comment]
[ConfigArchive.zip](https://github.com/AlexandreRouma/SDRPlusPlus/files/7249613/ConfigArchive.zip)
[TroubleReportLog.rtf.zip](https://github.com/AlexandreRouma/SDRPlusPlus/files/7249670/TroubleReportLog.rtf.zip)

**Comment by K0HYD** [comment]
Hi!

The files in the .config folder and the TroubleReport log that goes to apple are attached. Hope this is the log you were looking for. Probably has a lot more information than you needed but hope it helps.

**Comment by K0HYD** [comment]
Sorry didn't mean to close the issue. Let me know if you can't get the files. 73 de Dale

**Comment by AlexandreRouma** [comment]
Alright thanks for this. I'll have a look at the code, the place where it crashes it pretty worrying.

**Comment by AlexandreRouma** [comment]
Just wondering, did resetting the config actually fix it?

**Comment by K0HYD** [comment]
Yes, I just deleted the entire directory and fired up sdrpp again and it came on just fine pointed to my airspy device. I may wait awhile to try the spyserver again. Thanks for the quick response.

Dale


On September 29, 2021 at 2:25:55 AM, AlexandreRouma ***@***.***) wrote:

Just wondering, did resetting the config actually fix it?

**Comment by AlexandreRouma** [comment]
these issues are likely fixed by now, reopen if not
