### ISSUE TITLE
Negative frequencies from .WAV-file

### ISSUE THREAD

**Issue by gvanem** [AlexandreRouma/SDRPlusPlus#397]
I used the `file_source.dll` to play an old .wav-file recording (32-bit, from 2009). I was surprised that it showed the spectrum mirrored:
![sdrpp-mirrored-wave](https://user-images.githubusercontent.com/945271/135652290-fcaa7c2d-3b1a-4a6a-b037-18dfdcb9df11.png)

Comparing with SDR-Sharp v1772, I see no negative frequencies:
![sdrsharp-no-mirror](https://user-images.githubusercontent.com/945271/135652579-4e965f4d-5c11-47f0-a717-686e53acc44b.png)

Is this *working as designed*?

**Comment by AlexandreRouma** [comment]
the "negative" frequencies is because it can't find the center frequency in the filename so it just default to zero.

For the mirroring however I'm not sure what's going on without looking a the wav file, could you upload it somewhere?

**Comment by gvanem** [comment]
Here: http://www.watt-32.net/dx/PR_090226-0558_01200kHz_000_055900_060030.wav

**Comment by AlexandreRouma** [comment]
This file looks  nothing like the first screenshot on my install

**Comment by AlexandreRouma** [comment]
I'll check the wav file itself, it's behaving a bit strangely

**Comment by AlexandreRouma** [comment]
Ok found, the issue, looks like old SDR# versions added a bunch of junk to the beginning of the file, removing it lets it play correctly
![image](https://user-images.githubusercontent.com/17126412/135663729-b140d3bf-5cc3-484d-95c9-64c83e0fd374.png)

**Comment by gvanem** [comment]
> This file looks nothing like the first screenshot on my install

Try zooming a bit. The file I uploaded **is** the same .wav-file in this PR.

> looks like old SDR# versions added a bunch of junk to the beginning of the file

You mean that this `PR_090226-0558_01200kHz_000_055900_060030.wav` from 2009 was recorded with SDR-Sharp? 
Hard to believe since the 1st SDR-Sharp was released around 2013.

**Comment by AlexandreRouma** [comment]
Oh alright I thought it was SDR#
Well whatever recorded it added some metadata in front of the audio data which causes it to read the sames wrong

**Comment by bczhc** [comment]
Met the same thing, and then reached here. Just for the information, one way to remove these metadata is via:
```bash
ffmpeg -i input.wav -fflags +bitexact -flags:v +bitexact -flags:a +bitexact output.wav
```

Then SDR++ will handle it correctly.
