### ISSUE TITLE
Failed to compile with vs2019

### ISSUE THREAD

**Issue by erichuanhuan** [AlexandreRouma/SDRPlusPlus#405]
First, I used cmake to compile, and then opened the sdrpp.sln project file. There were a lot of errors when compiling. What is the reason? Thank you

**Comment by AlexandreRouma** [comment]
1) You're not supposed to use VS to compile it, follow the build instructions in the readme
2) What errors? I can"t say much without seeing them
3) If you've pulled from the master branch while I was working on it a few hours ago, there's a high chance that it might have been broken. Try pulling and rebuilding
