### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by girardim** [AlexandreRouma/SDRPlusPlus#408]
Hello!

Only a simple issue on Zoom slider bar.
When arriving to topmost zoom, it could be smother.

Yours.

**Comment by AlexandreRouma** [comment]
Hello,
this was already fixed and will be available in the next release

Regards.

**Comment by girardim** [comment]
Thank you very much.
Great job with SDR++.
I have changed from sdrsharp to SDR++...

Best regards.
