### ISSUE TITLE
UDP source  - request feature

### ISSUE THREAD

**Issue by F5OEO** [AlexandreRouma/SDRPlusPlus#409]
Having a generic udp i/q source could be interesting : should be unicat or multicast.
Source need to have a format parameter (CS8,CS16,CF32..)

Goal is for example to retrieve data from plutosdr without the need of iio.

**Comment by AlexandreRouma** [comment]
Could be a good addition to the network sink, I'll have to look into it.

**Comment by AlexandreRouma** [comment]
In the end I won't support it, I suggest users write their own source module instead.
Having a textbox where users can enter any samplerate is a recipe for disaster. (and it would be required for such a general source).
