### ISSUE TITLE
SDRPlay FM Notch Filter always on at startup

### ISSUE THREAD

**Issue by Xara82** [AlexandreRouma/SDRPlusPlus#425]
When i open up SDR++ with my RSP1a (or stop and start the receiver again) the FM notch filter is always activated in the device,
I have to activate it in SDR++ and deactivate it again to make it work.
This happends on both windows v1.03 and linux v1.04

**Comment by AlexandreRouma** [comment]
This bug should be fixed in the latest commit, the nightly build is currently building so you'll be able to download it if you don't want to build it yourself.
