### ISSUE TITLE
Feature request: also show dongle serial numbers

### ISSUE THREAD

**Issue by jaymot123** [AlexandreRouma/SDRPlusPlus#432]
Can the second pick-list from the top under Source in the sidebar be made to also show dongles' serial numbers? For RTL-SDR style dongles you can use the command `rtl_eeprom -s [desired_serial_number]` to assign custom SNs to make it easier to tell multiple dongles apart, after installing rtl_sdr. For example the one I use on a Raspberry Pi for ADS-B is S/N 00001090 (1090MHz, the ADS-B frequency), and the one I use with SDR++ for monitoring aeronautical VHF voice frequencies or ACARS is 00000125 (which is in the middle of the air band, roughly.) It would be easier for those of us who "serialize" our SDR dongles to select the right one in SDR++ if the SN was also shown (if they were both connected to my computer or when I get another dongle.)

**Comment by AlexandreRouma** [comment]
implemented
