### ISSUE TITLE
No audio from SDR++

### ISSUE THREAD

**Issue by dungar43** [AlexandreRouma/SDRPlusPlus#436]
Setup :  Ubuntu 21.04 , SDR++ v1.0.3, Terratech SDR
SDR++ displays fft but no audio. 
GQRx on same dongle works fine. 
SDR++ speaker symbol on top row is disabled and volume control does not move  
Speaker symbol under radio is ok and volume control moves.
 Pulse audio and 48000 listed under Radio.

**Comment by dungar43** [comment]
Thanks , I'll check it.

**Comment by AlexandreRouma** [comment]
Is rtaudio installed properly?
