### ISSUE TITLE
SDR++ for tablet PC with Windows 10 32bit

### ISSUE THREAD

**Issue by beta-tester** [AlexandreRouma/SDRPlusPlus#437]
hi,
i want to use my tablet PC with **Windows 10 32bit** OS with your SDR++, but unfortuantely there is only **sdrpp_windows_x64.zip** available that is not compiled for **Windows 10 32bit**. 
is there a chance to get a compiled binary **sdrpp_windows_x86.zip** on the releases page?

**Comment by AlexandreRouma** [comment]
Hello,
SDR++ isn't currently compatible with 32bit windows.
