### ISSUE TITLE
VC runtime/redist requirements are not in readme.md

### ISSUE THREAD

**Issue by beta-tester** [AlexandreRouma/SDRPlusPlus#439]
hi,
i just made a fresh install of Windows 10 x64 Pro on a laptop from scratch and tried to install and run SDR++ v1.0.3 (`sdrpp_windows_x64.zip`).
but then it popped up few error messages about missing dlls:
`VCRUNTIME140.dll`, `MSVCP140.dll`, `VCRUNTIME140_1.dll`
![1](https://user-images.githubusercontent.com/4750719/137200330-ae601419-255e-42ef-9ec9-4cd70cb804fd.PNG)
![2](https://user-images.githubusercontent.com/4750719/137200350-3f16058e-3fea-427c-b682-5fa037688d18.PNG)
![4](https://user-images.githubusercontent.com/4750719/137200363-dcadd6e6-f7d9-4dd1-acbc-db7f4da5f466.PNG)

i first had to download and install the latest Visual Studio Redistributables from [here](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist) to get rid of those error messages.

this should be mention in the readme.md file, that those vc redist are required for [install on windows](https://github.com/AlexandreRouma/SDRPlusPlus#windows)

**Comment by AlexandreRouma** [comment]
Will be in the manual but considering a simple google search gives million of results explaining it I won'y bother with it in the readme
