### ISSUE TITLE
Expose more device options

### ISSUE THREAD

**Issue by troffasky** [AlexandreRouma/SDRPlusPlus#442]
I don't know if this only applies to Soapy Remote, but I cannot toggle the broadcast and DAB notch filters on my SDRplay RSP1a from sdrpp. CubicSDR exposes these options when using Soapy Remote.

**Comment by troffasky** [comment]
Device string option would be a good start, wouldn't take much room in UI and doesn't require understanding of every device type.

**Comment by AlexandreRouma** [comment]
Switch to the SDRplay source instead
