### ISSUE TITLE
SDR++ on Jetson Nano

### ISSUE THREAD

**Issue by benb0jangles** [AlexandreRouma/SDRPlusPlus#446]
I have SDR++ working on Jetson Nano
![2IMG_20211016_234218](https://user-images.githubusercontent.com/15876842/137603928-d965ef3a-97ca-4cf4-9c02-e11907a621bd.jpg)
:

**Comment by benb0jangles** [comment]
yes, I reduced the FFT to 8192 to see how it responds

**Comment by AlexandreRouma** [comment]
Did it make a big difference?
In my experience FFTW3 is so optimized that it's barely noticeable at normal waterfall speeds.
By the way, there's a setting that says "fast FFT", I would recommend leaving it off (not sure if you put it on)
It saves a bit of CPU but makes the FFT imprecise.

Would be interesting to see how much performance can be gotten out of the jetson

**Comment by benb0jangles** [comment]
I am undecided on FFT settings so far, I only have 2GB Ram on Jetson Nano so I am trying to optimise. I like the Meteor demodulator :) and rigctrl - I have a rotator which I use with gpredict and having the option to automate will be impressive.

I notice only one way to get app to crash so far - when I try to add Module - weather_sat_decoder

But I think with the Jetson nano, I will be recording baseband, followed by offline decoding.

**Comment by benb0jangles** [comment]
![3_IMG_20211017_010213](https://user-images.githubusercontent.com/15876842/137605065-5ad584ab-e213-4893-8c31-7b66a609ae9b.jpg)

Jetson Stats seem good. Not reaching max CPU/GPU/MEM/TEMPS

**Comment by benb0jangles** [comment]
@AlexandreRouma how to enable UDP stream? I see there is network_sink, but no module appear in SDR++. Does network_sink run in background and settings adjusted in network_sink/main.cpp file? Or is not implemented yet.

**Comment by WB8CJW** [comment]
I select the "unsubscribe" link that appears at the bottom of
    messages then sign in to the group and it says I've been
    unsubscribed - but that is not the case.
    I continue receiving messages.
    
    Is this the Hotel California syndrome?  I checked in but can never
    leave? 😮

**Comment by AlexandreRouma** [comment]
> how to enable UDP stream? I see there is network_sink, but no module appear in SDR++. Does network_sink run in background and settings adjusted in network_sink/main.cpp file? Or is not implemented yet.

In the Sink menu, select "Network" instead of "Audio"

> I select the "unsubscribe" link that appears at the bottom of

You need to click the "Unwatch" button at the top right of the github page

**Comment by DavidHitchcock** [comment]
I have SDR++ running on the Jetson Xavier without any issues. I was wondering if SDR++ supports the Hackrf_sweep mode?

**Comment by AlexandreRouma** [comment]
SDR++ is an IQ processor. The HackRF sweep mode is a frequency analyser mode that only give FFT bins.
You can't use a mode like that with a receive application.

Also I'll close as it seems there is no issue here.

**Comment by DavidHitchcock** [comment]
Thanks for the quick response!

The reason I asked the question in reference to the Jetson Xavier is that I am running the hack on that system, and then running a neural net application on the results. I wanted to get a wider bandwidth measurement from the hack than 20MHz. qspectrumanalyzer does not support the aarch64 architecture of the jetson xavier. If I may pick your brain, any ideas on how to run hackrf_sweep on the jetson xavier?

Best,
David
