### ISSUE TITLE
SDRplay Center Spike in ZeroIF Mode

### ISSUE THREAD

**Issue by BT-Justice** [AlexandreRouma/SDRPlusPlus#447]
Thanks for releasing v1.0.4.  The now available LowIF modes get rid of the center spike I have had with my SDRplay RSP1a and RSPduo units.  The center spike is still present on ZeroIF mode though.  Is this something with the SDR++ software or is it something with the SDRplay 3.07 API?

**Comment by AlexandreRouma** [comment]
That's just how SDRs work, but  SDR++ doesn't hide it by defaiult.
Enable "IQ correction" if you want to get rid of it

**Comment by AlexandreRouma** [comment]
Can you show a screenshot of the FFT and waterfall?
