### ISSUE TITLE
No tracking with 1.0.4 and GPredict

### ISSUE THREAD

**Issue by bickbick** [AlexandreRouma/SDRPlusPlus#450]
v1.0.3 works fine, but 1.0.4 will not track in Gpredict. I set up everything the same. The rigctl server is running and connected.
RSP1A with Windows 11. Gpredict 2.3.37.

**Comment by AlexandreRouma** [comment]
Works fine for me using that exact version of gpredct. You likely configured something wrong.
Show your RigCTL server menu, gpredict config and gpredict radio control window
