### ISSUE TITLE
Issues with SDRPlay 1A on macOS

### ISSUE THREAD

**Issue by corvus-ch** [AlexandreRouma/SDRPlusPlus#463]
Using SDR++ on macOS 11.5.2 with an SDRPlay 1A. I have several observations that might or might not be related. 

When starting SDR++, its console output shows `[error] Could not intiatialized the SDRplay API. Make sure that the service is running.` When that happens, I can select the SDRPlay as a source but the device shows as unavailable (red text in SDR++). This usually can be fixed by sending SIG TERM to the `sdrplay_apiService` process.

Sometimes that does not work and SDRPlay does not even show up as a source. In that case the log shows `[error] Could not init RSP device: sdrplay_api_Fail`. The only way to recover from this, is to reboot the system. There is no `sdrplay_apiService` process running and disconnecting and reconnecting the SDRPlay hardware does also not change anything.

Listening to the radio waves for an extended time, things just stops. SDR++ disengages and there is no error explaining why. I discovered this while trying to record some POCSAC messages over night.

I can live with having to kill the `sdrplay_apiService` process once in a while. However, I highly dislike having to restart my system to fix things. Even having a workaround for this would be fine. And the software stoping to receive signals shoult just not happen.

**Comment by loewal** [comment]
That same problem also occurs on Monterey 12.0.1.
‘sudo launchctl stop com.sdrplay.sdrplay_service’
is the only way to get things working. Sometimes even a usbreset …/… (compiled this; very handy!).
Hackrf or rtlsdr are fine.
I’m also using SDRangel. Same trouble.
My opinion: purely SDRplay related i’m afraid.

Grtz

**Comment by F4HVO** [comment]
I have similar problem on Windows 10, Sdr++ 1.0.4, device is listed but it says "No device available" and pressing "play" does not display anything on the waterfall (also no sound output). Tested also with PlutoSDR and it works well, also the SDRPlay works with SDRUno.
![image](https://user-images.githubusercontent.com/54859526/138245564-b27525d2-b607-4146-8094-148c7ba933f2.png)
