### ISSUE TITLE
SDR++ V1.0.4 macOS fails on startup

### ISSUE THREAD

**Issue by gitjoost** [AlexandreRouma/SDRPlusPlus#465]
Fails on start up with:
dyld: Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.2.dylib
  Referenced from: /usr/local/bin/sdrpp
  Reason: image not found
[1]    35993 abort      sdrpp

macOS 11.6

And I suspect other libraries are missing/needed also. Providing an installer for macOS without the necessary libraries though perhaps well intended is not helpful, certainly not if instructions for finding/installing these libraries are missing also.  I suggest removing this installer.  Moreover, there is also no uninstaller (or manual instructions) nor information provided where SDRpp is installed/what the pkg file installs.

**Comment by bmparr** [comment]
Have you installed glew via brew?

I'm building sdrpp using the master branch on an M1 Mac. I'm targeting an RSPdx using the sdrplay driver

I know it shouldn't matter but it seemed to help when I turned Debug on in cmake.

With debug on, I just had two issues to sort 1) the location of airspy.h and airspyhf.h are different than what is in their include directives, ie. had to drop the directory (airspy/airspy.h -> airspy.h), and 2) waterfall.cpp would fail as the rawFFTSize had not been initialized properly before the doZoom function was called, so I just added the rawFFTSize value as a parameter to doZoom and then doZoom checks that:  (int)id+j is indeed < rawFFTSize.

I had to build SoapySDRPlay, volk & liquid-dsp manually.

Seems to be pretty solid now but I need to get off the master for sure.

**Comment by tlwsail** [comment]
Am excited about this software for my Mac and RPI.
Used Installer on my Mac to install but cannot find the app anywhere. I do have sdrsharp-x86-noskin in my Downloads folder. Have homebrew already installed.
1) Do install instructions exist?
2) Do I need to install dependencies in the Terminal window?
Thank you!

**Comment by AlexandreRouma** [comment]
The .pkg are no longer gonna be update. I suggest you try the proper .app release that doesn't require installing dependencies and doesn't have to be launched from the terminal like the pkg.
You can download the latest intel .app at https://www.sdrpp.org/nightly
If you have a M1 mac, I can provide manual builds

**Comment by tlwsail** [comment]
Thank you.

**Comment by zoeloe** [comment]
Noob question here.... sorry:   I'm landing on [https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/1473099237
](url) when opening [https://www.sdrpp.org/nightly](url) can't see the intel  .app for MacOS...  I'm probably dumb....

**Comment by AlexandreRouma** [comment]
Scroll down to "Artifacts" and click on "sdrpp_macos_intel"

**Comment by zoeloe** [comment]
Silly me... really,...  my pointer was in a place where the 2 finger scrollpad motion didn't work, so I didn't see the bottom part of the page.....     Anyway , thanks for the pointer.

**Comment by AlexandreRouma** [comment]
probably fixed with later nightly version but if no reopen a new issue.
