### ISSUE TITLE
Text entry field for frequency?

### ISSUE THREAD

**Issue by rileyrg** [AlexandreRouma/SDRPlusPlus#470]
Running sdr++ under linux (debian testing) using sway (may be relevant) the frequency LED type input is hellishly hard for me to use/figure out. Any chance of a simple text entry with a pick for hz/khz/mhz? I have had to create temporary bookmarks in order to select accurately a frequency as the LED input thingy keeps resetting itself. I dont think I'm overlooking an entry field in the left hand pane. (also return key defaults would be nice in the menu options eg "apply" when creating a new bookmark).

**Comment by rileyrg** [comment]
Oh,.I'm sorry, I missed the reply. I know its standard, almost the same - its just that I dont use a mouse much and would like to be able to type in a  frequency. rather than roll digits with a mouse wheel which I don have on my thinkpad. Its no big deal. Thanks for the feedback.

**Comment by AlexandreRouma** [comment]
if you hover over a digit and type, it'll set it and move your mouse cursor to the next.
See the keyboard controls here:
https://github.com/AlexandreRouma/SDRPlusPlus/wiki/UI-Controls#frequency-select

**Comment by rileyrg** [comment]
Yeah, it's really finicky on debian with sway/wayland.  I had moved to gqrx but I'll give sdrpp another go and document any issues. --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 10/11/2021, 14:53 AlexandreRouma ***@***.***> wrote:

   
  if you hover over a digit and type, it'll set it and move your mouse cursor to the next. See the keyboard controls here: https://github.com/AlexandreRouma/SDRPlusPlus/wiki/UI-Controls#frequency-select
