### ISSUE TITLE
SDR++ requires  libjack-jackd2-0 removal in Linux Mint 20.2 Cinnamon / Ubuntu 20.04

### ISSUE THREAD

**Issue by HoracioDos** [AlexandreRouma/SDRPlusPlus#477]
Hello.
I want to install sdr++ 1.0.4 for ubuntu focal and it requires to remove libjack-jackd2-0 in Linux Mint 20.2 Cinnamon. If I remove this package a ot of of other system packages will be removed.
![image](https://user-images.githubusercontent.com/4549674/138610942-4f4a9348-a5b1-4b69-8ecd-60a55313eb09.png)
I didn't find any problems to install SDR++ 1.0.4 in Linux Mint 20.2 XFCE where libjack0 is installed instead of  libjack-jackd2-0
Thanks in advanced

**Comment by v1ckxy** [comment]
BTW, basically the same happens with official clockworkpi uconsole debian trixie image.
The solution is the same: Just install ```libjack-jackd2-dev```
