### ISSUE TITLE
u8 IQ file playback

### ISSUE THREAD

**Issue by rs1729** [AlexandreRouma/SDRPlusPlus#478]
(SDR++ v1.0.4)
When I load a SDRSharp IQ recording (8 bit unsigned), the file plays with double speed.
[20180516_233225Z_405300000Hz_IQ.wav.gz](https://github.com/AlexandreRouma/SDRPlusPlus/files/7436128/20180516_233225Z_405300000Hz_IQ.wav.gz)
```
Channels       : 2
Sample Rate    : 250000
Precision      : 8-bit
Duration       : 00:00:10.00 = 2500000 samples ~ 750 CDDA sectors
File Size      : 5.00M
Bit Rate       : 4.00M
Sample Encoding: 8-bit Unsigned Integer PCM
```
```
00000000: 5249 4646 644b 4c00 5741 5645 666d 7420  RIFFdKL.WAVEfmt 
00000010: 1000 0000 0100 0200 90d0 0300 20a1 0700  ............ ...
00000020: 0200 0800 6461 7461 404b 4c00 7f80 7f80  ....data@KL.....
00000030: 7e7f 807f 8080 7f7f 807f 8080 8080 7f7f  ~...............
...
```
Another SDRSharp (8 bit unsigned) recording with sample rate 1024000 shows the same and the signal is all over the place.

However if I convert to 16 bit signed samples, everything is fine.

**Comment by rs1729** [comment]
@AlexandreRouma 
I observed the following playback issue (v1.0.4):
If I grab the filter window in order to change the filter size in FM, the playback speeds up until I release the left mouse button. (It does not happen if I have another VFO audio active.)

**Comment by AlexandreRouma** [comment]
this is normal, the file source is not throttled, when the DSP working is repeatedly stopped and started for when changing the taps of the filter, some data dropped thus causing the apparent "speed up"

**Comment by AlexandreRouma** [comment]
grouping with #129, follow that issue instead
