### ISSUE TITLE
Raspberry Pi -  device serial number shown - No device available message 

### ISSUE THREAD

**Issue by philg4iio** [AlexandreRouma/SDRPlusPlus#482]
Following an update and reboot I can no longer start SDR++. The RSP1A and its serial number is shown however there is a red error stating that - No device available 

Any suggestions on fault finding this issue?

Thanks

**Comment by AlexandreRouma** [comment]
Make sure the sdrplay api is set up to run at boot (or start manually it if you don't want it to start automatically)

**Comment by philg4iio** [comment]
Thank you, how do I do I start and or run automatically?

**Comment by AlexandreRouma** [comment]
`sudo systemctl enable sdrplay`
`sudo systemctl start sdrplay`

**Comment by philg4iio** [comment]
Thank you

**Comment by AlexandreRouma** [comment]
Closing for now, if it didn't fix your issue, please re-open
