### ISSUE TITLE
Help, please, what about multi-vfo like in sdr#?

### ISSUE THREAD

**Issue by santus118** [AlexandreRouma/SDRPlusPlus#486]
Is SDR++ have this function, to listen many freqs together?

**Comment by starvald** [comment]
in the module manager, select radio, add a name for it then click the + icon.
you can add as many as you wish, you'll also need to assign where to send its audio in the sinks module.

**Comment by santus118** [comment]
Thanks, it works! But how I can modify freqs of additional "radio"? Or it must be only deleted, then choose freq and add new "radio"?

**Comment by starvald** [comment]
you can either click on the radio in the FFT window to select it or 'page up'/'page down' on the keyboard to cycle through them.
once selected you can click somewhere on the FFT window to move it, use mouse wheel scroll or click a bookmark if you have one.

**Comment by nkaramolegos** [comment]
Can you share how the VFO is working in term of signal processing? Do you use a NCO? I mean is something like channeling (NCO, filtering, etc)?
