### ISSUE TITLE
[Bug?] Text on bookmark label disappears when label is clipped by edge of pandapter

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#495]
As the title says, the text on a bookmark label is not rendered when part of the label is outside the pandapter area. This happens for both the left and right edges in the same way.

![bookmark label clipped](https://user-images.githubusercontent.com/41851763/139943508-8984adb4-4e2a-45c6-9119-6fc35ab155e1.gif)

**Comment by AlexandreRouma** [comment]
That's intended, to my knowledge imgui doesn't have a way of partially rendering text so I don't display it when it would draw out of bounds

**Comment by shuyuan-liu** [comment]
OK, thanks for clarifying
