### ISSUE TITLE
Virtual sound devices - SDR++ falls back to default sound device after some time

### ISSUE THREAD

**Issue by OZ1BV** [AlexandreRouma/SDRPlusPlus#497]
Hi

I am using SDR++ in combination with WSJT-X (WSPR RX only) and HackRF One. 
I have created a virtual audio device using pacmd like this:

         pacmd load-module module-null-sink sink_name=Virtual_Sink1 sink_properties=device.description=Virtual_Sink1

It works perfectly for 10-15 minutes and then SDR++ falls back to the default audio device. 
The left side panel still shows the virtual device. If I select the default audio device and then the virtual again it works again for a limited time.

Is this a PulseAudio issue?

Best regards Brian - OZ1BV.

**Comment by AlexandreRouma** [comment]
This is very likely a portaudio bug, the code only opens the stream once, there is no reason for it to switch off with no use input to do so.

I also know of users who use those virtual sinks for days at a time never having any issues so this is likely a new bug
