### ISSUE TITLE
Windows releases do not contain all necessary DLL's etc

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [AlexandreRouma/SDRPlusPlus#5]
When trying to run the Windows release, it initially fails because volk.dll is missing, 

Looking in your Building for Windows, I noticed
"PothosSDR (for libvolk and SoapySDR)"

Hence these files are not just required for building, they are required to run the application and IMHO should be included as part of the release, even if you didn't write them (as they are open source and you can credit the original source)

BTW. Even after installing those files, the application does not detect my RTL SDR, which works fine under SDR#

**Comment by AlexandreRouma** [comment]
Hi, these files are not included as they are required to be properly installed, not just in the path. SoapySDR needs modules for every SDR model you plan on using. This most likely explains why your RTL isnt detected. 

Remove the files you added to the software's root directory and make sure SoapySDR is properly installed along with all the modules (if you installed pothos sdr this should already be fine). To verify the install, run `SoapySDRUtil --find`. Your sdr should be listed in the output.
