### ISSUE TITLE
Can't get pulseaudio on 2nd, nearly identical, machine. 

### ISSUE THREAD

**Issue by clytle374** [AlexandreRouma/SDRPlusPlus#522]
Building from current git source.  Both machines are running very similar gentoo builds, both have pulseaudio installed.  Using cmake-gui I get different options on the 2 machines.  Machine #2 shows no pulseaudio configs.
![Screenshot_20211123_091108](https://user-images.githubusercontent.com/18334763/143040375-cba31c3d-d9eb-423b-b9cd-004cf3e5badc.png)

I'm getting bad audio glitches on machine #2 Any ideas? 
Thanks
Cory

**Comment by AlexandreRouma** [comment]
RtAudio bug:
https://github.com/AlexandreRouma/SDRPlusPlus/discussions/112

**Comment by clytle374** [comment]
I think you provided me with correct direction.  While the machines both had pulseaudio installed.  I did not have a global use flag set for pulseaudio set on the 2nd machine.  So media-libs/rtaudio-5.1.0:0  wasn't built with pulseaudio turned on.

 I'm going to close this as the pulseaudio use flag pulled in about 6 hours of rebuilds on that poor old machine, so I'll test it in the morning, but assuming that'll fix it.
Thanks
