### ISSUE TITLE
rotctl server?

### ISSUE THREAD

**Issue by benb0jangles** [AlexandreRouma/SDRPlusPlus#526]
Hello, is there any plan to add rotctl server module to SDR++

Thanks

**Comment by benb0jangles** [comment]
Something like this I use in command line to begin communication with rotator:
[rotctld -m 202 -r tty/01 -s 9600 -T 127.0.0.1 -t 4533 -C timeout=500 -C retry=0 -vvvvvvvv > pause](url)

**Comment by AlexandreRouma** [comment]
I'm not sure if this is really in the scope of SDR++.
is there really an advantage in having the rotator control inside the UI instead of just having them in a seperate window with dedicated software?
