### ISSUE TITLE
bookmark name does not support Unicode【1.0.4】

### ISSUE THREAD

**Issue by hhs66317** [AlexandreRouma/SDRPlusPlus#528]
version：1.0.4

Bookmark names currently do not support Unicode characters, and characters such as CJK characters entered are displayed as ???

**Comment by shuyuan-liu** [comment]
There's no plan to implement support for CJK (and other Unicode characters). See #275.

**Comment by hhs66317** [comment]
Okay, I'll use other software for the time being
