### ISSUE TITLE
Segfault on start with Debian Bullseye + AMD Radeon 21.40

### ISSUE THREAD

**Issue by aeburriel** [AlexandreRouma/SDRPlusPlus#529]
Upon starting, sdrpp 1.0.4 segfaults with the following backtrace:

> #0  __rawmemchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:65
> #1  0x00007ffff75ef5a2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffd900, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
> #2  0x00007ffff75c336f in _IO_strfile_read (string=0x0, sf=0x7fffffffd900) at ../libio/strfile.h:95
> #3  __GI___isoc99_sscanf (s=0x0, format=0x7ffff7b3abbc "%d.%d") at isoc99_sscanf.c:28
> #4  0x00007ffff7abc8d9 in ImGui_ImplOpenGL3_Init(char const*) () from /usr/lib/libsdrpp_core.so
> #5  0x00007ffff79e589c in sdrpp_main(int, char**) () from /usr/lib/libsdrpp_core.so
> #6  0x00007ffff7591d0a in __libc_start_main (main=0x55555556f410 <main>, argc=1, argv=0x7fffffffe1d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
>     stack_end=0x7fffffffe1c8) at ../csu/libc-start.c:308
> #7  0x000055555556f4fa in _start ()

Which points to ImGui ticket [#4279](https://github.com/ocornut/imgui/issues/4279)

Updating ImGui to 1.85 solves the issue on my system.

**Comment by AlexandreRouma** [comment]
pretty sure that was a bug in imgui that was fixed
