### ISSUE TITLE
Core Dump Running on XWayland

### ISSUE THREAD

**Issue by PacketOperator** [AlexandreRouma/SDRPlusPlus#534]
Not a huge deal, but thought it was worth mentioning.

Compiled from source running in Gentoo.

Gnome Wayland session.

Using nvidia closed-source drivers v495.44-r2

Using hackrf.

Application crashes after about 10 seconds with radio running.

Does not crash in gnome that is using xorg as the display server.  This is most likely not a priority for the development team, which I completely understand.  I see huge potential with this application and I am grateful for the all the work that I know has been put into it thus far :)

If you would like more system details please let me know.

**Comment by AlexandreRouma** [comment]
Likely a GLFW bug, I'd recommend opening an issue to them.
SDR++ doesn't handle xorg/wayland/any other display system itself, it delegates it to GLFW
