### ISSUE TITLE
[Cosmetic] New radio module shows units for de-emphasis with incorrect capitalisation

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#539]
Same issue as #91, units for de-emphasis should be `µs` instead of `µS`. The capital `S` stands for Siemens, the unit for electrical conductance.

I tried changing the following text, but for some reason after rebuilding this has no effect on the units shown.

https://github.com/AlexandreRouma/SDRPlusPlus/blob/15010cff010f141157e0ec560d7a15dd1f2ed62f/decoder_modules/radio/src/radio_module.h#L23 

Also, the name of this string is missing a `p`: should be `DeemphasisModesTxt`.

**Comment by AlexandreRouma** [comment]
fixed

**Comment by shuyuan-liu** [comment]
thanks
