### ISSUE TITLE
I don't know how to drive the PlutoSDR in macos version

### ISSUE THREAD

**Issue by onnonn** [AlexandreRouma/SDRPlusPlus#547]
You have said the plutosdr is built by default in macos version in the readme.md.

But I just don't know how to use it, I can't find it here.
![image](https://user-images.githubusercontent.com/36289793/145914394-3ce84083-031a-4fde-a8ba-bc5d165bd48a.png)
When I try this one, it's nothing here.
![image](https://user-images.githubusercontent.com/36289793/145914567-021ba3f8-bd44-4655-aeab-2ff76902c1ce.png)
In the module manager, I also can't find the PlutoSDR.
![image](https://user-images.githubusercontent.com/36289793/145914646-ad28d5b5-82af-4f34-b9f8-d564ef0b03c6.png)
Would you like to give me a hand?

**Comment by AlexandreRouma** [comment]
use the latest nightly build: https://www.sdrpp.org/nightly
