### ISSUE TITLE
Please allow provide option to turn on Fan for limesdr

### ISSUE THREAD

**Issue by clytle374** [AlexandreRouma/SDRPlusPlus#560]
I have a box with a fan plugged into the fan header.  Could you please allow the fan to be turned on?
Thanks, Cory

**Comment by AlexandreRouma** [comment]
the fan isn't supposed to be controlled in software. It's controlled by the LM7002 chipset and activated when it reaches a temperature of 55°C

**Comment by clytle374** [comment]
Oh, oops, thanks
