### ISSUE TITLE
PlutoSDR RF bandwidth filter issue

### ISSUE THREAD

**Issue by innovak** [AlexandreRouma/SDRPlusPlus#563]
Plutosdr's RF bandwidth filter is not automatically set to the sampling frequency value.Maybe a manual setting option can be added?

**Comment by AlexandreRouma** [comment]
the bandwidth IS set automatically by a call to ad9361_set_bb_rate.
This automaticallt generates the filter settings for the frontend.
https://github.com/AlexandreRouma/SDRPlusPlus/blob/201a612c191a02238554e91a00b8269228651f79/source_modules/plutosdr_source/src/main.cpp#L152

**Comment by innovak** [comment]
That's weird, I'm using version 1.0.4 and I'm pretty sure it didn't adjust the rf filter bandwidth because when I switch from the SDR console software to sdrplusplus, the previously set bandwidth would appear on the spectrogram.

**Comment by AlexandreRouma** [comment]
Implemented bandwidth selection including automatic selection
