### ISSUE TITLE
Using a Knob with SDRpp

### ISSUE THREAD

**Issue by ja-Bertolin** [AlexandreRouma/SDRPlusPlus#576]
Hello Alexandre,

Just to recap,

I am trying to use the gadget: [https://sdrgadgets.co.uk/universal/39-universal-vfo-tuner-plus.html](https://sdrgadgets.co.uk/universal/39-universal-vfo-tuner-plus.html) with SDRpp and, even though it works fine with GQRX, when I am trying to tune a frequency the accuracy of the tuner is not so smooth, jump several Khz not 1 by 1 according to the “ticks” of the scroll-wheel of the knob.

I have tried several “snap intervals” and they do not work as smooth as it is doing it with GQRX. I mean, using a SI of 40, every tick of the scroll-wheel of the knob (that would be the same as the mouse) does not correspond with the change of the frequency at the same time.

Is there anything else that I could test to sync the movement of the mouse/knob scroll-wheel and the ticks with the frequency?

Thanks

**Comment by AlexandreRouma** [comment]
probably was a wrong mouse position if it's just a scrollwheel, otherwise support isn't planned
