### ISSUE TITLE
DLL fail to load on Windows x64 

### ISSUE THREAD

**Issue by JoNoci** [AlexandreRouma/SDRPlusPlus#58]
I have installed sdrpp_v0.2.5_beta_preview_x64.zip. When executing I get errors as indicated in the attached screen dump.
I have also downloaded the source code, rebuilt it and get the same errors when executing.
Please could you advise how to get past this problem
![image](https://user-images.githubusercontent.com/55557934/103443039-d7260b00-4c63-11eb-806c-d9d5fd96d9c5.png)
![SDR++Errors](https://user-images.githubusercontent.com/55557934/103443066-23714b00-4c64-11eb-88e6-c1d854e63ba9.png)

**Comment by AlexandreRouma** [comment]
Hi,
you're missing PothosSDR or you don't have it in your path

Regards.

**Comment by JoNoci** [comment]
Many thanks... my error. I have the Airspy Mini dongle. The software is
trying to start Airspy HF+ and failing. Does the software support Airspy
Mini? How do I select it?
Regards
Joe

**Comment by AlexandreRouma** [comment]
the Airspy HF+ source if for the HF+ Discovery and HF+ Dual.
I'm currently writing a source for the Airspy R2 and Mini, but in that mean time I recommend using the SoapySDR source.
Your device should appear in the list of the SoapySDR source menu. If you, click refresh or restart SDR++

**Comment by JoNoci** [comment]
Got it... thanks for the support
Joe
