### ISSUE TITLE
Crash when importing bookmarks from csv file

### ISSUE THREAD

**Issue by OZ1SEJ** [AlexandreRouma/SDRPlusPlus#588]
I clicked "Import bookmarks", found my bookmarks from Gqrx, selected the file "bookmarks.csv" and SDR++ crashed.

**Comment by AlexandreRouma** [comment]
Hello,
Importing is only supported for SDR++ json format, not GQRX format.

**Comment by OZ1SEJ** [comment]
Ah. Okay. I think I would prefer an error message instead of a crash, though ;-)

**Comment by gvanem** [comment]
Maybe there (for MSVC at-least) should be a pair of `__try` /  `__except` statements around such Json stuff?
