### ISSUE TITLE
Unable to create Instance of soapy_source

### ISSUE THREAD

**Issue by JoNoci** [AlexandreRouma/SDRPlusPlus#59]
I am trying to get the software which I have built, to operate. The software I am using is sdrplusplus-0.2.5_beta_preview2.
I have the following problem

When trying to create an instance of SoapySDR Source (soapy_source) called from
core::moduleManager.createInstance(name, module);

IN the function refresh, line "devList = SoapySDR::Device::enumerate();"
throws an exception  as follows:
Exception thrown at 0x00007FFAD0644B42 (SoapySDR.dll) in sdrpp.exe: 0xC0000005: Access violation reading location 0x0000000000000019.
I cannot find the reason for this. The software is finding the dll - setup in config.json is
  "modules": [
    "./airspyhf_source/Debug/airspyhf_source.dll",
    "./plutosdr_source/Debug/plutosdr_source.dll",
    "./rtl_tcp_source/Debug/rtl_tcp_source.dll",
    "./radio/Debug/radio.dll",
    "./recorder/Debug/recorder.dll",
    "./soapy_source/Debug/soapy_source.dll"
  ],

Any ideas would be appreciated

**Comment by AlexandreRouma** [comment]
Hi,
this is a SoapySDR bug

SoapySDR cannot run from a program built in debug mode on windows, refer to this issue on the SoapySDR github page:
https://github.com/pothosware/SoapySDR/issues/265

Regards
