### ISSUE TITLE
Library not loaded (macOS Monterey)

### ISSUE THREAD

**Issue by lukaszlis** [AlexandreRouma/SDRPlusPlus#594]
Hello. When I try to start it from console I have that issue:
dyld[2598]: Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.2.dylib
  Referenced from: /usr/local/bin/sdrpp
  Reason: tried: '/usr/local/opt/glew/lib/libGLEW.2.2.dylib' (no such file), '/usr/local/lib/libGLEW.2.2.dylib' (no such file), '/usr/lib/libGLEW.2.2.dylib' (no such file)
zsh: abort      sdrpp

**Comment by AlexandreRouma** [comment]
The pkg is being discontinued, please switch to the proper .app bundle at https://www.sdrpp.org/nightly
