### ISSUE TITLE
rigtcl server does not work after the latest changes

### ISSUE THREAD

**Issue by dl7vea** [AlexandreRouma/SDRPlusPlus#601]
The rigctl server does not receive neither transmit frequency changes after the last changes

**Comment by AlexandreRouma** [comment]
Nothing was changed in the rigctl server, I suspect this is an issue with the latest himlib update that completely breaks the protocol.

**Comment by dl7vea** [comment]
I'm using the old hamlib and nothing was changed in this area on my side.

So it might be indeed the network library.

**Comment by dl7vea** [comment]
If I try to connect sdrpp rigctl via:

rigctl -m 2 -r 127.0.0.1:4534

I see a short while status "Connected" in sdrpp, then a "Listening" again and the command line tool reports Communication timed out

**Comment by dl7vea** [comment]
With the release a view minutes ago it works again!

Thank you!
