### ISSUE TITLE
Feature request: mouse wheel zoom

### ISSUE THREAD

**Issue by Rua** [AlexandreRouma/SDRPlusPlus#608]
Can a feature be added to make the view zoom when the mouse wheel is rolled with the mouse over the FFT/waterfall, possibly with ctrl held (as in SDR#) or only when the mouse is over the frequency scale (as in Gqrx)? The view should zoom on the position of the mouse cursor, so whatever frequency is under the cursor should remain there and not move.

**Comment by AlexandreRouma** [comment]
After reflection I won't be adding that feature. I scrolling (including with modifiers) will be reserved for other things.
