### ISSUE TITLE
macOS Nightly .app build doesn't start

### ISSUE THREAD

**Issue by gegtor** [AlexandreRouma/SDRPlusPlus#612]
Latest build https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/1737376889 doesn't start

When I try to run it from the command line it says `killed`

macOS Monterey 12.1 Intel

How can I be of help

**Comment by ja-Bertolin** [comment]
It my case (Big Sur 11.6.2) it works fine.

**Comment by aosync** [comment]
@gegtor does the issue still persist in newer builds?

**Comment by gegtor** [comment]
@aosync I can't reproduce it in the latest build 🎉

Build Binaries #769
