### ISSUE TITLE
Enhancement request (UI): improve visibility of checkboxes in the options pane

### ISSUE THREAD

**Issue by jaymot123** [AlexandreRouma/SDRPlusPlus#617]
In all themes except Light and Marine Grey the checkboxes to enable options such as squelch are hard to see, being dark boxes on a dark background. Could the color of the checkboxes in the Army Green, Dark and Deep Blue themes be made a lighter shade of their respective colors, or lighter-color borders be added? Thanks.

**Comment by AlexandreRouma** [comment]
I've not seen any other request for this, so I'd suggest instead creating a theme to suite your needs.
