### ISSUE TITLE
Aborted (core dumped) if ~/.config/ dont exist.

### ISSUE THREAD

**Issue by MaxPeal** [AlexandreRouma/SDRPlusPlus#619]
```
user@fcb88529c37f:~$ sdrpp 
[2022-01-28 15:13:14.862] [info] SDR++ v1.0.4
[2022-01-28 15:13:14.862] [warning] Root directory /home/user/.config/sdrpp does not exist, creating it
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [/home/user/.config/sdrpp]
Aborted (core dumped)
user@fcb88529c37f:~$
```
this is a showstopper for running sdrpp inside a docker via x11docker,
as the user name and also the home dir name is set at the docker run and not at the docker build.

**Comment by AlexandreRouma** [comment]
Use `-r [directory]` to use another config directory.
By the way I'm not even sure if it'll run since it requires OpenGL. This is a non standard environment and I won't go out of my way to support it.
