### ISSUE TITLE
automatically center waterfall when changing frequencies using rigctl

### ISSUE THREAD

**Issue by falseywinchnet** [AlexandreRouma/SDRPlusPlus#627]
The program doesn't center the passband or waterfall when changing frequencies.

**Comment by shuyuan-liu** [comment]
Are you using center tuning mode (target icon at the top next to frequency) or free tuning mode (two arrows icon)? The latter doesn't auto center the waterfall.

**Comment by falseywinchnet** [comment]
it seems i was using free tuning mode.
