### ISSUE TITLE
Windows sdr++ not opening

### ISSUE THREAD

**Issue by Breezeyview** [AlexandreRouma/SDRPlusPlus#628]
I have installed sdr++ on two different pc's using Windows 7 and 10. Neither one will open properly. Windows 10 pc starts to open then reverts to desktop. Windows 7 pc opens with a partial screen and stops.

**Comment by shuyuan-liu** [comment]
Could you run sdrpp from a terminal with the `-s` option and post the logs produced?

**Comment by WB0OCV** [comment]
I recently had a similar problem and traced it to a conflict with the rtaudio.dll.  Try removing that dll from the sdrpp folder and see if the program will open.  See a more detailed description in Discussion Message #638.  Good luck.
Ken -- WBØOCV
