### ISSUE TITLE
Playback of recorded baseband

### ISSUE THREAD

**Issue by JoNoci** [AlexandreRouma/SDRPlusPlus#63]
The software allows the recording of the IQ data to a .wav file. Is there a way that this data can be 'played back' into the software for post analysis - ie to run the existing functionality as is but sourcing the IQdata from the .wav file?

**Comment by AlexandreRouma** [comment]
not yet.
The module is in development but is currently unusable.

**Comment by JoNoci** [comment]
As this is something I am really keen on,would it be possible to email me
the module in its current status. If I manage to get it working I will then
send it back to you?
Regards
Joe

**Comment by AlexandreRouma** [comment]
Hi, a crude baseband file player has been added. it's currently a bit unstable but works fine most of the time

**Comment by AlexandreRouma** [comment]
the file player is now fixed and enabled by default. Make sure to delete the existing config file or update the config manually to enable the module.
