### ISSUE TITLE
Hello, I have (HackRF ) I want to open the code of the signals (VHF ) and (UHF ) on the FM channel on the laptop using Windows 7, Thanks

### ISSUE THREAD

**Issue by abbas1964** [AlexandreRouma/SDRPlusPlus#646]
Hello, I have (HackRF ) I want to open the code of the signals (VHF ) and (UHF ) on the FM channel on the laptop using Windows 7, Thanks

**Comment by shuyuan-liu** [comment]
OK, what exactly do you need help with? What have you tried? Also, you opened two Issues with the same title, please close one of them.

**Comment by AlexandreRouma** [comment]
I gotta say I'm really not sure what's being asked here. If it's **not** related to the SDR++ software I suggest asking on a general SDR related forum instead.

**Comment by abbas1964** [comment]
There are no two issues, but only one is that I have SDRSharp on my laptop and I have a HackRF device, NooElec............ and I can't decode the signal sent via FM
    On Friday, February 11, 2022, 06:49:51 PM GMT+3, Shuyuan Liu ***@***.***> wrote:  
 
 


OK, what exactly do you need help with? What have you tried? Also, you opened two Issues with the same title, please close one of them.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexandreRouma** [comment]
This is not the support section for SDRsharp but for SDR++.
Please ask for support on Airspy's forums instead.

**Comment by abbas1964** [comment]
> 

Good
I need the latest DSD software

**Comment by abbas1964** [comment]
> يجب أن أقول إنني حقًا لست متأكدًا مما يُطلب هنا. إذا **لم يكن** مرتبطًا ببرنامج SDR ++ ، فأقترح أن تسأل في منتدى عام متعلق بحقوق السحب الخاصة بدلاً من ذلك.

Good
I need the latest DSD software

**Comment by abbas1964** [comment]
> حسنًا ، ما الذي تحتاج إلى المساعدة فيه بالضبط؟ ماذا حاولت؟ بدون مزيد من التفاصيل ، لن نعرف المشكلة التي تواجهها ولن تتمكن من مساعدتك.
> 
> يبدو أن فتحت ثلاث إصدارات الإصدارات نفسها ، هل يمكنك إغلاق الإصدارات الأخرى من فضلك؟ يؤدي إلى إقرأ النكسات.
> 
> يرجى ملاحظة أن SDR ++ تم تطويره الأشخاص في أوقات فراغهم ، ولا يعمل أحد بدوام كامل للإجابة على الأسئلة على هذا الموقع. سيكون صبرك موضع تقدير كبير. شكرا لك!
Good
I need the latest DSD software
