### ISSUE TITLE
Close window not possible

### ISSUE THREAD

**Issue by loewal** [AlexandreRouma/SDRPlusPlus#650]
Bonjour Edouard,

I installed the latest version under Ubuntu Impish.
Now I cannot close the window anymore and have to kill the process within  BTOP (or any other processsmanager).
This happens on 2 machines.
On my iMac this is not the case.
Can you help?

**Comment by AlexandreRouma** [comment]
What do you call "latest version"? This doesn't tell me anything about which build you're actually using.
Latest released version? Latest master branch build? latest backend_abstraction branch build?

If you're talking about the backend_abstraction branch, there's a reason it hasn't been merged into master yet. It still has issues and this exact one was fixed this morning but not pushed yet.

**Comment by loewal** [comment]
Hello Alexandre,

I downloaded the version under Actions/ “backend_abstraction” and then the Impish-file.

https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/1837378817

**Comment by AlexandreRouma** [comment]
The non master branches should not be used. they're work in progress and usually broken.
Only install builds of the master branch
