### ISSUE TITLE
SDR++ Looks Blurry On Mac M1 and Help For M1 Mac

### ISSUE THREAD

**Issue by ChrisDev8** [AlexandreRouma/SDRPlusPlus#652]
When I was trying to build my own version of SDR++, the package volk would not install and I got an error. I don't remember what it said and something happened to my homebrew install so now I can't use brew. But the github issue #557 had the zip file with SDR++.app that worked perfectly. So to the creator, please add that zip file on issue #557 to the releases page. Anyways, once I got it to work it looked a little blurry on apple retina screen and a little off. I hope you understand!!!! Please don't be mean I've had lots of people who like NO WAY THAT A DUMB IDEA JUST CLOSE IT GDFGTERTWRGRGRE.

<img width="1276" alt="Screen Shot 2022-02-16 at 3 35 47 PM" src="https://user-images.githubusercontent.com/70666342/154352711-59e1cde9-de40-4ad8-b5ae-9dbd7a66b286.png">

I really hope you can make this software the best software defined radio program for Mac OS X! Unlike other alternatives.

**Comment by AlexandreRouma** [comment]
Can't do anything about it. SDR++ renders through OpenGL, if apple applies sont dumb scaling to stuff I can't do anything about it.

**Comment by ChrisDev8** [comment]
Ok but how about adding a `SDR++.app` file to the release page. Just like the .app file in issue #557 so people don't have to build their own. Not many people are "Computer Geeks".

**Comment by AlexandreRouma** [comment]
It's not the same version. It was a special manual build of the master branch, I'm not adding it to an existing release.
When the time of releasing the next version comes around, it will be in there, not before.

**Comment by ChrisDev8** [comment]
Thanks!
