### ISSUE TITLE
Version #616 has lost the possibility to enter frequency manually

### ISSUE THREAD

**Issue by ja-Bertolin** [AlexandreRouma/SDRPlusPlus#655]
JUst testing #616, and it seems that it has some problems to enter manually the frequency. When you enter for instance 6100, it only changes the number 6, and number 1 is placed in the same digit as 6, and the same for the ret

With #608 works fine, but not #616.

**Comment by AlexandreRouma** [comment]
Can't replicate, description unclear.
Please show exactly what you mean by "enter manually the frequency" and "the same for the ret"

**Comment by ja-Bertolin** [comment]
Apologies for the bad explanation. When you want to jump to a specific frequency you can type it on top of the Frequency Selector and it has been working fine so far. Now with 616, if I do the same the frequency does not change properly, I will try to explain it

For instance, imagine that you have the frequency 5000 in the selector, If I try to type 6100, once typed the 6 if I type the 1, it changes the 6 by 1, but does not write 61, and if know I type 0 it does not show 610 but just 0 in the first digit ...

I do not know whether it is clearer now

**Comment by AlexandreRouma** [comment]
So what you're trying to say is the mouse cursor doesn't move when a digit is typed?
I can't replicate that on windows. Unfortunately you haven't mentioned what OS you're using so I can't test on the specific platform

**Comment by ja-Bertolin** [comment]
Yes, it does not move

Sorry, I am using MacOS BigSur 11.6.4

I will try to reinstall it and test it again

**Comment by AlexandreRouma** [comment]
close as idle and very likely a GLFW bug as there is 0 reason for anything to stop working like that.
