### ISSUE TITLE
Visual glitches (ghosting) on Linux Mint 20.3 / AMD Ryzen 4300U

### ISSUE THREAD

**Issue by SanchYESS** [AlexandreRouma/SDRPlusPlus#660]
Hello! I've got weird behavior on Mint 20.3 kernel 5.13.0-22-generic.
Seems like ghosting, like image is accumulated instead of updating. SDR++ is working, I can hear tuned stations. FFT is working, waterfall is absent, menu and top bar are totally glitchy but also working.
SDR++ is built from source.
Runs on Lenovo IdeaPad Flex 5 14ARE05, AMD Ryzen 4300U.
![Screenshot from 2022-02-20 09-34-38](https://user-images.githubusercontent.com/89254866/154833169-6e76dabd-b875-4392-a7db-2bcd4c965512.png)

**Comment by AlexandreRouma** [comment]
Broken graphics driver, reinstall threm.

**Comment by toxa1983poloskov** [comment]
> Broken graphics driver, reinstall them.
thanks!
the same problem is observed on the old GNU NVIDIA Corporation G86 [GeForce 8400 GS] c Nvidia binary driver 340.108.

xserver-xorg-video-nouveau --  the graphical interface is usually displayed!!
