### ISSUE TITLE
SDR++ on top of other programs

### ISSUE THREAD

**Issue by TarLink48** [AlexandreRouma/SDRPlusPlus#662]
If you use a browser such as Google Chrome on top of SDR++, then at random time SDR++ appears very quickly on top of the browser and also disappears abruptly. If SDR++ is minimized, then blinking occurs no longer at the program window, but at its icon on the taskbar. I recorded a small video of how it happens , I don 't know if it 's an error or the normal operation of the program ...
Video - https://youtu.be/OUkAWfqMQLI
![1](https://user-images.githubusercontent.com/99340373/154855088-e1f9bd05-96a3-4653-9e26-3a475c42bbc3.PNG)
SDR++ v1.0.4
Win 10 x64

**Comment by AlexandreRouma** [comment]
SDR++ never tries to focus, It's something else on your system and not SDR++'s fault. Check your browser.
