### ISSUE TITLE
[Improvement request] Change LO frequency automatically after changing frequency via Rigctl

### ISSUE THREAD

**Issue by n2iw** [AlexandreRouma/SDRPlusPlus#664]
I wrote a [script](https://github.com/n2iw/cat-relay) to sync frequency between SDR++ and logging software  RUMlogNG or DXLab Commander. It works fine except when not in "center mode" (target/bullseye), a lot of times if I change band on the radio (frequency change requested via Rigctl), the LO is not changed appropriately, resulting current frequency out of SDR's coverage. I have to click "bullseye" then click back (I don't want my waterfall to shift when changing frequency on radio). If LO can be changed automatically close to requested frequency, that will be very helpful!!!

BTW. when directly changing frequency in SDR++, LO is changed appropriately no matter in "center mode" or not.

**Comment by AlexandreRouma** [comment]
That is simply expected behavior. RigCTL controls the VFO, NOT the center frequency of the SDR.

**Comment by n2iw** [comment]
> That is simply expected behavior. RigCTL controls the VFO, NOT the center frequency of the SDR.

Thanks Alex! I dug a little deeper and found out,  LO is changed actually, but it's a little too far away from VFO frequency sometimes. I noticed that at least for Airspy HF+ (I suspect it's similar for other SDRs), sensitivity drops on the edge of the coverage, makes about 80KHz on each edge not very usable.  And a lot of the time (for me), my requested frequency lands near the edge of the bandwidth of the SDR. 

I don't know current algorithm SDR++ used to decide center frequency, but may I suggest if a new center frequency is needed, make it close to or at requested frequency or middle of requested band?

**Comment by AlexandreRouma** [comment]
The algorithm only separates the VFO from the border when in normal tuning mode and if the center frequency changes. It doesn't try to prevent the VFO tro go right at the border since the user might want to do it for once reason or another.
What you want is simply, to leave the software in center tuning mode since that won't be an issue for an SDR like the HF+ which doesn't have a DC spike.

**Comment by n2iw** [comment]
Yes, using center tuning mode would solve the issue for sure. Except when I tune inside the band, I don't want my waterfall to shift left and right. When waterfall shifts, I lose track of where the stations were, which it the main reason for using waterfall. 

Alternatively, is there a RitCTL command that I can use to change center frequency? If so, I can do it in my script.

**Comment by AlexandreRouma** [comment]
Unfortunately no, the RigCTL protocol doesn't have such command. It was designed for normal rigs that don't have a concept of a separate LO, you just tune wherever you want to tune.

You might want to look into writing a module that uses internal functions to do what you're trying to achieve.
