### ISSUE TITLE
Dependencies in non standard path

### ISSUE THREAD

**Issue by FenixC4** [AlexandreRouma/SDRPlusPlus#668]
I'm compiling SDRPlusPlus from source on linux, however i have dependencies like libhackrf or SoapySDR compiled from source and installed in non standard directories. Which flags am I supposed to use when using cmake to define these non standard paths ?

**Comment by AlexandreRouma** [comment]
there's no flag to set. If they were installed properly the pkgconfig file these libs intall will reflect the non-standard path.
