### ISSUE TITLE
No audio on Ubuntu 20.04

### ISSUE THREAD

**Issue by scottbomb** [AlexandreRouma/SDRPlusPlus#676]
Hi, I just installed it as you have instructed at https://github.com/AlexandreRouma/SDRPlusPlus#debian-based-ubuntu-mint-etc

I can use the tuner and see signals, waterfall works, "Radio" is checked, and yet I'm not getting any sound. Using RTL-SDR, Realtek RTL2838.

**Comment by shuyuan-liu** [comment]
Make sure in the Sinks tab you have changed "None" to "Audio" and selected the correct output device.

**Comment by scottbomb** [comment]
Thanks for the tip. I saw Audio was already selected but I had to
change the output from my sound card to "default" for it to work.
Thanks again,Scott

-----Original Message-----From: Shuyuan Liu ***@***.***>R
eply-To: AlexandreRouma/SDRPlusPlus <
***@***.***>To:
AlexandreRouma/SDRPlusPlus ***@***.***>Cc:
scottbomb ***@***.***>, Author ***@***.***>Subj
ect: Re: [AlexandreRouma/SDRPlusPlus] No audio on Ubuntu 20.04 (Issue
#676)Date: Wed, 02 Mar 2022 16:33:16 -0800

Make sure in the Sinks tab you have changed "None" to "Audio" and
selected the correct output device.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: <
***@***.***>

**Comment by John-Telek** [comment]
I'm having the same issue on Debian 11 with the nightly releases. If I compile my own The speaker icon is not locked out, but the nightly install is locked even though i've got radio selected and audio as the sink.

Any ideas pls ?

Cheers,
    John
