### ISSUE TITLE
Crashing on MacOs when starting up, #654 #657

### ISSUE THREAD

**Issue by ja-Bertolin** [AlexandreRouma/SDRPlusPlus#678]
Since several versions (#606) sometimes when trying to startup the app it crashes. And after some tries it goes fine (/thereafter the behaviour is fine too). @AlexandreRouma you mentioned that it could be a library, am I right? Is there anyway to fix it? It is only quite disturbing until it starts fine (4 - 5 time trying), once it starts fine no problem until I close it,

[crash_sdrpp.pdf](https://github.com/AlexandreRouma/SDRPlusPlus/files/8187787/crash_sdrpp.pdf)

**Comment by AlexandreRouma** [comment]
Follow #1265 instead
