### ISSUE TITLE
[improvement request] Place Squelch and Gain up top & label them.

### ISSUE THREAD

**Issue by gbeyer3** [AlexandreRouma/SDRPlusPlus#683]
First, @AlexandreRouma, I want to say a big THANK YOU for SDR++  This is an amazing package, very compact, much smaller than the other hog SDR application.  And cross platform to boot!  Just WOW!  It's chock full of features which, as a noob, I'm still getting my head around.  
That said, I'd like to humbly request a UI improvement.  Could you place both squelch and gain sliders at the top, stacked under or just to the right of the volume slider?  These are controls that are constantly used to tweak listening as one tunes.  Gain and squelch are buried down in settings, requiring opening the configuration, then clicks to expand, then find them in the long list of settings.  Volume, OTOH is handily at the top.  Also, I'd suggest labeling all three: "Volume" "Gain" and "Squelch". Gain and Volume are not labelled now.   Giving each a different color, would also be really cool, but that is not a must have, and if it results in bloat, well, nevermind.
Thanks again, this is a lot of fun!
best regards,
Greg

**Comment by AlexandreRouma** [comment]
Hello,
This is not possible for several reasons:

1) It would require a complete rewrite of how the top bar is implemented
2) This would be horrible to use on any machine with low screen realested
3) It goes against the modular nature of SDR++, which is source, processing and sink agnostic.
4) Won't work for SDRs with multiple gain settings (airspy, hackrf, SDRplay, etc...)
5) Can't allow for multiple radio modules or it will just fill the top bar indefinitly

I recommend you just keep the Radio menu open
