### ISSUE TITLE
Problems with Favorities List

### ISSUE THREAD

**Issue by SirTwsted** [AlexandreRouma/SDRPlusPlus#687]
The favorites list does not currently have a way to move a favorite input saved,  from one Group List to Another.
This will force the user to have to retype all their favorites all over again onto the new Group.  This is very stressful.

There is also no [C] , [V]  aka copy and paste feature in the favorites lists.  Which is a huge QoL drawback.

Here is an example of what I have gone through, which (to me) was a nightmare.
I started to put all the favorites frequencies I like in the general section of the favorites list.
Then I figured out that there was a way to create Groups for these favorites.  I then proceeded to try to either move or copy & paste
the saved favorite onto the new Group I created.  But it failed because there is no way of doing so.
The list was extensive, around 68 entries in the generals list and I have created 2 additional Groups for certain frequencies.
I have tried several times to copy and paste so I wouldn't have to retype everything all over again, but to no prevail.

Hence why I am now here posting this issue.

**Comment by AlexandreRouma** [comment]
1) Select all the ones you want to move (CTRL + Click)
2) Click "export", save the file somewhere
3) Switch to the list you want to move them to
4) Click "import", select the file you saved them as
5) Delete the bookmarks from the first list

**Comment by SirTwsted** [comment]
Would have been nice If I can just select the group that the frequency I want it to belong to,
by just going to EDIT and selecting the group with a drop-down menu.

Instead of all the unnecessary export and import, just to move a frequency to the proper group people want it on.

Just saying  :)

**Comment by AlexandreRouma** [comment]
Nobody constantly moves bookmarks from one list to another, and doing it any other way is a nightmare to implement.
