### ISSUE TITLE
Nightly macOS build won't start

### ISSUE THREAD

**Issue by petermllrr** [AlexandreRouma/SDRPlusPlus#695]
I downloaded the nightly build from https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/1872297127 but the app just terminates when launched.

macOS 12.3 (Intel)

Any pointers?

**Comment by ja-Bertolin** [comment]
It happens the same for me, if you try three-four times it starts fine, and works fine. I opened an Issue related to that #678

**Comment by AlexandreRouma** [comment]
could you try this exact build?
https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/1932808676

**Comment by ja-Bertolin** [comment]
This is the one that I am using and opened issue #678 ,in other post you mentioned something about a library that was provoking the crash in macos

**Comment by pumatrax** [comment]
Got it installed and running on my macOS. 

Installed these first: brew install fftw glew glfw volk airspy airspyhf portaudio hackrf rtl-sdr libbladerf

received an error about permission denied and then ran this.

sudo chown -R $(whoami) $(brew --prefix)/*

**Comment by AlexandreRouma** [comment]
closing as stalled
