### ISSUE TITLE
Dependencies to the -dev packages since 1.0.4

### ISSUE THREAD

**Issue by flux242** [AlexandreRouma/SDRPlusPlus#697]
Why do you want -dev packages to be installed? We do not install no -dev packages unless we are developing on them

**Comment by AlexandreRouma** [comment]
and I'll fix the deb to not include `-dev` where possible

**Comment by flux242** [comment]
where was it completed? Here's the nightly deb package:

Package: sdrpp
Version: 1.1.0-769
Maintainer: Ryzerth
Architecture: all
Description: Bloat-free SDR receiver software
Depends: libfftw3-dev, libglfw3-dev, libvolk2-dev, librtaudio-dev, libzstd-dev

**Comment by AlexandreRouma** [comment]
It was closed by mistake by @aosync and as I said I'll fix it later. I don't currently have the time to mess with package names.
it's not as simple as removing the dev suffix.

**Comment by flux242** [comment]
What are you talking about? You just provide proper packages names to that darn sh script that generates the deb. Is that the complexity you're talking about?
