### ISSUE TITLE
Wish: audio recording/split files.

### ISSUE THREAD

**Issue by starvald** [AlexandreRouma/SDRPlusPlus#7]
if/when you add audio recording could you add the ability for it to auto make a new time & datestamped file every hour? same as rtl_airband does.
also an option for making a new file every time the squelch breaks, not something i use personally but something ppl tend to ask for.

thanks.

**Comment by AlexandreRouma** [comment]
Good idea! Thanks for the suggestion.

**Comment by aosync** [comment]
Audio recording was added since then :)

**Comment by AlexandreRouma** [comment]
I'll add that split recording won't be supported
