### ISSUE TITLE
RTLSDR/AIRSPY win10

### ISSUE THREAD

**Issue by sdramateur** [AlexandreRouma/SDRPlusPlus#70]
Hi,  SDR++  not find RTL-SDR nor AIRSPY window error not find module  only the Pluto
Installed pothos  cubicSDR is running
--- SOLVED ---

**Comment by AlexandreRouma** [comment]
hello,
the pre-release #3 doesn't have the RTL-SDR module yet. 
I will release a version with in tomorrow, but in the mean time, here is a build that has it:
[sdrpp_windows_x64.zip](https://github.com/AlexandreRouma/SDRPlusPlus/files/5984101/sdrpp_windows_x64.zip)

For the airspy issue, I'm not too sure, are you able to use it with the Soapy module? 

I think the most probable issue is that libairspy and libairspyhf are out of date. So I would recommend trying to update pothos and using the build included here.

**Comment by sdramateur** [comment]
First:   SDR#  is working for many years   CubicSDR + GQRX are working 
SDR++
Airspy is detected  but seem not receive any signal
RTLSDR not doing

Startup SDR++ i get a popup ERROR libusb_set_option not found in Program File\PothosSDR\bin\uhd.dll

**Comment by AlexandreRouma** [comment]
Likely a soapy bug, sdr++ doesn't use UHD at all

**Comment by sdramateur** [comment]
RTLSDR when tuning, there is some shorts "hickups" like the screen freezes its not smooth tuning

**Comment by AlexandreRouma** [comment]
> RTLSDR when tuning, there is some shorts "hickups" like the screen freezes its not smooth tuning

This is normal for a RTL-SDR. The RTL cannot tune while streaming samples. This means the stream has to be cut every time you tune resulting in inconsistancies

**Comment by sdramateur** [comment]
Your example picture  show multi radio support?  (radio1 + radio2)  How do i setup RTLSDR + AIRSPY?
It seem settings also record path not saved after close?

**Comment by AlexandreRouma** [comment]
Multi VFS is not multi device. It can only receive from one device at once, but can decodes several parts of the spectrum.

**Comment by sdramateur** [comment]
But How do i setup MULTI VFO?

**Comment by AlexandreRouma** [comment]
you need to edit the config.json file and add an entry in the "moduleInstance" parameter. After that, you need to add an entry in the "menuOrder" parameter to decide where to show the menu.

**Comment by sdramateur** [comment]
When start BETA #3 below error

[2021-02-21 01:29:38.494] [info] Loading ./modules/rtl_sdr_source.dll
[2021-02-21 01:29:40.985] [error] Couldn't load ./modules/rtl_sdr_source.dll.
[2021-02-21 01:29:40.986] [info] Loading ./modules/rtl_tcp_source.dll

[2021-02-21 01:29:41.323] [info] Initializing HackRF Source (hackrf_source)
[2021-02-21 01:29:41.325] [error] Module 'hackrf_source' doesn't exist
[2021-02-21 01:29:41.325] [info] Initializing PlutoSDR Source (plutosdr_source)

[2021-02-21 01:29:41.355] [info] Initializing SoapySDR Source (soapy_source)
←[1m←[31m[ERROR] SoapySDR::loadModule(C:\Program Files\PothosSDR/lib/SoapySDR/modules0.8/uhdSupport.dll)
  LoadLibrary() failed: Kan opgegeven procedure niet vinden.
←[0m
[2021-02-21 01:29:43.324] [info] Setting sample rate to 6000000.0

**Comment by sdramateur** [comment]
It here a typo thingy  ?
./modules/rtl_sdr_source.dll.  <== the dot?

**Comment by AlexandreRouma** [comment]
You either misstyped the filename in the config or you don't have librtlsdr

**Comment by sdramateur** [comment]
Nope,  just install the BETA #3  and notice the startup screen give 2 ERRORS  and i see the  . DOT in the end  while other startup liners not have the . DOT

**Comment by sdramateur** [comment]
Version 0.2.5. BETA Feb 2021 is working but your latest windows,  stuck with "loading audiosink.dll"

**Comment by AlexandreRouma** [comment]
it's old, use the latest nightly build from here: https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/812047935
(scroll down and select sdrpp_windows_x64)

**Comment by sdramateur** [comment]
your latest windows nightly build download yesterday  after install its stuck with loading "audiosink.dll" and "recorder.dll" 
When copy these audiosink.dll" and "recorder.dll from the older release 0.2.5Beta februari,  than nightly build download from yesterday, is startup without error
