### ISSUE TITLE
BladeRF with no device segfaults

### ISSUE THREAD

**Issue by DeltaYelta** [AlexandreRouma/SDRPlusPlus#700]
Selecting BladeRF as my source, with nothing in the rest of the dropdowns gives a segmentation fault.
`dmesg` tells me:
`sdrpp[17496]: segfault at 0 ip 00007fe3dae32d06 sp 00007ffca3f4dda0 error 4 in bladerf_source.so[7fe3dae04000+36000]`
I don't have any BladeRF device to test this further.

**Comment by aosync** [comment]
Please provide more information, such as the logs as well as the particular SDR++ version

**Comment by AlexandreRouma** [comment]
Closing as idle, reopen if you're still experiencing the issues.
