### ISSUE TITLE
Display Issue Windows 10 Pro

### ISSUE THREAD

**Issue by AA7CL** [AlexandreRouma/SDRPlusPlus#704]
Just downloaded version 1.0.4 and when I launch the program, I get a really dark screen and can't see the program well enough to configure the source or any other aspect of the software. What am I doing wrong..? Anyone else experiencing this issue?

Windows Pro 64 bit OS. 

![image](https://user-images.githubusercontent.com/8794691/160303297-07515c42-a9ce-429c-95aa-b31524df5ca7.png)

**Comment by AlexandreRouma** [comment]
Update your graphics drivers

**Comment by aosync** [comment]
Closing the issue as staled after suggestion, feel free to reopen if the problem persists.
