### ISSUE TITLE
sdrpp_server_source.dll location in Windows 64bit build

### ISSUE THREAD

**Issue by Derek000** [AlexandreRouma/SDRPlusPlus#715]
Hi all,

I can't find sdrpp_server_source.dll in the modules directory when installing the latest build.
It also doesn't appear in the install package or available in the available modules.

Should this be included?

Thanks
Derek

**Comment by AlexandreRouma** [comment]
What do you mean by "latest build"? Release? Nightly?
If you're talking about the latest release, it's from 6 months ago and SDR++ server was only written 2 two months ago, so no, it won't have any of the SDR++ server/client code.
You need the nightly build: https://www.sdrpp.org/nightly

**Comment by Derek000** [comment]
Thank you so much for the clarification.
Yes, I was using the older buld, using the nightly build provided the option. Sorry for the distraction.
