### ISSUE TITLE
Feature Request: keyboard shortcuts 

### ISSUE THREAD

**Issue by stevecrow74** [AlexandreRouma/SDRPlusPlus#720]
Any chance of adding shortcuts, play/stop, add new bookmark, radio mode, squelch on/off, direct sampling I/Q/Disabled, Bias T… etc etc.
Editable bookmarks would be even better although more involved setting it up.

**Comment by AlexandreRouma** [comment]
Existing keybinds are listed here: https://github.com/AlexandreRouma/SDRPlusPlus/wiki/UI-Controls
there is currently no plan to add more.
