### ISSUE TITLE
Study the SDRPlusPlus Code Without Installing

### ISSUE THREAD

**Issue by KGx55** [AlexandreRouma/SDRPlusPlus#723]
This is my first post and I hope it is ok.  I am hoping to study the Mac version of SDRPlusPlus to learn from it before attempting to build it.  I downloaded sdrpp_macos_amd64.pkg and unpacked it with the "pkgutil --expand" utility.  The result had a file titled Sdrpp.pkg, which I viewed with “show package contents.”  There, I could see three files.  Two of those files, Payload and Bom were encoded and I was not able to read them.  Is there a way to read the whole project code without installing the package?

**Comment by gvanem** [comment]
Why don't you download the sources instead:
`git clone https://github.com/AlexandreRouma/SDRPlusPlus.git <some_empty_directory>`

Or download the `.zip` from the frontpage.

**Comment by shuyuan-liu** [comment]
You could also read the code here online, for example https://github.com/AlexandreRouma/SDRPlusPlus/blob/master/core/src/gui/main_window.cpp.
