### ISSUE TITLE
Please document Windows Zadig for RTL-SDR

### ISSUE THREAD

**Issue by duk3luk3** [AlexandreRouma/SDRPlusPlus#731]
For someone who just wants to get started using RTL-SDR with SDR++, it is very hard to find out how to set up the RTL-SDR (e.g. googling for "RTL-SDR SDR++" finds no useful results).

The only step required other than plugging in the RTL-SDR Dongle and running SDR++ is to run Zadig: https://www.rtl-sdr.com/getting-the-rtl-sdr-to-work-on-windows-10/

Adding a link to that somewhere in the README would be very useful to help someone who is starting from scratch.

I personally use both windows and lots of linux flavors, so remembering the setup steps between all of them is a hassle.

Thanks!

**Comment by AlexandreRouma** [comment]
SDR++ is only a year and a half old, you won't find any result by googleing anything. 

The readme is not a manual, it doesn't tell you how to use the software, it's just there for how to install or build it. Considering the number of devices SDR++ supports, if I had to link usage instruction for every single one it would quickly get out of control.
