### ISSUE TITLE
[Feature request] Transmit capability

### ISSUE THREAD

**Issue by mike6000** [AlexandreRouma/SDRPlusPlus#737]
I would like to suggest transmit capability for SDR Pluto and similar SDR hardware that has both RX and TX capabilities. At the moment only SDR Sharp is able to do that and this is not a software suitable for remote ham radio operation.

**Comment by AlexandreRouma** [comment]
TX capability would be basically rewriting the entire software. It was never meant for TX and TX support is not planned
