### ISSUE TITLE
Rgictl server not support cmd

### ISSUE THREAD

**Issue by EeeLo** [AlexandreRouma/SDRPlusPlus#740]
I see the code and try to test, the rigctl server can not support the "l" and "l SQL" cmd, this cmd can get the value of squelch and signal level which can useed to search signal, there have some software can connect rigctl server and search freq, we can use for it if sdr++ support it,thanks.

**Comment by M0XFX** [comment]
Hi I am also having problems with SDR++ using the rigctl server. I am absolutely sure that Alex (The developer)  will be able to give you a much better picture than myself. I have taken a peak at the rigctl code and it looks to me like the only set and read back functions are available is for general Tuning which comprises of read / write of frequency , mode and VFO settings , I am not seeing much else unless I am mistaken. Note: The mode set for some reason does not seem to be working, well for me at least. For testing  I am accessing the SDR++ rigctl using a terminal emulator with Telnet protocol.  I am currently trying to build the source code latest rev to VS studio code so I can hopefully get to the bottom of the problem and possibly add more read / write options to the rigctl server.  I will keep you updated with any developments.
