### ISSUE TITLE
Ubuntu 22.04 Jammy Jellyfish - sdrpp won't start

### ISSUE THREAD

**Issue by kv5r** [AlexandreRouma/SDRPlusPlus#745]
Installed sdrpp_ubuntu_hirsute_amd64.deb in just-released Ubuntu Jammy. Won't start up.
sdrpp calls libGLEW.so.2.1 -- needs  libGLEW.so.2.2
sdrpp calls libvolk.so.2.4 -- needs libvolk.so.2.5
Workaround: Creating 2 symlinks in /lib/x86_64-linux-gnu fixes it, now starts and runs fine.
I think if the code just call "libGLEW.so" and "libvolk.so" it'd work fine; symlinks already there pointing to latest installed versions in Jammy.
73, --kv5r

**Comment by shuyuan-liu** [comment]
You installed the package for Hirsute. Have you tried the Jammy one? https://www.sdrpp.org/nightly

**Comment by delboy85341** [comment]
> You installed the package for Hirsute. Have you tried the Jammy one? https://www.sdrpp.org/nightly

I couldn't get SDR++ to work after upgrading from Ubuntu 20.04 to 22.04.  I found this forum and tried the link you suggested.  I found the jammy build at the bottom, but it wasn't a link.  How do I download the jammy build? thanks

**Comment by shuyuan-liu** [comment]
The download links can be a bit tricky to find, make sure you scroll down the page to the Artifacts section where the downloads are located.

![image](https://user-images.githubusercontent.com/41851763/191701206-b48365af-989b-4b24-a862-99b374964d6e.png)
