### ISSUE TITLE
README should mention nightly, or make more releases

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#748]
#745, #747, #759, and #760 indicate many users are unaware of nightly builds, and run into problems when using the very old release version. In fact the main README doesn't mention "nightly" anywhere.

I think it would be useful to either prominently mention nightly builds, or to make more frequent releases.

(Originally about Ubuntu Jammy Jellyfish, but later discovered in Issues and Discussions that plenty of users are still on 1.0.4 on all platforms)

**Comment by JoshuaKimsey** [comment]
I do agree, I had no clue about there being Nightly Builds (or even a website for SDR++), so it definitely should be mentioned somewhere on the main GitHub page.

**Comment by JosephTheTank13** [comment]
wait there's a website now?

**Comment by shuyuan-liu** [comment]
Yes https://www.sdrpp.org/

**Comment by maiestro** [comment]
Somehow I am too stupid to find the download link for the nightly builds, can someone give me a hint to find the ubuntu jammy .deb package from the github actions page?

Would be great, thank you very much!

**Comment by shuyuan-liu** [comment]
> Somehow I am too stupid to find the download link for the nightly builds, can someone give me a hint to find the ubuntu jammy .deb package from the github actions page?
> 
> Would be great, thank you very much!

- Go to the Actions page
- Open the latest build marked successful (green check mark)
- Scroll down to Artifacts i.e. packages built
- Click on the package you need. In your case, `sdrpp_ubuntu_jammy_amd64`.

**Comment by loewal** [comment]
And you have to login first. This means, you need to have (made) a Github account.

Loe Walter
Insula 103
6416 BZ  Heerlen
☎️ +31-6-24476963

**Comment by maiestro** [comment]
Thanks you guys @shuyuan-liu and @loewal for your support,
I'm logged in, but I cant see any files, just log files :

![1](https://user-images.githubusercontent.com/2205262/184343541-2abaabd0-ae3f-4063-a0f7-4062d1dd3ba7.png)
![2](https://user-images.githubusercontent.com/2205262/184343566-2202e32b-167a-4d38-9e05-6ca4822f6d5b.png)
![3](https://user-images.githubusercontent.com/2205262/184343764-dd59df5d-c212-43fb-9b2d-4c3a7baa223a.png)

**Comment by loewal** [comment]
I the right portion of the screen you can scroll further down.

**Comment by maiestro** [comment]
Oh my god, you are totally right, sorry.

Now i see that too - the scrolling with the mouse was in the build_all.yml area as zoom. I with my small screen thought that would already be the end of the page. Thank you :)

**Comment by loewal** [comment]
Sorry, use the scrollbar otherwise scrolling sometimes doesn’t work

**Comment by mmrein** [comment]
The "must login" part got me. Did try without it and was wondering why is there file list without posibility to dowload them. Ended up building from source for Jammy...

**Comment by shuyuan-liu** [comment]
Closing since the readme now mentions nightly builds so the original issue has been resolved.
