### ISSUE TITLE
[cosmetic] white icons have low visibility with the light theme

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#751]
Using the light theme, these white button icons are difficult to see on the light background:

![image](https://user-images.githubusercontent.com/41851763/166223439-73815738-3a25-4f55-a3e2-138a41b8a3b8.png)

Although they look OK in isolation, they have much lower contrast than in the dark themes. It also feels odd to have white button icons when all other text is black.

The icons are currently PNGs with fixed colours. Would it be more flexible to implement them as vector graphics with colours specified by themes (either seperately or simply the same as text colour)?

**Comment by OttoPattemore** [comment]
ImGui::ImageButtons have a tint argument which can be used to color an image.
It multiples every pixel by the tint.

Here we are using the current theme text color as the tint ( `` ImGui::GetStyleColorVec4(ImGuiCol_Text) ``).
```c++
ImGui::ImageButton(icons::PLAY, btnSize, ImVec2(0, 0), ImVec2(1, 1), 5,ImVec4(0,0,0,0),ImGui::GetStyleColorVec4(ImGuiCol_Text))
```
Modified line 382 in main_window.cpp


In light mode:
![image](https://user-images.githubusercontent.com/57029490/166416905-fe2149a8-4e37-4d8d-9394-92ade22c091d.png)

In dark mode:
![image](https://user-images.githubusercontent.com/57029490/166416990-fe7e60f5-34cc-46a1-bbd4-65a64f16a018.png)

**Comment by shuyuan-liu** [comment]
This looks quite good. @AlexandreRouma would you like to implement it this way?

**Comment by AlexandreRouma** [comment]
I'll try to implement this if I get some free time, extremely busy at the moment and can't go over pull requests
