### ISSUE TITLE
Fix / Workaround for M1 Chip

### ISSUE THREAD

**Issue by ChrisDev8** [AlexandreRouma/SDRPlusPlus#756]
# When running CMAKE command as stated in the documentation, it creates this error multiple times with different modules.
# OS: MAC M1 OSX; Version: MacOS Monterey 12.1

## Short Error:
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
    Reason given by package: The command
      "/usr/lib/pkgconfig" --version
    failed with output:

    stderr: 
      
    result: 
Permission denied
```

## Complete Error:

https://pastebin.com/Yp8unJeR
**Password**: d12FSfZ0aQ

**Comment by ChrisDev8** [comment]
Tried sudo prefix
Everything else too complicated.
Also I've had really bad luck using cmake for ANY other programs.

**Comment by ChrisDev8** [comment]
# I GOT IT; YES YES YES

## SHORT: https://bit.ly/3wp8k1t

## RAW: https://nightly.link/AlexandreRouma/SDRPlusPlus/workflows/build_all.yaml/master/sdrpp_macos_intel.zip

**Comment by AlexandreRouma** [comment]
see https://github.com/AlexandreRouma/SDRPlusPlus/discussions/757#discussioncomment-2740822 for instructions on how to get the MacOS nightly.
