### ISSUE TITLE
Add PlutoSDR LPF Configuration

### ISSUE THREAD

**Issue by longview** [AlexandreRouma/SDRPlusPlus#768]
At present it seems the hardware low pass filter is not configured for PlutoSDR devices, I'm not sure what the power on default is but it ended up being 6 MHz for me.

Setting this filter based on sampling rate would likely improve performance. There is also the Pluto+ SDR which can (in practice) support higher rates than the stock ADI implementation, and at high rates the default LPF can end up being too narrow.

The relevant IIO parameter is in_voltage_rf_bandwidth. On the command line it can be set with:

echo n>  /sys/bus/iio/devices/iio\:device0/in_voltage_rf_bandwidth

Where n is the cutoff frequency in Hz, around 75% of sample rate seems appropriate. 
Alternately it could be a user set parameter, though I think automatic is fine for most users.

**Comment by AlexandreRouma** [comment]
combining with the older #563, follow that one instead
