### ISSUE TITLE
AppImage release

### ISSUE THREAD

**Issue by Miki994** [AlexandreRouma/SDRPlusPlus#769]
Can you please make AppImage release for SDR++ ? 
Currently i am using Void Linux distro and xbps package is not available.
The best and convenient way to run SDR ++ on other distros will be AppImage (portable app)
This will help also with less packages to be downloaded and make distro slim and bloat-free.

**Comment by AlexandreRouma** [comment]
Duplicate of #286

Support for AppImage is not planned.
