### ISSUE TITLE
LNA gain control not functioning for RSPduo

### ISSUE THREAD

**Issue by flocentblack** [AlexandreRouma/SDRPlusPlus#781]
LNA gain control not functioning for RSPduo.  No change in noise floor when moved.

SDR++ 1.0.6

**Comment by flocentblack** [comment]
Upon further experimentation, the issue is intermittent, although I can never get LNA when to operate when using LowIF 2048KHz, IFBW 1536KHz.

Toggling through the other modes will sometimes get it working again.

**Comment by AlexandreRouma** [comment]
likely an issue with the API and not SDR++
