### ISSUE TITLE
Macos latest nos sound

### ISSUE THREAD

**Issue by loewal** [AlexandreRouma/SDRPlusPlus#788]
Hi Alexandre

The macos version of yesterday has no sound anymore.
I also installed the version before that and that was okay.

Is it therefore that you call it "MacOS do be wasting my time"? ;-)

**Comment by ja-Bertolin** [comment]
I hope it does not ... this is the unique and the best version of SDR software for MacOS ... if @AlexandreRouma is not going to support MacOS anymore due to the effort required it will be a pity and we, MacOS users, will be out of the SDR game.

**Comment by loewal** [comment]
Never tried SDRangel?

**Comment by ja-Bertolin** [comment]
No, is it worthwhile for MacOS?

**Comment by loewal** [comment]
Perfect!
Standalone app:
https://github.com/f4exb/sdrangel/tags

Or this one
Webbased:
https://github.com/jketterl/openwebrx
Regards

On 20 Jun 2022, 18:30 +0200, ja-Bertolin ***@***.***>, wrote:
	No, is it worthwhile for MacOS?

**Comment by ja-Bertolin** [comment]
thanks, Just tested and it is very unfriendly app ... very difficult to configure and make it run ... SDR++ is much more friendly....

**Comment by AlexandreRouma** [comment]
You realize it's a completely different branch (`new_dsp`) for a reason right?
It's has nothing to do with dropping support for MacOS.
I just can't fix any macOS issue because I don't own a mac.

**Comment by pbij2001** [comment]
I brought audio back to life on Mac Catalina by copying the old audio_sink.dylib abd new_portaudio_sink.dylib in the plugins folder. (both from april 22)

Why it works now I don't know but it works.

**Comment by ja-Bertolin** [comment]
Thanks! it worked like a charm...

**Comment by AlexandreRouma** [comment]
Fixed
