### ISSUE TITLE
Selecting NFM demod causes v1.1.0 crash

### ISSUE THREAD

**Issue by mebrown47** [AlexandreRouma/SDRPlusPlus#790]
On the v1.1.0  focal deb build, if the NFM demod is selected the program closes.

sdrpp: /root/SDRPlusPlus/core/src/signal_path/../dsp/channel/../processor.h:58: void dsp::Processor<I, O>::setInput(dsp::stream<I>*) [with I = dsp::complex_t; O = dsp::stereo_t]: Assertion `_block_init' failed.
Aborted (core dumped)

**Comment by AlexandreRouma** [comment]
known issue in the process of bejng fixed

**Comment by AlexandreRouma** [comment]
Fixed
