### ISSUE TITLE
Only set CMAKE_INSTALL_PREFIX when it isn't supplied by the caller

### ISSUE THREAD

**Issue by yurivict** [AlexandreRouma/SDRPlusPlus#792]
[here](https://github.com/AlexandreRouma/SDRPlusPlus/blob/master/CMakeLists.txt#L7)

The whole section should be conditional on ```CMAKE_INSTALL_PREFIX``` not being defined:
```
if (${CMAKE_INSTALL_PREFIX} EQUAL "")
    if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        set(CMAKE_INSTALL_PREFIX "/usr/local")
    else()
       set(CMAKE_INSTALL_PREFIX "/usr")
    endif()
endif()
```

**Comment by yurivict** [comment]
So these distros are broken. You shouldn't cater to broken distributions IMO.

**Comment by AlexandreRouma** [comment]
I'm just one uni student writing this software, I don't have time to deal with thousands of users having issues installing the thing.
I'd rather have a path that works on any unix OS. The only people that will be annoyed by it have the skills to edit the cmakelists and change it to whatever they want.

**Comment by yurivict** [comment]
I am currently in my FreeBSD ports maintainer and commiter hat.
And I've seen literally hundreds of cmake projects that "just work" (TM) and don't require patching out pre-set "/usr" in CMakeLists.txt

You've probably hit one random bad case and made too general conclusions, IMO.

**Comment by AlexandreRouma** [comment]
Was implemented a while back
