### ISSUE TITLE
Display Issue macOS

### ISSUE THREAD

**Issue by Pytlicek** [AlexandreRouma/SDRPlusPlus#794]
**OS:** macOS Monterey 12.4 on MacBook Pro 16" 2019
**Build used:** https://github.com/AlexandreRouma/SDRPlusPlus/actions/runs/2545681172

**Description:**
You can horizontally scroll the left sidebar by 2-fingers gesture on macOS and you will see `AGC Decay` text on a blank background, as you can see on the screenshot below. YT video: https://youtu.be/IvYooflQOLg

<img width="574" alt="Screenshot 2022-06-23 at 23 12 37" src="https://user-images.githubusercontent.com/1430522/175402540-afe1e2ce-6067-4176-a2cb-d96147973d26.png">

**Comment by AlexandreRouma** [comment]
Looks like  forgot to remove the right text, will push a fix

**Comment by AlexandreRouma** [comment]
fixed

**Comment by Pytlicek** [comment]
Thanks. It works as expected now 👍
