### ISSUE TITLE
Does not work on ubuntu 22.04

### ISSUE THREAD

**Issue by TS440S** [AlexandreRouma/SDRPlusPlus#799]
It seems Glew is causing issues again on 22.04.

`sdrpp: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory`

**Comment by AlexandreRouma** [comment]
update to the nightly

**Comment by mitchy93** [comment]
install these packages manually
https://packages.debian.org/bullseye/libvolk2.4
https://debian.pkgs.org/11/debian-main-amd64/libglew2.1_2.1.0-4+b1_amd64.deb.html (**arm64 version also in this url**)

it opened fine after that

**Comment by JosephTheTank13** [comment]
I compiled it and it worked.
