### ISSUE TITLE
SDR++ doesn't launch on Windows 10 Pro

### ISSUE THREAD

**Issue by 7zx** [AlexandreRouma/SDRPlusPlus#800]
When i click on the executable, it just opens a terminal really quickly, then it closes, then it doesn't open.
**My specs:** Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz 2.59 GHz, 16gb RAM.

**Comment by pdxh0b0** [comment]
> When i click on the executable, it just opens a terminal really quickly, then it closes, then it doesn't open. **My specs:** Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz 2.59 GHz, 16gb RAM.

try deleting the config.json

**Comment by hseifert4711** [comment]
same on windows 11 Pro, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
deleting config.jason did not change anything

**Comment by aosync** [comment]
Could you provide more information? Such as the version of SDR++ you are using as well as the logs.

**Comment by aosync** [comment]
Closing as stale, please reopen if the issue persists; notably in newer versions.
