### ISSUE TITLE
Any easy way to build with windows

### ISSUE THREAD

**Issue by EeeLo** [AlexandreRouma/SDRPlusPlus#804]
Any easy way to building on windows? config software is so sick

**Comment by AlexandreRouma** [comment]
Everything is explained in the readme: https://github.com/AlexandreRouma/SDRPlusPlus#building-on-windows
It can't be made any easier, software development is not trivial.
If this is too complicated, I recommend getting the nightly builds instead which are always up to date with the master branch: https://www.sdrpp.org/nightly
