### ISSUE TITLE
No audio output on Pop OS 22.04

### ISSUE THREAD

**Issue by JosephTheTank13** [AlexandreRouma/SDRPlusPlus#805]
As of POP 22.04 They switched from Pulse Audio to Pipewire, or some hybrid of the two since PAVUctl still works. SDR++ only works when outputting audio to my Signalink but doesn't work for any of my other sound devices.
![image](https://user-images.githubusercontent.com/28242145/178154719-eb95f229-4ef3-46a3-8810-be8a124fc61a.png)
It shows several "Pulse Audio Volume Control" Entries and it shows my signalink twice for some reason. No audio comes out when selecting any of the copied entires.

**Comment by AlexandreRouma** [comment]
Try this: https://github.com/AlexandreRouma/SDRPlusPlus/discussions/112
If it doesn't work, report to the RtAudio developers. SDR++ does not deal with any audio server directly so there is nothing I can do.
