### ISSUE TITLE
SDR++ crashing when stopping, then starting Hackrf on Mac

### ISSUE THREAD

**Issue by bvogt3000** [AlexandreRouma/SDRPlusPlus#808]
I am just wondering if there is a workaround to avoid this issue? Is it a bug or is it normal? I am on the nightly build version 1.1.0 (built at 14:27:22, Jul 11 2022). 
Any help would be appreciated, thanks.

**Comment by AlexandreRouma** [comment]
See the troubleshooting section of the readme.
The solution is to remove the SoapySDR source module by deleting its instance in the module manager menu

**Comment by bvogt3000** [comment]
Thanks for getting back to me. 
Yes, I had seen that in the readme, but I do not see the SoapySDR module on the macOS version. I am looking in the module manager, and in the plugins folder location within the app. Should I be looking somewhere else? 

<img width="269" alt="Screen Shot 2022-07-13 at 2 22 29 PM" src="https://user-images.githubusercontent.com/91347504/178815104-89cf2117-c56a-4335-8bf8-50bdb0e57132.png">
<img width="277" alt="Screen Shot 2022-07-13 at 2 21 53 PM" src="https://user-images.githubusercontent.com/91347504/178815112-2680c349-b3e9-4893-99d0-163cad4b65ff.png">
<img width="979" alt="Screen Shot 2022-07-13 at 2 23 00 PM" src="https://user-images.githubusercontent.com/91347504/178815114-2c8abbc2-9a3f-46d6-8f7e-96262b6744a1.png">

**Comment by AlexandreRouma** [comment]
nothing I can do unfortunately

**Comment by bvogt3000** [comment]
Ok, that is unfortunate. Thanks for your help and the awesome app!
