### ISSUE TITLE
need help for compile on macos

### ISSUE THREAD

**Issue by BG7JAF** [AlexandreRouma/SDRPlusPlus#81]
Hello, I try to compile this program on macos. compiling is ok, but when linking error occus. Here I upload the error log, how can I fix this error? thx

platform: macos 10.15.7

[log.txt](https://github.com/AlexandreRouma/SDRPlusPlus/files/6176855/log.txt)

**Comment by AlexandreRouma** [comment]
Hello, clang is currently not supported.
Please use GCC instead.
MacOS support is general is a bit wonky atm since I don't have a VM to test it.

**Comment by kd5ftn** [comment]
> MacOS support is general is a bit wonky atm since I don't have a VM to test it.

@AlexandreRouma You might be interested in https://snapcraft.io/sosumi

**Comment by AlexandreRouma** [comment]
> 
> 
> > MacOS support is general is a bit wonky atm since I don't have a VM to test it.
> 
> @AlexandreRouma You might be interested in https://snapcraft.io/sosumi

Unfortunately, my main PC runs windows and my linux PC isn't fast enough to run a MacOS VM :/
