### ISSUE TITLE
“volk/volk.h”: No such file or directory

### ISSUE THREAD

**Issue by EeeLo** [AlexandreRouma/SDRPlusPlus#812]
when I building with windows, error with “volk/volk.h”: No such file or directory, anyother library need ?

**Comment by EeeLo** [comment]
I reinstall the pothosSDR and done, but RtAudio.h not found , I already build it in C:/Program Files (x86)/RtAudio/ , and system path

**Comment by AlexandreRouma** [comment]
It's not installed properly, the `.lib` files are expected in `C:/Program Files (x86)/RtAudio/lib` and the headers in `C:/Program Files (x86)/RtAudio/include/rtaudio`.
