### ISSUE TITLE
Feature Request: integrate rtl_433 decoder as new module

### ISSUE THREAD

**Issue by LEDFlighter** [AlexandreRouma/SDRPlusPlus#817]
It would be great if the rtl_433 decoder could be integrated in SDR++ as a new module to decode everything in the ISM-Bands.

**Comment by AlexandreRouma** [comment]
I am not ok with having core modules that depend on external software.
Moreover having RTL-433 as a module doesn't make much sense, it's single purpose, might as well just run it directly on the SDR.
