### ISSUE TITLE
Feature Request: more maximum available bandwith for demodulation

### ISSUE THREAD

**Issue by LEDFlighter** [AlexandreRouma/SDRPlusPlus#818]
Depending on the demodulation mode you are using, there is only 500 Hz, 12kHz, 15 kHz, 50 kHz or 250 kHz available as a maximum. For some cases it is useful (or mandatory) to be able to use much more bandwith and don't be limited to this rather small bandwiths.
SDR# can handle up to several MHz simultaneously! I want way more available bandwith for the demodulator (radio).

**Comment by AlexandreRouma** [comment]
The bandwidth are limited by the demodulator samplerate which is not dynamically adjustable and setting it higher wastes CPU.
There is never a need for a higher bandwidth than given for the intended use of the demodulators.
+ SDR# does *not* allow you to set VFOs to several MHz, that would be completely and utterly stupid.

If something needs more bandwidth, it's probably something that should have its own module instead.
