### ISSUE TITLE
Matrix bridged with Discord

### ISSUE THREAD

**Issue by uranuspucksaxophone** [AlexandreRouma/SDRPlusPlus#826]
**Feature description**

**Comment by AlexandreRouma** [comment]
I don't understand what you're asking for here

**Comment by AlexandreRouma** [comment]
I know that but I have no idea what the feature request is about. What does that have to do with SDR++...

**Comment by AlexandreRouma** [comment]
After consideration, I do not have the time to manage and moderate a matrix channel in addition to the existing discord.
