### ISSUE TITLE
Debian library versions are not specified in the deb file

### ISSUE THREAD

**Issue by meeas** [AlexandreRouma/SDRPlusPlus#827]
There is a Debian package for Debian Sid, however the deb package does not specify the required versions of each library.  This causes the installation to install the wrong libraries than needed and appears to install successfully.  I would find it much more preferable to get an error on install saying the version X.X.X of your library was not available in the repository, which would provide more information to users on what version they need to go hunt down.

**Comment by AlexandreRouma** [comment]
you're not supposed to change the library versions, you're supposed to install the nightly instead: https://www.sdrpp.org/nightly
Obviously releases won't keep being up to date with a rolling release distro.
