### ISSUE TITLE
Decimation WAV

### ISSUE THREAD

**Issue by zeke800** [AlexandreRouma/SDRPlusPlus#828]
When using the decimation feature to record, SDR++ records at the original sample rate. This is seen during the WAV file playback, when it plays faster than normal. For example, when receiving Meteor (excuse the local VHF noise), the recording was decimated by 4 in SDR++. However, the bandwidth does not even remotely fit. Any advice would be appreciated. 
![image](https://user-images.githubusercontent.com/82127189/182261643-e0ef5d81-c014-4c89-8885-b9882aae2974.png)

**Comment by zeke800** [comment]
Thank you! However, is there a way to convert the existing recordings?

**Comment by AlexandreRouma** [comment]
you either have to divide the samplerate and bytesPerSecond fields of the wav header by 4 or use GNU radio to read the wav as raw IQ data and rewrite it with the correct samplerate.
