### ISSUE TITLE
"Highest" sink volume controls master volume

### ISSUE THREAD

**Issue by scottjpalmer** [AlexandreRouma/SDRPlusPlus#838]
**Hardware**
- SDR: RTL-SDR local

**Software**
- Operating System: Windows 11 x64
- SDR++: v1.1.0 23:15 Aug 2

**Bug Description**
When using multiple VFOs, adjusting the volume in the sink nearest the top of the Sinks module of the active VFOs adjusts the master volume. Deactivating that VFO causes the master volume to change to the volume of the next highest sink.

**Comment by AlexandreRouma** [comment]
Not a bug, volume on top only adjusts the volume of the selected VFO. there is no master volume in SDR++.
