### ISSUE TITLE
How to add SoapySDR to prebuilt MacOs bundle? 

### ISSUE THREAD

**Issue by kbwrx** [AlexandreRouma/SDRPlusPlus#841]
Hello, 

Thank you for this amazing project. I was wondering if it possible to add the SoapySDR/SoapyAudio module to the nightly prebuilds? Do I have to compile from source instead? I have a StarTech ICUSBAUDIO2D external USB soundcard I would like to use to capture within SDR++. I appreciate any advice. 

Thank you, 

Keith

**Comment by AlexandreRouma** [comment]
Supporting SoapySDR on MacOS is not possible. SoapySDR has to be installed, it can't be shipped inside the bundle like other libraries. I suggest waiting for Audio inputs to be implemented (not sure when it'll happen, soundcard SDRs aren't a priority).
