### ISSUE TITLE
Very hard to resize individual panels

### ISSUE THREAD

**Issue by Lostboyzz** [AlexandreRouma/SDRPlusPlus#845]
Hi
Fantastic program, but its very difficult to resize areas,  like the waterfall and such.
Android galaxy s9+

**Comment by AlexandreRouma** [comment]
This is a know issue mentioned in the post of the prerelease:
> - Resizing the menu and/or waterfall is kinda fiddly, be precise when trying to grab the resize bar!!!

Support of the android build is on halt at the moment. Refer to the android release thread (#703) for more info.
