### ISSUE TITLE
Doesn't Work under Mint Vanessa

### ISSUE THREAD

**Issue by Lesprilibre** [AlexandreRouma/SDRPlusPlus#848]
Hi ! And thanks again for you software !
Yesterday I've update Mint Una (20.3) to Vanessa (21), it seems that, after update, I've got some trouble with LibGlew again.

Rolling back to Una (thanks to Timeshift) everything run fine... Doesn't anyone encounter this kind of trouble ?

**Comment by AlexandreRouma** [comment]
Expected as the library versions are different.
Get the [nightly](https://www.sdrpp.org/nightly) for the ubuntu version that corresponds to the new mint version.

**Comment by Lesprilibre** [comment]
Thanks Alexandre !

Le dim. 21 août 2022, 16:46, AlexandreRouma ***@***.***> a
écrit :
