### ISSUE TITLE
Ubuntu Studio 22.04 missing dependencies 

### ISSUE THREAD

**Issue by pauluzs** [AlexandreRouma/SDRPlusPlus#849]
Trying to install the SDRpp .deb package on Ubuntu Studio 22.04 as given in the [readme.md](https://github.com/AlexandreRouma/SDRPlusPlus/blob/master/readme.md) will remove some base components that make up ubuntu studio

```
sdrpp@ubuntu-studio:~$ sudo apt install libfftw3-dev libglfw3-dev libvolk2-dev libsoapysdr-dev libairspyhf-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev
...
Recommended packages:
  qjackctl
The following packages will be REMOVED:
  agordejo jack-keyboard jack-mixer jack-tools jackd jackd2 jackd2-firewire
  libjack-jackd2-0 mcpdisp meterbridge qjackctl qtractor rakarrack
  studio-controls ubuntustudio-default-settings ubuntustudio-desktop
  ubuntustudio-installer ubuntustudio-menu
The following NEW packages will be installed:
  bladerf jackd1 
...
```

Adding `libjack-jackd2-dev libzstd-dev`  will fix this.

To install sdrpp without breaking the studio parts :

```
sudo apt install libfftw3-dev libglfw3-dev libvolk2-dev libsoapysdr-dev libairspyhf-dev libiio-dev libad9361-dev librtaudio-dev libhackrf-dev libjack-jackd2-dev libzstd-dev

sudo dpkg -i sdrpp_debian_amd64.deb

volk_profile
```
Just sharing the info
Pauluzs

**Comment by AlexandreRouma** [comment]
It's not really about missing dependencies, it's about the `rtaudio-dev` package being maintained by idiots.

I suggest just telling the ubuntu maintainers to have a look at the rtaudio package and have it not try to uninstall half the system's audio components...
