### ISSUE TITLE
Crash on startup under CrossOver (WINE) on Ubuntu 22

### ISSUE THREAD

**Issue by dslotter** [AlexandreRouma/SDRPlusPlus#852]
Yes, I know there's a Linux version. I wanted to try the Windows version under CrossOver (WINE).

**Hardware**
- CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics
- RAM: 48 GB
- GPU: AMD/ATI Radeon
- SDR: Local - SDRPlay

**Software**
- Operating System: Windows 10 x64 under CrossOver (WINE)
- SDR++: 1.1.0 Nightly build August 2, 2022

**Bug Description**
Crash on startup

**Steps To Reproduce**
1. Start application
2. Observe crash

**Additional info**

Console log:
[2022-08-24 12:57:23.990] [info] SDR++ v1.1.0
[2022-08-24 12:57:23.990] [info] Loading config
[2022-08-24 12:57:24.132] [info] Using OpenGL 3.0
[2022-08-24 12:57:24.200] [info] Loading icons
[2022-08-24 12:57:24.208] [info] Loading band plans
[2022-08-24 12:57:24.211] [info] Loading band plans color table
[2022-08-24 12:57:24.216] [info] Loading modules
[2022-08-24 12:57:24.217] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/airspyhf_source.dll
[2022-08-24 12:57:24.220] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/airspy_source.dll
[2022-08-24 12:57:24.221] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/audio_sink.dll
[2022-08-24 12:57:24.224] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/bladerf_source.dll
[2022-08-24 12:57:24.261] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/discord_integration.dll
[2022-08-24 12:57:24.262] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/file_source.dll
[2022-08-24 12:57:24.263] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/frequency_manager.dll
[2022-08-24 12:57:24.264] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/hackrf_source.dll
[2022-08-24 12:57:24.265] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/limesdr_source.dll
[2022-08-24 12:57:24.267] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/m17_decoder.dll
[2022-08-24 12:57:24.269] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/meteor_demodulator.dll
[2022-08-24 12:57:24.270] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/network_sink.dll
[2022-08-24 12:57:24.271] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/plutosdr_source.dll
[2022-08-24 12:57:24.274] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/radio.dll
[2022-08-24 12:57:24.275] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/recorder.dll
[2022-08-24 12:57:24.276] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/rfspace_source.dll
[2022-08-24 12:57:24.277] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/rigctl_server.dll
[2022-08-24 12:57:24.278] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/rtl_sdr_source.dll
[2022-08-24 12:57:24.279] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/rtl_tcp_source.dll
[2022-08-24 12:57:24.280] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/sdrplay_source.dll
[2022-08-24 12:57:24.337] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/sdrpp_server_source.dll
[2022-08-24 12:57:24.338] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/soapy_source.dll
[2022-08-24 12:57:24.340] [error] Couldn't load C:/Program Files/sdrpp_windows_x
64/modules/soapy_source.dll. Error code: 126
[2022-08-24 12:57:24.340] [info] Loading C:/Program Files/sdrpp_windows_x64/modu
les/spyserver_source.dll
[2022-08-24 12:57:24.341] [info] Initializing Airspy Source (airspy_source)
[2022-08-24 12:57:24.347] [info] Initializing AirspyHF+ Source (airspyhf_source)
[2022-08-24 12:57:24.354] [info] Initializing Audio Sink (audio_sink)
[2022-08-24 12:57:24.354] [info] Initializing BladeRF Source (bladerf_source)
[2022-08-24 12:57:24.365] [error] Could not list devices -7
[2022-08-24 12:57:24.365] [info] Initializing File Source (file_source)
[2022-08-24 12:57:24.370] [info] Initializing Frequency Manager (frequency_manag
er)
[2022-08-24 12:57:24.370] [info] Initializing HackRF Source (hackrf_source)
[2022-08-24 12:57:24.376] [info] Initializing LimeSDR Source (limesdr_source)
[2022-08-24 12:57:24.376] [info] Initializing Network Sink (network_sink)
[2022-08-24 12:57:24.377] [info] Initializing PlutoSDR Source (plutosdr_source)
[2022-08-24 12:57:24.378] [info] Initializing RFspace Source (rfspace_source)
[2022-08-24 12:57:24.378] [info] Initializing RTL-SDR Source (rtl_sdr_source)
[2022-08-24 12:57:24.380] [info] Initializing RTL-TCP Source (rtl_tcp_source)
[2022-08-24 12:57:24.381] [info] Initializing Radio (radio)
[Resamp] predec: 32, interp: 4, decim: 5, inacc: 0.000000%, taps: 380
[Resamp] predec: 4, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[Resamp] predec: 32, interp: 5000, decim: 7813, inacc: 0.000000%, taps: 593750
[Resamp] predec: 4, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
[Resamp] predec: 4, interp: 441, decim: 625, inacc: 0.000000%, taps: 47500
[2022-08-24 12:57:24.628] [warning] Demod switch took 93681 us
[2022-08-24 12:57:24.629] [info] RtAudio stream open
[2022-08-24 12:57:24.629] [info] Initializing Recorder (recorder)
[2022-08-24 12:57:24.630] [info] Initializing Rigctl Server (rigctl_server)
[2022-08-24 12:57:24.631] [info] Initializing SDR++ Server Source (sdrpp_server_
source)
[2022-08-24 12:57:24.635] [info] Initializing SDRplay Source (sdrplay_source)
[2022-08-24 12:57:24.637] [error] Could not intiatialized the SDRplay API. Make
sure that the service is running.
[2022-08-24 12:57:24.637] [info] Initializing SoapySDR Source (soapy_source)
[2022-08-24 12:57:24.638] [error] Module 'soapy_source' doesn't exist
[2022-08-24 12:57:24.638] [info] Initializing SpyServer Source (spyserver_source
)
[2022-08-24 12:57:24.640] [info] Loading color maps
[2022-08-24 12:57:24.642] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/classic.json
[2022-08-24 12:57:24.643] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/classic_green.json
[2022-08-24 12:57:24.644] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/electric.json
[2022-08-24 12:57:24.646] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/gqrx.json
[2022-08-24 12:57:24.647] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/greyscale.json
[2022-08-24 12:57:24.648] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/inferno.json
[2022-08-24 12:57:24.649] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/magma.json
[2022-08-24 12:57:24.649] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/plasma.json
[2022-08-24 12:57:24.651] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/turbo.json
[2022-08-24 12:57:24.654] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/viridis.json
[2022-08-24 12:57:24.655] [info] Loading C:/Program Files/sdrpp_windows_x64/res/
colormaps/websdr.json

*** Debug info: ***

Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x00000025251f33).
Register dump:
 rip:0000000025251f33 rsp:000000004ce5fbc0 rbp:000000000000ac44 eflags:00010202 (  R- --  I   - - - )
 rax:0000000080040154 rbx:000000000bdac678 rcx:0000000000000000 rdx:000000002525c9f0
 rsi:0000000000000001 rdi:000000000bdac650  r8:000000000bdac658  r9:000000017006da5c r10:000000017006d960
 r11:0000000000000246 r12:000000000bdac660 r13:000000000bdac670 r14:000000000bdac668 r15:0000000000000020
Stack dump:
0x0000004ce5fbc0:  000000002525d650 000000004ce5fca0
0x0000004ce5fbd0:  000000004ce5fca0 0000000067646d4e
0x0000004ce5fbe0:  000000000bdac650 0000000000000040
0x0000004ce5fbf0:  0000000000000000 0000000000000000
0x0000004ce5fc00:  0000000000000000 000000000ba96550
0x0000004ce5fc10:  000000000bdac640 000000000ba96400
0x0000004ce5fc20:  000000004ce5fd30 00000000252581c4
0x0000004ce5fc30:  000000000bdac640 000000000ba96501
0x0000004ce5fc40:  0000000000000000 0000000000000002
0x0000004ce5fc50:  000000000000ac44 000000000000ac44
0x0000004ce5fc60:  0000000000000000 0000000000000000
0x0000004ce5fc70:  0000000100000000 0000000000000000
Backtrace:
=>0 0x00000025251f33 ??0RtApi@@QEAA@XZ+0x503() in rtaudio (0x0000000000ac44)
  1 0x000000252581c4 ??0RtApi@@QEAA@XZ+0x6794() in rtaudio (0x0000004ce5fd30)
  2 0x0000002525708e ??0RtApi@@QEAA@XZ+0x565e() in rtaudio (0000000000000000)
  3 0x0000007b62c229 ActivateActCtx+0x20649() in kernel32 (0000000000000000)
  4 0x0000017005daf2 A_SHAFinal+0x3cdf2() in ntdll (0000000000000000)
0x00000025251f33 rtaudio+0x1f33: movq	(%rcx),%rax
Modules:
Module	Address					Debug info	Name (177 modules)
PE	0000000000430000-00000000006c2000	Deferred        volk
PE	00000000006d0000-000000000070c000	Deferred        glfw3
PE	0000000000710000-0000000001040000	Deferred        shell32
PE	0000000001040000-0000000001127000	Deferred        fftw3f
PE	0000000001130000-00000000011c9000	Deferred        zstd
PE	0000000024cf0000-0000000024d2c000	Deferred        airspyhf_source
PE	0000000024d30000-0000000024d5c000	Deferred        airspyhf
PE	0000000024d60000-0000000024d84000	Deferred        libusb-1.0
PE	0000000024d90000-0000000024da9000	Deferred        pthreadvc2
PE	0000000024fb0000-0000000024fee000	Deferred        airspy_source
PE	0000000024ff0000-0000000025005000	Deferred        airspy
PE	0000000025210000-000000002524c000	Deferred        audio_sink
PE	0000000025250000-0000000025266000	Export          rtaudio
PE	0000000025470000-00000000254ae000	Deferred        bladerf_source
PE	00000000254b0000-0000000025566000	Deferred        bladerf
PE	0000000025770000-00000000257bd000	Deferred        discord_integration
PE	00000000257c0000-0000000025809000	Deferred        file_source
PE	0000000025a10000-0000000025a80000	Deferred        frequency_manager
PE	0000000025c80000-0000000025cbc000	Deferred        hackrf_source
PE	0000000025cc0000-0000000025cd4000	Deferred        hackrf
PE	0000000025ee0000-0000000025f1d000	Deferred        limesdr_source
PE	0000000025f20000-0000000026023000	Deferred        limesuite
PE	0000000026230000-0000000026256000	Deferred        m17_decoder
PE	0000000026460000-00000000264a6000	Deferred        meteor_demodulator
PE	00000000266b0000-00000000266ee000	Deferred        network_sink
PE	00000000268f0000-000000002692b000	Deferred        plutosdr_source
PE	0000000026930000-0000000026acb000	Deferred        libiio
PE	0000000026ad0000-0000000026cab000	Deferred        libad9361
PE	0000000026eb0000-0000000026f0b000	Deferred        radio
PE	0000000027110000-0000000027161000	Deferred        recorder
PE	0000000027370000-00000000273b0000	Deferred        rfspace_source
PE	00000000275b0000-00000000275f0000	Deferred        rigctl_server
PE	00000000277f0000-000000002782f000	Deferred        rtl_sdr_source
PE	0000000027830000-000000002784b000	Deferred        rtlsdr
PE	0000000027a50000-0000000027a8c000	Deferred        rtl_tcp_source
PE	0000000027c90000-0000000027cd3000	Deferred        sdrplay_source
PE	0000000027ce0000-0000000027cee000	Deferred        sdrplay_api
PE	0000000028000000-0000000028041000	Deferred        sdrpp_server_source
PE	0000000028250000-0000000028291000	Deferred        soapy_source
PE	00000000282a0000-00000000282dc000	Deferred        spyserver_source
PE	0000000061300000-000000006132d000	Deferred        iphlpapi
PE	0000000061540000-000000006157f000	Deferred        advapi32
PE	0000000062100000-00000000621c8000	Deferred        msvcp140
PE	0000000062dc0000-0000000062e44000	Deferred        rpcrt4
PE	0000000063280000-000000006328e000	Deferred        version
PE	00000000639c0000-00000000639d9000	Deferred        shcore
PE	0000000064840000-0000000064894000	Deferred        shlwapi
PE	0000000064cc0000-0000000064df3000	Deferred        oleaut32
PE	00000000664c0000-00000000664d0000	Deferred        hid
PE	0000000066540000-0000000066551000	Deferred        rtworkq
PE	0000000066d40000-0000000066d48000	Deferred        winusb
PE	0000000067140000-0000000067202000	Deferred        msvcr120
PE	0000000067640000-000000006766d000	Deferred        winepulse
PE	0000000067b40000-0000000067b6a000	Deferred        mmdevapi
PE	0000000068040000-00000000680a3000	Deferred        mfplat
PE	0000000068300000-0000000068353000	Deferred        combase
PE	00000000684c0000-00000000684e3000	Deferred        concrt140
PE	0000000068500000-0000000068537000	Deferred        uxtheme
PE	0000000068f80000-0000000068f90000	Deferred        wsock32
PE	0000000069200000-000000006920e000	Deferred        vcruntime140_1
PE	0000000069340000-000000006938d000	Deferred        dinput8
PE	0000000069740000-000000006976b000	Deferred        propsys
PE	000000006a080000-000000006a117000	Deferred        msvcrt
PE	000000006a200000-000000006a318000	Deferred        ole32
PE	000000006a680000-000000006a693000	Deferred        xinput1_4
PE	000000006b100000-000000006b19e000	Deferred        msvcr90
PE	000000006ba00000-000000006ba2b000	Deferred        sechost
PE	000000006bac0000-000000006bb40000	Deferred        setupapi
PE	000000006be80000-000000006be8b000	Deferred        cfgmgr32
PE	000000006c7c0000-000000006c838000	Deferred        gdi32
PE	000000006ca40000-000000006cb7e000	Deferred        comctl32
PE	000000006d580000-000000006d5a6000	Deferred        ws2_32
PE	000000006e2c0000-000000006e2d5000	Deferred        dnsapi
PE	000000006ea40000-000000006ea4e000	Deferred        dwmapi
PE	000000006eb00000-000000006ecc9000	Deferred        user32
PE	000000006f280000-000000006f28c000	Deferred        nsi
PE	0000000070040000-000000007004c000	Deferred        vcruntime140
PE	0000000070940000-00000000709ff000	Deferred        ucrtbase
PE	0000000071000000-0000000071019000	Deferred        imm32
ELF	000000007a800000-000000007aa0c000	Deferred        opengl32<elf>
  \-PE	000000007a850000-000000007aa0c000	\               opengl32
PE	000000007b000000-000000007b24b000	Deferred        kernelbase
PE	000000007b600000-000000007b660000	Export          kernel32
ELF	000000007d000000-000000007d004000	Deferred        <wine-loader>
PE	0000000140000000-0000000140010000	Deferred        sdrpp
PE	0000000170000000-000000017009f000	Export          ntdll
PE	0000000180000000-000000018063a000	Deferred        sdrpp_core
PE	00000002db9e0000-00000002dbb8a000	Deferred        libcodec2
ELF	00007f27dcebe000-00007f27dcffc000	Deferred        libgcrypt.so.20
ELF	00007f27f4084000-00007f27f40aa000	Deferred        libgpg-error.so.0
ELF	00007f27f40aa000-00007f27f40ca000	Deferred        liblz4.so.1
ELF	00007f27f40ca000-00007f27f4128000	Deferred        libopus.so.0
ELF	00007f27f4128000-00007f27f41d3000	Deferred        libvorbisenc.so.2
ELF	00007f27f41d3000-00007f27f4200000	Deferred        libvorbis.so.0
ELF	00007f27f4200000-00007f27f4412000	Deferred        winepulse.so
ELF	00007f27f4429000-00007f27f4465000	Deferred        libflac.so.8
ELF	00007f27f4465000-00007f27f452c000	Deferred        libsystemd.so.0
ELF	00007f27f452c000-00007f27f45ab000	Deferred        libsndfile.so.1
ELF	00007f27f45ab000-00007f27f45f9000	Deferred        libdbus-1.so.3
ELF	00007f27fc01f000-00007f27fc0a4000	Deferred        libpulsecommon-15.99.so
ELF	00007f27fc0a4000-00007f27fc0f9000	Deferred        libpulse.so.0
ELF	00007f280400b000-00007f2804016000	Deferred        libcap.so.2
ELF	00007f2804016000-00007f2804021000	Deferred        libogg.so.0
ELF	00007f2804021000-00007f2804036000	Deferred        libapparmor.so.1
ELF	00007f2804036000-00007f280403e000	Deferred        libasyncns.so.0
ELF	00007f280443e000-00007f280605c000	Deferred        libicudata.so.70
ELF	00007f280605c000-00007f280c000000	Deferred        libllvm-13.so.1
ELF	00007f2819346000-00007f2819541000	Deferred        libicuuc.so.70
ELF	00007f2819541000-00007f2819723000	Deferred        libxml2.so.2
ELF	00007f2819723000-00007f2819755000	Deferred        libtinfo.so.6
ELF	00007f2819755000-00007f281978f000	Deferred        libedit.so.2
ELF	00007f281978f000-00007f281979c000	Deferred        libffi.so.8
ELF	00007f281979c000-00007f281980a000	Deferred        libvulkan.so.1
ELF	00007f281980a000-00007f2819815000	Deferred        libdrm_nouveau.so.2
ELF	00007f2819815000-00007f2819821000	Deferred        libdrm_amdgpu.so.1
ELF	00007f2819821000-00007f281983f000	Deferred        libelf.so.1
ELF	00007f281983f000-00007f281990e000	Deferred        libzstd.so.1
ELF	00007f2819937000-00007f281b2ce000	Deferred        radeonsi_dri.so
ELF	00007f281b2ce000-00007f281b2ee000	Deferred        libgcc_s.so.1
ELF	00007f281b51a000-00007f281b524000	Deferred        libxcb-xfixes.so.0
ELF	00007f281b524000-00007f281b529000	Deferred        libxshmfence.so.1
ELF	00007f281b529000-00007f281b533000	Deferred        libxcb-sync.so.1
ELF	00007f281b533000-00007f281b538000	Deferred        libxcb-present.so.0
ELF	00007f281b538000-00007f281b53f000	Deferred        libxcb-dri3.so.0
ELF	00007f281b53f000-00007f281b544000	Deferred        libxcb-shm.so.0
ELF	00007f281b544000-00007f281b54b000	Deferred        libxcb-dri2.so.0
ELF	00007f281b54b000-00007f281b550000	Deferred        libx11-xcb.so.1
ELF	00007f281b550000-00007f281b56d000	Deferred        libxcb-glx.so.0
ELF	00007f281b56d000-00007f281b583000	Deferred        libdrm.so.2
ELF	00007f281b583000-00007f281b5be000	Deferred        libglapi.so.0
ELF	00007f281b5be000-00007f281b62f000	Deferred        libglx_mesa.so.0
ELF	00007f281b62f000-00007f281b663000	Deferred        libglx.so.0
ELF	00007f281b663000-00007f281b71b000	Deferred        libgldispatch.so.0
ELF	00007f281b71b000-00007f281b7a2000	Deferred        libgl.so.1
ELF	00007f281b7a5000-00007f281b7b4000	Deferred        libdrm_radeon.so.1
ELF	00007f281b7b4000-00007f281b7c4000	Deferred        libsensors.so.5
ELF	00007f281b7ed000-00007f281b7f5000	Deferred        libxfixes.so.3
ELF	00007f281b7f5000-00007f281b801000	Deferred        libxcursor.so.1
ELF	00007f281b801000-00007f281b815000	Deferred        libxi.so.6
ELF	00007f281b815000-00007f281b81a000	Deferred        libxcomposite.so.1
ELF	00007f281b81a000-00007f281b827000	Deferred        libxrandr.so.2
ELF	00007f281b827000-00007f281b834000	Deferred        libxrender.so.1
ELF	00007f281b834000-00007f281b83b000	Deferred        libxxf86vm.so.1
ELF	00007f281b83b000-00007f281b840000	Deferred        libxinerama.so.1
ELF	00007f281b840000-00007f281b84d000	Deferred        libmd.so.0
ELF	00007f281b84d000-00007f281b865000	Deferred        libbsd.so.0
ELF	00007f281b865000-00007f281b86d000	Deferred        libxdmcp.so.6
ELF	00007f281b86d000-00007f281b897000	Deferred        libxcb.so.1
ELF	00007f281b897000-00007f281b9d7000	Deferred        libx11.so.6
ELF	00007f281ba00000-00007f281bc05000	Deferred        ws2_32.so
ELF	00007f281bc06000-00007f281bc0c000	Deferred        libxau.so.6
ELF	00007f281bc0c000-00007f281bc21000	Deferred        libxext.so.6
ELF	00007f281bc21000-00007f281bcd7000	Deferred        winex11<elf>
  \-PE	00007f281bc30000-00007f281bcd7000	\               winex11
ELF	00007f281bdb6000-00007f281be00000	Deferred        libfontconfig.so.1
ELF	00007f281be00000-00007f281c003000	Deferred        dnsapi.so
ELF	00007f281c019000-00007f281c04a000	Deferred        libexpat.so.1
ELF	00007f281c04a000-00007f281c06d000	Deferred        libbrotlicommon.so.1
ELF	00007f281c06d000-00007f281c135000	Deferred        libfreetype.so.6
ELF	00007f281c235000-00007f281c400000	Deferred        win32u<elf>
  \-PE	00007f281c260000-00007f281c400000	\               win32u
ELF	00007f281c400000-00007f281c603000	Deferred        user32.so
ELF	00007f281c619000-00007f281c700000	Deferred        libm.so.6
ELF	00007f281c800000-00007f281cb76000	Dwarf           libwine.so.1
ELF	00007f281cb84000-00007f281cb8d000	Deferred        libuuid.so.1
ELF	00007f281d200000-00007f281d4db000	Deferred        ntdll.so
ELF	00007f281d4dd000-00007f281d4eb000	Deferred        libbrotlidec.so.1
ELF	00007f281d4eb000-00007f281d507000	Deferred        libz.so.1
ELF	00007f281d507000-00007f281d542000	Deferred        libpng16.so.16
ELF	00007f281d542000-00007f281d556000	Deferred        libresolv.so.2
ELF	00007f281d556000-00007f281d581000	Deferred        liblzma.so.5
ELF	00007f281d581000-00007f281d59c000	Deferred        libunwind.so.8
ELF	00007f281d59c000-00007f281d5a1000	Deferred        librt.so.1
ELF	00007f281d5a4000-00007f281d7cc000	Deferred        libc.so.6
ELF	00007f281d7cc000-00007f281d7d1000	Deferred        libdl.so.2
ELF	00007f281d7d1000-00007f281d7d6000	Deferred        libpthread.so.0
ELF	00007f281d801000-00007f281d83d000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000048    0     
	00000064    0     
	0000008c    0     
	000000a4    0     
	000000d0    0     
	000000d4    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000b0    0     
0000005c winedevice.exe
	00000060    0     
	00000068    0     
	0000006c    0     
	00000070    0     
	00000074    0     
	00000078    0     
	0000007c    0     
00000084 plugplay.exe
	00000088    0     
	00000090    0     
	00000094    0     
	00000098    0     
	0000010c    0     
	00000110    0     
0000009c svchost.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
000000b4 explorer.exe
	000000b8    0     
	000000bc    0     
	000000c0    0     
000000c8 rpcss.exe
	000000cc    0     
	000000d8    0     
	000000dc    0     
	000000e0    0     
	000000e4    0     
	000000e8    0     
	000000ec    0     
000000f0 (D) C:\Program Files\sdrpp_windows_x64\sdrpp.exe
	000000f4    0     
	00000100    0     
	00000104    0     
	00000108    0     
	0000012c    0     
	00000130    0     
	00000134    0     
	00000138    0     
	0000013c    0     
	00000140    0     
	00000144    0     
	00000148    0     
	0000014c    0     
	00000150    0     
	00000154    0     
	00000158    0     
	0000015c    0     
	00000160    0     
	00000164    0     
	00000168    0     
	0000016c    0     
	00000170    0     
	00000174    0     
	00000178    0     
	0000017c    0     
	00000198    0     
	000001a0    0     
	000001ac    0     
	000001b0    0     
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001c0    0     
	000001c4    0     
	000001c8    0     
	000001cc    0     
	000001d0    0     
	000001d4    0 <== 
	000001dc    0     
	000001e0    0     
	000001e4    0     
	000001e8    0     
	0000020c    0     
	00000210    0     
	00000224    0     
	00000228    0     
	0000022c    0     
	00000230    0     
000001f4 conhost.exe
	000001f8    0     
System information:
    Wine build: wine-7.7-8314-ga93a0119cf0
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.0-46-generic

**Comment by AlexandreRouma** [comment]
RTaudio for windows very likely doesn't work on wine. Nothing that can (or should) be done tbh.
