### ISSUE TITLE
Add SDR++ to flatpak

### ISSUE THREAD

**Issue by MikeTheComrade** [AlexandreRouma/SDRPlusPlus#864]
**Feature description**

While SDR++ is available on a wide range of Linux systems, those that are immutable, such as SteamOS (Arch based), have anything outside of the Flatpaks wiped after updating, this includes anything installed from the AUR for example.

I believe that by adding SDR++ as a Flatpak to the flatbub repository, it would make things more convenient, not only for immutable systems, but for compatibility across multiple Linux OS's from one source, while still leaving the option to build manually if one so chooses.

I recently noticed SDRAngel was added to the flathub, however I would like to use SDR++ if possible when traveling on things like my SteamDeck.

Thank you for all you do and taking the time to read my suggestion.

**Comment by AlexandreRouma** [comment]
Flatpak support is not planned as it would completely void the modularity aspect of the software and probably cause heaps of issues with driver conflicts on a a bunch of SDRs.

I suggest not using dumb distros with locked down filesystems instead.
