### ISSUE TITLE
Audio recording levels very low

### ISSUE THREAD

**Issue by jcoles56** [AlexandreRouma/SDRPlusPlus#867]
When I record (16bit PCM mono) audio from an AM signal, the audio level in the resulting WAV file is low. This is obvious when looking at the file in any audio editor. There are 16 bits available in the WAV format. Let's use them.

**Comment by AlexandreRouma** [comment]
No steps to reproduce, no info on versions or hardware, no settings shown... What am I supposed to do with this?
Re-open an issue with the template filled out properly.

**Comment by jcoles56** [comment]
Apologies. I confused your product for another one! Checking the Record function today, I find it works just fine.
