### ISSUE TITLE
Line 52 of CMakeLists.txt issue.

### ISSUE THREAD

**Issue by RoodyPooCandyButt** [AlexandreRouma/SDRPlusPlus#872]
I have been having issues compiling on a raspberry pi 4 and I noticed that line 52 of CMakeLists.txt has a comment describing the SSTV decoder as the M17 decoder. Compilation has been failing at this point and I am wondering if it is related. Thanks for everything you do.

**Comment by AlexandreRouma** [comment]
just a typo but has nothing to do with a build faily, it's just a comment.
That option should NOT be enabled by the way.

Unfortunately you haven't described the actual issue so I can only ask you to reopen an issue following the template and containing the build logs.
