### ISSUE TITLE
SDRPlay DAB Notch

### ISSUE THREAD

**Issue by kmp56** [AlexandreRouma/SDRPlusPlus#875]
i7 4x3500MHz, Ubuntu 22.04 / Windows 11 x64
SDR ++ v.1.1.0 build (4047d3b)
SDRPlay RSP1A receiver:

 - does not work (it has never worked so far) DAB Notch filter for 174-240MHz frequency. Applies to Linux and Windows versions. 
 - FM / MW Notch works OK from the beginning.

**Comment by AlexandreRouma** [comment]
fixed, wait 45 minutes for the new nightly to finish building.
