### ISSUE TITLE
SDR++ on android tv

### ISSUE THREAD

**Issue by Mikeload66** [AlexandreRouma/SDRPlusPlus#877]
Hi there ,
At the moment I'm using sdr touch on my android tv box
But it has limited features , I'm needing bias tee switching so I can select another antenna , I've installed sdr++ apk file successfully but when I press play on the screen the program switches back to the homescreen.
Tv box is running android 11, any advice will much appreciated. 

Regards
Mike

**Comment by AlexandreRouma** [comment]
You haven't given any useful information to debug the issue as asked for in the issue template...
What hardware? what specs? what SDR? Which SDR++ version? Nightly or first prerelease? Does the device show up in the list? Screenshots? Error message? etc.

**Comment by AlexandreRouma** [comment]
closing as stalled, reopen when/if info asked for is provided
