### ISSUE TITLE
Recording path settings is not saved

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#88]
On my build, the recording path is set to `%ROOT%/recordings` by default. I am able to enter a different path and SDR++ records into that path just fine, but after closing and re-opening SDR++, the default path is back. It would be great if the user's path entered is saved across restarts of the program.

**Comment by AlexandreRouma** [comment]
Bug fixed in latest commit

**Comment by shuyuan-liu** [comment]
Thanks @AlexandreRouma !
