### ISSUE TITLE
New source for controlling soundcard SDR

### ISSUE THREAD

**Issue by sajjsamm** [AlexandreRouma/SDRPlusPlus#894]
**Feature description**
This feature adds a new source for soundcard SDRs whose frequency is controlled by a serial com port.
I want a source module in which I can select the COM port and baud rate and consistently send the center frequency to that COM port and adjust the shift value (which is in this case the center frequency) in software so the main VFO frequency is always equal to what is basically in the radio not relative to sound card samplings frequency.
I suggest the format of frequency be something common so simply everybody can write their own code to parse the frequency in the microcontroller on the radio.
i.e. for 14.074 MHz would be "14074000\r\n" without "
I can really use this for my Avala-01 based sound card SDR with a Si5351 as LO and an ATMEGA8 microcontroller because I have to tune the center frequency with a rotary and read the frequency on an LCD which is very annoying.

**Comment by sajjsamm** [comment]
As I mentioned, some older kits use COM ports to communicate. Even if I manage to write a rigctl client on AVR I still need some TCP connection to the PC. It does make more sense to just send commands directly over serial. For some sound card SDR maybe we can come up with a CAT control at best.

**Comment by AlexandreRouma** [comment]
A lot of soundcard based ham kits are already supported by rigctl/hamlib. If yours isn't, you can just write a simple application to do the same or contribute to hamlib and implement the specific model if it's common.

There are no standards serial protocols for that. I'm gonna gonna start trying to support a  bunch of them when I don't even have the hardware to test or make up an arbitrary protocol.

**Comment by sajjsamm** [comment]
I'm designing a bare minimum RX. I even want to downgrade ATMEGA8 to an ATTINY series because the only job it does is to read a frequency from a serial port and send I2C commands to a Si5351 chip to adjust the frequency and nothing fancy that is interpreted in CAT or rigctl protocols.
I have no programming skills to do pure software development to make a module for my own design.
