### ISSUE TITLE
On linux, crash because of bandplans directory not found

### ISSUE THREAD

**Issue by nmaster2042** [AlexandreRouma/SDRPlusPlus#9]
When I build the last 0.2.3 alpha and try to start I got:

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory [../bandplans]
Abandon (core dumped)

I start it from where I build, and there is actually a bandplans folder.

If think it should look for ./bandplans instead of ../bandplans because if I copy the folder to ../ sdrpp actually starts.

**Comment by AlexandreRouma** [comment]
Hi
Sorry, my bad, pushed development code to the master branch :/
Just fixed the issue, try pulling and rebuilding.
