### ISSUE TITLE
SDR++ Windows10 trouble

### ISSUE THREAD

**Issue by RecepAGulec** [AlexandreRouma/SDRPlusPlus#904]
FIRST: Before reporting any bug, make sure that the bug you are reporting has not been reported before. Also, try to use the [nightly version](https://www.sdrpp.org/nightly) if possible in case I've already fixed the bug.

**Hardware**
- CPU:  i5 3.33 GHz
- RAM: 4GB
- GPU: 
- SDR: Local

**Software**
- Operating System: Windows10 Pro x64 20H2
- SDR++: SDR++v1.0.4

**Bug Description**
After running SDR++ , program windows is very dimmed and fonts are un-readable. (Screen print attached)
![sdrpp screen print](https://user-images.githubusercontent.com/55786871/199764743-25dec91d-f898-465f-837a-b9da05cd7fb2.png)

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.

**Comment by AlexandreRouma** [comment]
Update your graphics drivers.
