### ISSUE TITLE
Unit of de-emphasis value should be "μs" instead of "μS"

### ISSUE THREAD

**Issue by shuyuan-liu** [AlexandreRouma/SDRPlusPlus#91]
The unit for seconds should be lower-case. It is currently upper-case, as shown in the screenshot in the main README.md file.

**Comment by AlexandreRouma** [comment]
Fixed, thanks for reporting.

**Comment by shuyuan-liu** [comment]
The new radio module still has the incorrect unit as of 15010cf.
