### ISSUE TITLE
Need release build for aarm64 for MacOS on M1

### ISSUE THREAD

**Issue by kskenyon** [AlexandreRouma/SDRPlusPlus#924]

**Comment by romanremus** [comment]
hello everyone......can you please compile sdr++ also for windows 7 /64 bit.....or please provide support in the source code for compiling in cygwin...........I have I tried to open it with windows 7 but I don't have SoapySDR.dll.....and in compilation with cygwin...I don't have certain dependencies and I can't install them in cygwin

**Comment by AlexandreRouma** [comment]
I don't have an a Mac (let alone an M1) and cross compilation is not possible.
Github doesn't allow for building on M1, so your only option is build from source.
