### ISSUE TITLE
Hello everyone! I have a problem with the application windows and font.

### ISSUE THREAD

**Issue by itan2105** [AlexandreRouma/SDRPlusPlus#930]
Mac OS 13.0.1 SDR++ Nightly Build

When you open the program, everything becomes huge. buttons, letters and everything else.
<img width="1280" alt="Снимок экрана 2022-12-06 в 09 27 44" src="https://user-images.githubusercontent.com/44764285/205793865-3b7a867a-06de-49d4-9d02-eda976af0c78.png">

**Comment by AlexandreRouma** [comment]
you changed high-dpi scaling, set it back to 100%

**Comment by itan2105** [comment]
apparently I'm so stupid that I can't find this parameter. Tell me please...

**Comment by AlexandreRouma** [comment]
it's in the "Display" menu

**Comment by itan2105** [comment]
thank you!
