### ISSUE TITLE
FC0012 tuner shows only zero gain, unless it was previously used e.g. in SDR#

### ISSUE THREAD

**Issue by trishmapow** [AlexandreRouma/SDRPlusPlus#933]
**Hardware**
- CPU: i7-1165G7
- RAM: 16GB
- GPU: integrated
- SDR: Generic blue RTL2832U + FC0012

**Software**
- Operating System: Windows 11 22000.1219
- SDR++: v1.1.0 (Built at 09:16:16, Nov 23 2022)

**Bug Description**
Cannot set gain for FC0012 based dongle, even after clicking refresh and restarting sdr++. Tested with 2 dongles. Everything works fine with RTL-SDR.com v3.

**Steps To Reproduce**
1. Plug in dongle and start program.
2. No gain control.
3. Connect to dongle in SDR#
4. Gain control appears

**Screenshots**
After plugging in
<img width="171" alt="image" src="https://user-images.githubusercontent.com/17211063/206702300-7e45204f-6c44-4933-8e19-e325970a600e.png">
After using SDR#
<img width="158" alt="image" src="https://user-images.githubusercontent.com/17211063/206702456-38f1fd7d-a744-47db-a456-d6ac025dbe14.png">

**Comment by AlexandreRouma** [comment]
report to the developers of the rtlsdr driver. SDR++ shows what it tells it the dongle supports.
