### ISSUE TITLE
Using SDR++ with the SDR Play module on an Android device

### ISSUE THREAD

**Issue by lordsvarogofmax** [AlexandreRouma/SDRPlusPlus#939]
Good day!
Can you please tell me how to add the SDR Play module to the SDR ++ assembly on a smartphone?

Thanks!
 
Asus ZenFone 7 Pro (root), Android 12, SDR Play driver, SDRPlay RSP1

**Comment by AlexandreRouma** [comment]
the SDRplay API doesn't run on android, you can't.

**Comment by app7713-design** [comment]
hi there buddy did you get my last email? cheers dave

**Comment by Neitron4ikus** [comment]
@AlexandreRouma - SDRplay driver is exist on Android already.  Can you please add support in next release of https://github.com/AlexandreRouma/SDRPlusPlus/discussions/703 ?

**Comment by AlexandreRouma** [comment]
No? you're talking about a RTL-TCP hack and it will not be implemented.
