### ISSUE TITLE
Unresolved dependancies for Ubuntu Jammy (nightly) package

### ISSUE THREAD

**Issue by thefoster** [AlexandreRouma/SDRPlusPlus#943]
On my Jammy installation, the sdr++ package fails to install because of the dependancy chain from librtaudio-dev via libjack-dev and libjack0, while libjack0 depends on jackd1, while on jammy jackd2 is default.

 libjack-jackd2-0 : Kollidiert mit: libjack-0.116
                    Kollidiert mit: libjack-0.125
                    Kollidiert mit: libjack0 aber 1:0.125.0-3build2 soll installiert werden
 libjack0 : Kollidiert mit: libjack-0.116
            Kollidiert mit: libjack-0.125

**Comment by AlexandreRouma** [comment]
Tell the maintainer of the rtaudio package.
Whatever that package itself requires is not my under my control.
