### ISSUE TITLE
sdrpp_server Source not available 

### ISSUE THREAD

**Issue by AA7CL** [AlexandreRouma/SDRPlusPlus#944]
**Hardware**
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4570 CPU @ 3.20GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4600

**Software**
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-56-generic (64-bit)
OpenGL version string: 3.1 Mesa 22.0.5
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

SDR++ version: 1.1.0 (built 23:15:41, Dec 11 2022)

**Bug Description**
Sdrpp_server module not available in the source or Module Manager. See screen shot.
Appears the module is in the /usr/lib/sdrpp directory and is loading at launch. See log.

**Steps To Reproduce**
1. downloaded nightly build for 22.04 Jammy
2. Install libraries as mentioned in the installation manual
3. Used QApt package manager to install the deb file
4. Ran sdrpp from the console.

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
![sdrpp](https://user-images.githubusercontent.com/8794691/209375631-712b58a6-3ad8-49da-b828-03c5a5362f91.png)

Add any other relevant information
[launch_log.txt](https://github.com/AlexandreRouma/SDRPlusPlus/files/10296423/launch_log.txt)
.

**Comment by AlexandreRouma** [comment]
Not a bug.

You previously ran an older version that didn't have the `sdrpp_server_source` (eg. version 1.0.4). Therefor you must instantiate the module yourself if you wish to use it. 

At the bottom of the "Module Manager", select `sdrpp_server_source` from the dropdown, then type "SDR++ Server Source" in the text field at the left of said dropdown and finally press the `+` button on the right of the dropdown.
