### ISSUE TITLE
display of settings problem

### ISSUE THREAD

**Issue by DANKC2STA** [AlexandreRouma/SDRPlusPlus#950]
**Hardware**
- CPU: Athlon 64 dual core 5000+ @2.6
- RAM: 3840 MiB
- GPU: NVIDIA Gforce 8200
- SDR: local Airspy HF+ 

**Software**
- Operating System: , Ubuntu 22.04.1 LTS x86_64
- SDR++: v1.1.0 build 23:15:41 Dec 11, 2022

**Bug Description**
Opens ok, but left side of screen (setting) is blank. If I scroll down it shows from Line "OFFSET"

**Steps To Reproduce**
1. open program
2. look at left side of screen- it is blank
3. with mouse scroll down and image appears at line OFFSET
4. .also note diagonal line
5. ...

**Screenshots**
![Screenshot from 2022-12-31 09-54-03](https://user-images.githubusercontent.com/19675766/210140819-4fefd0a7-6e8c-49f9-a601-4111edfe9707.png)

![Screenshot from 2022-12-31 09-11-43](https://user-images.githubusercontent.com/19675766/210140773-6a0ea16f-7d18-41fa-891f-e89e7cd2bb60.png)

**Additional info**
Add any other relevant information.

Any help would be appreciated Thanks Dan KC2STA

**Comment by AlexandreRouma** [comment]
Your graphics drivers or the GPU are broken.
That GPU was released almost 16 years ago...
