### ISSUE TITLE
SDR++ for Windows ARM64 (SQ1 Surface Pro X)

### ISSUE THREAD

**Issue by xnaron** [AlexandreRouma/SDRPlusPlus#951]
**Feature description**

Is it possible to have a version auto built for windows arm64 to support a Surface Pro X with SQ1 Arm64 processor?

**Comment by AlexandreRouma** [comment]
In automated builds it is not possible. GitHub doesn't plan to ever support it: https://github.com/actions/runner-images/issues/768

You'll have to build from source, should work the same way as normal windows.

I don't have any device that would run arm windows so can't test anyway.
