### ISSUE TITLE
Add Radio Sonde plugin on Android Version

### ISSUE THREAD

**Issue by BrunoKlu** [AlexandreRouma/SDRPlusPlus#952]
**Feature description**

**Comment by AlexandreRouma** [comment]
I do not add third party plugins to the official builds.

**Comment by scottjpalmer** [comment]
I enlisted the help of a friend who got it working.
Download here https://github.com/jethrocarr/SDRPlusPlus/releases/download/nightly/sdrpp.apk
Video of it working here https://youtu.be/Ru0BRHeV7b0
It is using the latest SDR++ nightly as of today.
