### ISSUE TITLE
kernel: sdrpp segfault at 38 ip 00007f1d86f98f74 sp 00007ffef9400dd8 error 4 in libc.so.6

### ISSUE THREAD

**Issue by test1232-22** [AlexandreRouma/SDRPlusPlus#957]
**Hardware**, 
- CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
- RAM: 32501624 kB
- GPU: GP107M [GeForce GTX 1050 Ti Mobile]
- SDR: Local

**Software**
- Operating System: Ubuntu 22.04.1 LTS
- SDR++:  v1.1.0 Build at 22:06 Jan 2, 2023

**Bug Description**
Click play, SDRpp crashes.

**Steps To Reproduce**
1. Open the app
2. Select HackRF source
3. Click play icon

**Additional info**
Full log file at https://pastebin.pl/view/7e3d691c

ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: ubuntu:GNOME
Date: Thu Jan  5 12:02:29 2023
DistroRelease: Ubuntu 22.04
ExecutablePath: /usr/bin/sdrpp
ExecutableTimestamp: 1672689909
ProcCmdline: /usr/bin/sdrpp
ProcCwd: /home/akh
ProcEnviron:
 PATH=(custom, user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/usr/bin/zsh

an  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.710] [info] SDR++ v1.1.0
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.710] [info] Loading config
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.790] [info] Using OpenGL 3.0
Jan  5 16:23:35 akh-XPS gnome-shell[3369]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xc00009
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.854] [info] Loading icons
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.860] [info] Loading band plans
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.863] [info] Loading band plans color table
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.871] [info] Loading modules
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.871] [info] Loading /usr/lib/sdrpp/plugins/airspy_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.874] [info] Loading /usr/lib/sdrpp/plugins/network_sink.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.878] [info] Loading /usr/lib/sdrpp/plugins/rfspace_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.881] [info] Loading /usr/lib/sdrpp/plugins/radio.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.890] [info] Loading /usr/lib/sdrpp/plugins/plutosdr_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.892] [info] Loading /usr/lib/sdrpp/plugins/file_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.894] [info] Loading /usr/lib/sdrpp/plugins/soapy_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.896] [info] Loading /usr/lib/sdrpp/plugins/m17_decoder.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.899] [info] Loading /usr/lib/sdrpp/plugins/spyserver_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.904] [info] Loading /usr/lib/sdrpp/plugins/meteor_demodulator.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.906] [info] Loading /usr/lib/sdrpp/plugins/sdrpp_server_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.907] [info] Loading /usr/lib/sdrpp/plugins/discord_integration.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.909] [info] Loading /usr/lib/sdrpp/plugins/limesdr_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.910] [info] Loading /usr/lib/sdrpp/plugins/rtl_tcp_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.912] [info] Loading /usr/lib/sdrpp/plugins/new_portaudio_sink.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.914] [info] Loading /usr/lib/sdrpp/plugins/rtl_sdr_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.918] [info] Loading /usr/lib/sdrpp/plugins/hermes_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.919] [info] Loading /usr/lib/sdrpp/plugins/rigctl_server.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.921] [info] Loading /usr/lib/sdrpp/plugins/audio_sink.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.924] [info] Loading /usr/lib/sdrpp/plugins/hackrf_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.925] [info] Loading /usr/lib/sdrpp/plugins/bladerf_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.926] [info] Loading /usr/lib/sdrpp/plugins/recorder.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.927] [info] Loading /usr/lib/sdrpp/plugins/spectran_http_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.929] [info] Loading /usr/lib/sdrpp/plugins/airspyhf_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.930] [info] Loading /usr/lib/sdrpp/plugins/scanner.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.934] [info] Loading /usr/lib/sdrpp/plugins/frequency_manager.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.936] [info] Loading /usr/lib/sdrpp/plugins/sdrplay_source.so
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.937] [error] Couldn't load /usr/lib/sdrpp/plugins/sdrplay_source.so.
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.937] [info] Initializing Airspy Source (airspy_source)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.944] [info] Initializing AirspyHF+ Source (airspyhf_source)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.950] [info] Initializing Audio Sink (audio_sink)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.951] [info] Initializing BladeRF Source (bladerf_source)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.957] [error] Could not list devices -7
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.957] [info] Initializing File Source (file_source)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.958] [info] Initializing Frequency Manager (frequency_manager)
Jan  5 16:23:35 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:35.959] [info] Initializing HackRF Source (hackrf_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.149] [info] Initializing LimeSDR Source (limesdr_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.188] [info] Initializing Network Sink (network_sink)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.189] [info] Initializing PlutoSDR Source (plutosdr_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.191] [info] Initializing RFspace Source (rfspace_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.198] [info] Initializing RTL-SDR Source (rtl_sdr_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.209] [info] Initializing RTL-TCP Source (rtl_tcp_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.210] [info] Initializing Radio (radio)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 32, interp: 4, decim: 5, inacc: 0.000000%, taps: 380
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 4, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 256, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: -2147483648, interp: 2, decim: 1, inacc: 0.000000%, taps: 152
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: -2147483648, interp: 147, decim: 80, inacc: 0.000000%, taps: 11172
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.220] [warning] Demod switch took 2867 us
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.299] [info] RtAudio stream open
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.299] [info] Initializing Recorder (recorder)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.302] [info] Initializing Rigctl Server (rigctl_server)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.303] [info] Initializing SDR++ Server Source (sdrpp_server_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.308] [info] Initializing SDRplay Source (sdrplay_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.311] [error] Module 'sdrplay_source' doesn't exist
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.311] [info] Initializing SoapySDR Source (soapy_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
Jan  5 16:23:36 akh-XPS kernel: [ 1974.818880] [UFW BLOCK] IN=enxf8e43b0b884e OUT= MAC= SRC=fe80:0000:0000:0000:76a3:10d6:69b5:7fcb DST=ff02:0000:0000:0000:0000:0000:0000:000c LEN=224 TC=0 HOPLIMIT=1 FLOWLBL=691129 PROTO=UDP SPT=1900 DPT=1900 LEN=184 
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.882] [info] Setting sample rate to 8000.0
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 8192, interp: 3, decim: 1, inacc: 0.000000%, taps: 228
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.884] [info] New DSP samplerate: 8000.0 (source samplerate is 8000.0)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.884] [info] Initializing SpyServer Source (spyserver_source)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.887] [info] Loading color maps
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.891] [info] Loading /usr/share/sdrpp/colormaps/greyscale.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.895] [info] Loading /usr/share/sdrpp/colormaps/gqrx.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.898] [info] Loading /usr/share/sdrpp/colormaps/viridis.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.903] [info] Loading /usr/share/sdrpp/colormaps/electric.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.907] [info] Loading /usr/share/sdrpp/colormaps/websdr.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.910] [info] Loading /usr/share/sdrpp/colormaps/inferno.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.912] [info] Loading /usr/share/sdrpp/colormaps/classic_green.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.917] [info] Loading /usr/share/sdrpp/colormaps/plasma.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.919] [info] Loading /usr/share/sdrpp/colormaps/magma.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.922] [info] Loading /usr/share/sdrpp/colormaps/classic.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.925] [info] Loading /usr/share/sdrpp/colormaps/turbo.json
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 64, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.968] [info] New DSP samplerate: 2000000.0 (source samplerate is 2000000.0)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.968] [info] HackRFSourceModule 'HackRF Source': Menu Select!
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 64, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 64, interp: 96, decim: 125, inacc: 0.000000%, taps: 9500
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.970] [info] New DSP samplerate: 2000000.0 (source samplerate is 2000000.0)
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: -2147483648, interp: 147, decim: 80, inacc: 0.000000%, taps: 11172
Jan  5 16:23:36 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:36.976] [info] RtAudio stream open
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] HackRFSourceModule 'HackRF Source': Tune: -340215.98!
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Airspy Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for AirspyHF+ Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Audio Sink
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for BladeRF Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for File Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Frequency Manager
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for HackRF Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for LimeSDR Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Network Sink
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for PlutoSDR Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for RFspace Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for RTL-SDR Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for RTL-TCP Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Radio
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Recorder
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for Rigctl Server
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for SDR++ Server Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for SoapySDR Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Running post-init for SpyServer Source
Jan  5 16:23:37 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:37.002] [info] Ready.
Jan  5 16:23:41 akh-XPS sdrpp.desktop[90978]: [Resamp] predec: 512, interp: 8000, decim: 13021, inacc: 0.000000%, taps: 989583
Jan  5 16:23:41 akh-XPS sdrpp.desktop[90978]: [2023-01-05 16:23:41.537] [info] New DSP samplerate: 20000000.0 (source samplerate is 20000000.0)
Jan  5 16:23:42 akh-XPS kernel: [ 1980.838326] sdrpp[90978]: segfault at 38 ip 00007fbf496a5f74 sp 00007ffc8ba6fda8 error 4 in libc.so.6[7fbf49636000+195000]
Jan  5 16:23:42 akh-XPS kernel: [ 1980.838360] Code: 14 00 e8 ff 1e fa ff 48 8d 0d e8 98 14 00 ba 53 02 00 00 48 8d 35 2a 16 14 00 48 8d 3d 4e 16 14 00 e8 e0 1e fa ff f3 0f 1e fa <8b> 47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 0f 85 a7 00 00 00 53
Jan  5 16:23:43 akh-XPS systemd[3206]: app-gnome-sdrpp-90978.scope: Consumed 1.527s CPU time.
^Z

**Comment by AlexandreRouma** [comment]
See troubleshooting section of the readme:
https://github.com/AlexandreRouma/SDRPlusPlus#sdr-crashes-when-starting-a-hackrf
