### ISSUE TITLE
[Feature Request] Digital mode decoding

### ISSUE THREAD

**Issue by evoke0** [AlexandreRouma/SDRPlusPlus#959]
As in #360, SDR++ stays behind SDR# when plugins are needed. Any chance a digital demodulator is integrated? It's better to go little by little as not every mode is needed, just the most typical ones such as P25 and DMR. Maybe taking a look at 'Simple DMR' plugin for SDR# could be a good start as DSD is vague.

**Comment by AlexandreRouma** [comment]
Not possible due to legal reason. Codec is proprietary and including it is how you get sued.

**Comment by AsciiWolf** [comment]
> Not possible due to legal reason. Codec is proprietary and including it is how you get sued.

You probably could depend on an external mbelib just like other digital voice decoders do.

Or better - you can implement this using a hardware [vocoder chip](https://www.pa7lim.nl/ambepage/) (usually in form of an USB dongle like [this one](https://www.passion-radio.com/digital/dongle-ambe3000-590.html)) that is 100% legal.
