### ISSUE TITLE
Add SDR++ for Android to F-Droid

### ISSUE THREAD

**Issue by dfsxn** [AlexandreRouma/SDRPlusPlus#966]
Hi,

I've submitted the SDR++ repository to F-Droid Requests For Packaging: https://gitlab.com/fdroid/rfp/-/issues/2322

Also in https://forum.f-droid.org/t/software-defined-radio-client-for-android-sdr-android-public-pre-release-nightly-build/20954

As you probably know, F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The F-Droid client can be able browse, install, and keep track of updates on Android devices.

It is OK for you?

If yes, could you help with the missing Fastlane structures? Be welcome to use Izzy's [Fastlane CheatSheet](https://gitlab.com/-/snippets/1895688) to set them up.

Thank you.

Kind regards,

**Comment by AlexandreRouma** [comment]
I don't have time to deal with it and don't want to have someone else maintain it either.
I would prefer the software **not** be available on there since I don't need more people running outdated or incorrectly built versions.

Use the APK as provided in every nightly and future release.
