### ISSUE TITLE
Ability to go wide than 15000 On AM demodulation bandwidth

### ISSUE THREAD

**Issue by TS440S** [AlexandreRouma/SDRPlusPlus#972]
Would it be possible to allow users to go beyond the "standard" bandwidth limits for things like AM radio reception (other modes, too)?

I am experimenting with hi fidelity shortwave recording and I'd love to be able to open up the AM receiver a bit more.

**Comment by AlexandreRouma** [comment]
Duplicate of https://github.com/AlexandreRouma/SDRPlusPlus/issues/958
