### ISSUE TITLE
Nightly does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by drewlio** [AlexandreRouma/SDRPlusPlus#986]
Looks like it needs libvolk.so.2.2 but libvolk.so.2.5 is current. This is on today's nightly.

```
$ sdrpp
sdrpp: error while loading shared libraries: libvolk.so.2.2: cannot open shared object file: No such file or directory

```

```
/usr/lib/x86_64-linux-gnu/libvolk.so
/usr/lib/x86_64-linux-gnu/libvolk.so.2.5.1
/usr/lib/x86_64-linux-gnu/libvolk.a
/usr/lib/x86_64-linux-gnu/libvolk.so.2.5
```

**Comment by drewlio** [comment]
PR #919 knew this was going to happen.

**Comment by AlexandreRouma** [comment]
That pull request has nothing to do with what you're experiencing, you probably just downloaded the wrong deb for your Ubuntu version. You need to use the `jammy` deb.

**Comment by drewlio** [comment]
You might be right. I'll check. Thanks.

**Comment by L1049G** [comment]
I am getting exactly the same error;
$ sdrpp
sdrpp: error while loading shared libraries: libvolk.so.2.2: cannot open shared object file: No such file or directory

Using the nightly jammy deb; sdrpp_ubuntu_jammy_amd64.deb
on Ubuntu 22.04 (jammy).
libvolk.so.2.5 is installed
