### ISSUE TITLE
multi client

### ISSUE THREAD

**Issue by romanremus** [AlexandreRouma/SDRPlusPlus#987]
**Feature description**
Hi .....Alexandre .....do you think you can make sdr++ so that the tcp audio output accepts more clients ??? I use sdr++ for dsd-fme ... but it only accepts one client ..... and I would like to connect more clients via tcp .... thank you

**Comment by samysousa** [comment]
@romanremus DSD-FME ? 
As a generalisation, i believe that compatibility (Where possible) to DSD external programs like DSDPLUS by Network Sink (TCP:7355) would be great. 
DSDPLUS already works with an Audio interface, but TCP support would be amazing . 

If this DSD-FME already supports that, then this is great. To have more clients could probably be covered by having multiple Network Sink outputs going to different instances on different ports.

**Comment by AlexandreRouma** [comment]
No plan to support multiple clients for performance reasons. Future versions will allow multiple sinks per stream anyway so you'll be able to add a second network sink as needed.
