### ISSUE TITLE
Latest MacOS version competely broken

### ISSUE THREAD

**Issue by loewal** [AlexandreRouma/SDRPlusPlus#990]
**Hardware**
- CPU: iMac 21,5"
- RAM: 8Gb
- GPU: 
- SDR: SDRDX

**Software**
- Operating System: Ventura
- SDR++: compilation of #924

**Bug Description**
The app starts up, but is completely empty; without any module;
Previous version restored and is oke.

**Screenshots**
Add any screenshot that is relevant to the bug (GUI error messages, strange behavior, graphics glitch, etc...).

**Additional info**
Add any other relevant information.
![Scherm­afbeelding 2023-02-15 om 09 46 37](https://user-images.githubusercontent.com/7289719/218979714-ca349ae1-cbc6-4d34-8880-e3cf27370f3a.jpg)

**Comment by AlexandreRouma** [comment]
924 is an experimental branch, it's not finished and won't work.
Never download any build that isn't from the `master` branch.
The correct place to download nightly builds is always https://www.sdrpp.org/nightly

**Comment by loewal** [comment]
Okay Alexandre,
Merci/Thanks!
