### ISSUE TITLE
Would not compile on M1 as of today.

### ISSUE THREAD

**Issue by michaelgeorge001** [AlexandreRouma/SDRPlusPlus#992]
I know a lot of cmake stuff was updated today. I was able to compile without issue on an M1 Mac mini up until this morning without issue. I was  in the process of writing a detailed procedure to share with other Mac Silicon users when I got hung up.

I spun up a clean Ventura VM and was compiling and documenting each section as I went along. Everything was fine until it started to build the source modules in the last stage. That was when I started getting a lot of `clang: error: no such file or directory: '@SDRPP_MODULE_COMPILER_ARGS@'` errors.

I realized that during the cleanup that `"SDRPP_MODULE_COMPILER_ARGS"` was replaced with `"SDRPP_COMPILER_FLAGS"`. The only place left that `"SDRPP_MODULE_COMPILER_ARGS"` existed was in the file "sdrpp_module.cmake".

Once I changed all reference of `"SDRPP_MODULE_COMPILER_ARGS"` to `"SDRPP_COMPILER_FLAGS"` in that file, I was able to compile a Mac Silicon version correctly.

Mike

**Comment by AlexandreRouma** [comment]
Looks like I was a bit too tired to code yesterday.
Should be fixed in the latest commit, reopen if not
