### ISSUE TITLE
SoapySDR source missing from MacOS nightly build

### ISSUE THREAD

**Issue by yoramrotbach** [AlexandreRouma/SDRPlusPlus#996]
**Feature description**
Hi
Please add SoapySDR option to MacOS nightly build.

Thank you

Yoram

**Comment by AlexandreRouma** [comment]
Not possible to do reliably.

Additionally, SoapySDR support is being phased out since basically all the hardware soapy supports is supported natively.

Not sure which hardware you're using specifically but there's very likely a native source for it.

**Comment by yoramrotbach** [comment]
Hello
Thanks for the quick response.
I'm using CaribouLite SDR which currently is supported only by SoapySDR API.

Yoram

**Comment by AlexandreRouma** [comment]
The cariboulite is a raspberry pi SDR... Why would you need soapy on the Mac to use it?
Just use SDR++ server on the pi and connect to it.

Moreover native support for the cariboulite is coming soon.

**Comment by yoramrotbach** [comment]
Thank you
Will wait patiently
All the best
Yoram

**Comment by AlexandreRouma** [comment]
There is no need to wait, Soapy is supported on the Pi. Just use SDR++ server and you'll see soapy in the remote source list.

**Comment by Aldekein** [comment]
Hey, I'm trying to use SoapySDR in a Mac build to connect to and SDRPlay compatible SDR Receiver RSp1 with MSi001 and MSi2500 Main Chips. It's a pity to see it's being removed.

**Comment by aneitzel** [comment]
Same here - with removal of SOAPY my SDRplay compatible SDR dont work anymore. SDRplay dont support my "compatibel" device, so SDRplay native support is not an option. 

**Is there any way to have it BACK in SDR++? Its sad to remove things which worked good so far.**
