### ISSUE TITLE
Font not loading on nightly releases

### ISSUE THREAD

**Issue by MrTalon63** [AlexandreRouma/SDRPlusPlus#998]
**Hardware**
- CPU: i9-9900k
- RAM: 64GB 3200MHz
- GPU: GTX1070
- SDR: Local

**Software**
- Operating System: Windows 10 22H2, 64 bit
- SDR++: 1.1.0 9:22:12, February 23 2023

**Bug Description**
The font is not being loaded properly. Console output doesn't mention any errors regarding loading other than `[error] Menu element is missing name key`

**Steps To Reproduce**
1. Launch sdrpp executable
2. Wait for loading to complete

**Screenshots**
![image](https://user-images.githubusercontent.com/36423105/221312023-81cc3021-fb09-4889-8740-52edcc1f203f.png)

**Comment by AlexandreRouma** [comment]
Can't reproduce on any system including both my dev machines and a clean VM.

Almost certainly just an issue updating from an older version, a corrupted (or incorrectly modified) config  or bad file permissions (doubt it).

Delete config.json and try again.
